//==================================================================================
// Copyright (c) 2016 , Advanced Micro Devices, Inc.  All rights reserved.
//
/// \author AMD Developer Tools Team
/// \file pdRemoteProcessDebuggerCommandId.h
///
//==================================================================================

//------------------------------ pdRemoteProcessDebuggerCommandId.h ------------------------------

#ifndef __PDREMOTEPROCESSDEBUGGERCOMMANDID_H
#define __PDREMOTEPROCESSDEBUGGERCOMMANDID_H

enum pdRemoteProcessDebuggerCommandId
{
    PD_INITIALIZE_PROCESS_DEBUGGER_CMD,
    PD_LAUNCH_DEBUGGED_PROCESS_CMD,
    PD_LAUNCH_DEBUGGED_PROCESS_IN_SUSPENDED_MODE_CMD,
    PD_CONTINUE_DEBUGGED_PROCESS_FROM_SUSPENDED_CREATION_CMD,
    PD_DEBUGGED_PROCESS_EXISTS_CMD,
    PD_TERMINATE_DEBUGGED_PROCESS_CMD,
    PD_IS_DEBUGGING_64_BIT_APPLICATION_CMD,
    PD_AMOUNT_OF_DEBUGGED_PROCESS_THREADS_CMD,
    PD_GET_THREAD_ID_CMD,
    PD_SET_SPY_API_THREAD_ID_CMD,
    PD_SPIES_API_THREAD_INDEX_CMD,
    PD_MAIN_THREAD_ID_CMD,
    PD_SPIES_API_THREAD_ID_CMD,
    PD_DEBUGGED_PROCESS_ID_CMD,
    PD_IS_SPY_API_THREAD_RUNNING_CMD,
    PD_SUSPEND_DEBUGGED_PROCESS_CMD,
    PD_RESUME_DEBUGGED_PROCESS_CMD,
    PD_IS_DEBUGGED_PROCESS_SUSPENDED_CMD,
    PD_SUSPEND_DEBUGGED_PROCESS_THREAD_CMD,
    PD_RESUME_DEBUGGED_PROCESS_THREAD_CMD,
    PD_GET_DEBUGGED_THREAD_CALL_STACK_CMD,
    PD_FILL_CALL_STACK_DEBUG_INFO_CMD,
    PD_FILL_THERAD_CREATED_EVENT_CMD,
    PD_CAN_GET_CALL_STACKS_CMD,
    PD_CAN_MAKE_THREAD_EXECUTE_FUNCTION_CMD,
    PD_MAKE_THREAD_EXECUTE_FUNCTION_CMD,
    PD_FUNCTION_EXECUTION_MODE_CMD,
    PD_AFTER_API_CALL_ISSUED_CMD,
    PD_REMOTE_TO_LOCAL_FILE_PATH_CMD,
    PD_REMOTE_CAN_GET_HOST_VARIABLES_CMD,
    PD_REMOTE_GET_HOST_LOCALS_CMD,
    PD_REMOTE_GET_HOST_VARIABLE_VALUE_CMD,
    PD_REMOTE_CAN_PERFORM_HOST_DEBUGGING,
    PD_REMOTE_IS_API_OR_KERNEL_BP_CMD,
    PD_REMOTE_HOST_BREAK_REASON_CMD,
    PD_REMOTE_HOST_BREAKPOINT_LOCATION_CMD,
    PD_REMOTE_SET_HOST_BP_CMD,
    PD_REMOTE_DELETE_HOST_BP_CMD,
    PD_REMOTE_PERFORM_HOST_STEP_CMD,
    PD_REMOTE_SUSPEND_HOST_DEBUGGED_PROCESS,
    PD_REMOTE_GET_BP_TRIGGERING_THREAD_INDEX_CMD,

    // Addidtional aid functions:
    PD_HANDLE_DEBUG_EVENT,
};


#endif //__PDREMOTEPROCESSDEBUGGERCOMMANDID_H

