# Copyright (c) 2014 Advanced Micro Devices, Inc. All rights reserved.
#
# Main scons build file for WebServer (GPUPerfStudio)
#
from CXL_init import *

Import('*')
env = CXL_env.Clone()

appName="CXLGraphicsServer"

initGPSBackend (env)
UseBoost(env)

env.Prepend(CCFLAGS =
[
    "-D'LOG_MODULE=\"" + appName + "\"'"
])

env.Append (CPPPATH =[
    env['CXL_commonproj_dir'],
    env['CXL_commonproj_dir'] + '/../../CodeXL/Components/Graphics/Server/Common',
    env['CXL_commonproj_dir'] + '/../../CodeXL/Components/Graphics/Server/Common/Linux',
    ])

# These need to be in their dependency order. Most derived first
env['LIBS'] = \
[
    #internal libraries
    "libCXLGraphicsServerCommon",
    "libCXLOSWrappers",
    "libCXLBaseTools",
    #boost
    'libboost_program_options.a',
    'libboost_filesystem.a',
    'libboost_system.a',
    #enternal libraries
    "rt",
    "pthread",
    "dl",
]

# build the GPUPerfStudio executable

sources = \
[
    "Commands.cpp",
    "ClientRequestThread.cpp",
    "Inject.cpp",
    "OSDependent.cpp",
    "PluginResponseThread.cpp",
    "ProcessTracker.cpp",
    "RenderStallThread.cpp",
    "ShutdownThread.cpp",
    "WebServer.cpp",
]

exe = env.Program(
    target = appName,
    source = sources)

# Installing libraries
libInstall = env.Install(
    dir = env['CXL_lib_dir'],
    source = (exe))

Return('libInstall')
