//==============================================================================
// Copyright (c) 2015-2016 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief THIS CODE WAS AUTOGENERATED BY PASSTHROUGHGENERATOR ON 04/14/16
//==============================================================================

#ifndef _HSATRACEINTERCEPTION_H_
#define _HSATRACEINTERCEPTION_H_

#include <hsa_api_trace.h>

extern ApiTable* g_realHSAFunctions;    ///< table of real HSA functions
extern ExtTable* g_realHSAExtFunctions; ///< table of real HSA extension functions

/// Intercepts HSA APIs for this HSA Profiler agent
void InitHSAAPIInterceptTrace(ApiTable* pTable);

/// Cleans up API interception for this HSA Profiler agent
void DoneHSAAPIInterceptTrace();

#endif // _HSATRACEINTERCEPTION_H_

