//==================================================================================
// Copyright (c) 2016 , Advanced Micro Devices, Inc.  All rights reserved.
//
/// \author AMD Developer Tools Team
/// \file acStringConstants.h
///
//==================================================================================


#ifndef __ACSTRINGCONSTANTS
#define __ACSTRINGCONSTANTS
// Infra:
#include <AMDTBaseTools/Include/AMDTDefinitions.h>

// General strings:
#define AC_STR_Comma L","
#define AC_STR_CommaA ","
#define AC_STR_Dot '.'
#define AC_STR_Tab "\t"
#define AC_STR_NewLine L"\n"
#define AC_STR_NewLineA "\n"
#define AC_STR_Quot "\""
#define AC_STR_NotAvailable L"N/A"
#define AC_STR_Space L" "
#define AC_STR_SpaceA " "
#define AC_STR_QuotSpace "\" "
#define AC_STR_PERCENT L"%"
#define AC_STR_0 L"0"
#define AC_STR_1 L"1"
#define AC_STR_Empty L""

// CSV export header string:
#define AC_STR_ExportFileHeaderSeperator L"/////////////////////////////////////////////////////////////////////////////////\n"
#define AC_STR_ExportFileHeaderTitlePrefix L"// This file contains "
#define AC_STR_ExportFileHeaderProjectName L"// Project name: "
#define AC_STR_ExportFileHeaderGenerationDate L"// Generation date: "
#define AC_STR_ExportFileHeaderGenerationTime L"// Generation time: "
#define AC_STR_ExportFileHeaderGeneratedBy L"// Generated by CodeXL\n"
#define AC_STR_ExportFileHeaderWebSite L"// http://gpuopen.com/\n"

// Application Components items
#define AC_STR_true L"true"
#define AC_STR_false L"false"
#define AC_STR_ErrorMessageError L"Error"
#define AC_STR_ErrorMessageWarning L"Warning"
#define AC_STR_ErrorMessageInformation L"Information"

#define AC_STR_Question "Question"

// Layout XML Nodes:
#define AC_STR_GUILayoutsGUILayoutsNode "GUILayouts"
#define AC_STR_GUILayoutsGUILayoutsFileVersionNode "GUILayoutsFileVersion"
#define AC_STR_GUILayoutsLayoutNode "Layout"
#define AC_STR_GUILayoutsLayoutDataNode "LayoutData"
#define AC_STR_GUILayoutsViewersNode "Viewers"
#define AC_STR_GUILayoutsViewerNode "Viewer"
#define AC_STR_GUILayoutsViewerNameNode "ViewerName"
#define AC_STR_GUILayoutsViewerShownNode "ViewerShown"
#define AC_STR_GUILayoutsWindowSizeNode "WindowSize"
#define AC_STR_GUILayoutsWindowPositionNode "WindowPosition"
#define AC_STR_GUILayoutsExecutionModeNode "ExecutionMode"
#define AC_STR_GUILayoutsExecutionModeDebugger "Debugger"
#define AC_STR_GUILayoutsExecutionModeProfiler "Profiler"
#define AC_STR_GUILayoutsExecutionModeAnalyzer "Analyze"
#define AC_STR_GUILayoutsPerformanceGraphViewSeperatorPosition "PerformanceGraphViewSeperatorPosition"
#define AC_STR_GUILayoutsStatisticsViewSeperatorPosition "StatisticsViewSeperatorPosition"
#define AC_STR_GUILayoutsCodeXLRevisionNode "RevisionNumber"


// GUI layouts Unicode strings:
#define AC_STR_GUILayoutsMultipleLayoutsForOneExecModeError L"Multiple layouts found for one execution mode"
#define AC_STR_GUILayoutsMultipleLayoutsForOneViewerError L"Multiple layouts found for one viewer"
#define AC_STR_GUILayoutsViewerNameStateVarsCompare L"StateVariablesCompareViewer"
#define AC_STR_GUILayoutsViewerNameSourceCode L"SourceCodeViewer"
#define AC_STR_GUILayoutsViewerNameShadersSourceCode L"ShadersSourceCodeViewer"
#define AC_STR_GUILayoutsViewerNameTexture L"TexturesAndBuffersViewer"
#define AC_STR_GUILayoutsViewerNameStatistics L"StatisticsViewer"
#define AC_STR_GUILayoutsViewerNameMemoryAnalysis L"MemoryAnalysisViewer"
#define AC_STR_GUILayoutsViewerNameCommandQueues L"CommandQueuesViewer"

// acWXListCtrl:
#define AC_STR_FindDialogTextNotFoundMessage L"The following text was not found:\n\n\"%ls\"\n\n"
#define AC_STR_FindDialogMessageBoxTitle L"Information"
#define AC_STR_FindDialogFindReachedEndOfSearchMessage L"Find reached the starting point of the search."

// acDataView:
#define AC_STR_DataViewLinkImageAndDataViews "Link between the Image and Data Views"
#define AC_STR_DataViewGridZoom "Grid Zoom:"
#define AC_STR_DataViewShowNormalizedValues "Show values normalized to [0..255] range"
#define AC_STR_DataViewShowHexValues "Show hexadecimal values"

// acImageItem:
#define AC_STR_ImageItemGeneratingPreviewMessage L"Generating\nPreview..."

// acWXListCtrlForDirectories:
#define AC_STR_AdditionalDirectoriesAddDirectory L"Add directory..."
#define AC_STR_AdditionalDirectoriesDirSearch L"Source code directory path"

// acHTMLWindows:
#define AC_STR_Copy L"&Copy\tCtrl+C"
#define AC_STR_SelectAll "Select &All\tCtrl+A"
#define AC_STR_Hexadecimaldisplay "&Hexadecimal Display"

// acTextFilterCtrl:
#define AC_STR_breakpointsTextFilterInitialText "Filter here..."

// acImagesBuffersManager
#define AC_STR_ImageViewThumbnailViewItem L"Click to view \n%ls"

// Progress:
#define AC_STR_ProgressBarPleaseWaitMessage L"Please Wait..."

// Source code view:
#define AC_STR_sourceCodeFileReadOnlyQuestion "The file %s is write-protected.\nOverwrite the file?"
#define AC_STR_sourceCodeFileLanguage "Language"
#define AC_STR_sourceCodeCut "Cut"
#define AC_STR_sourceCodeCopy "Copy"
#define AC_STR_sourceCodePaste "Paste"
#define AC_STR_sourceCodeCutShortcut "Ctrl+X"
#define AC_STR_sourceCodeCopyShortcut "Ctrl+C"
#define AC_STR_sourceCodePasteShortcut "Ctrl+V"
#define AC_STR_sourceCodeSaveFileAs "Save File As"
#define AC_STR_sourceCodeViewSelectAll "Select All"
#define AC_STR_sourceCodeViewSelectAllShortcut "Ctrl+A"

// Find Widget:
#define AC_STR_matchCase "Match &Case"
#define AC_STR_find "&Find"

// List control:
#define AC_STR_listCtrlCopy "Copy"
#define AC_STR_listCtrlFind "Find"
#define AC_STR_listCtrlFindNext "Find Next"
#define AC_STR_listCtrlPaste "Paste"
#define AC_STR_listCtrlSelectAll "Select All"
#define AC_STR_listCtrlDeleteSelected "&Delete Selected"

// Tree control:
#define AC_STR_treeCtrlExpandAll "Expand All"
#define AC_STR_treeCtrlCollapseAll "Collapse All"

// Chart:
#define AC_STR_chartNoData "No Data Available"

// Convert:
#define AC_STR_ImageLimitReached L"Image size of 1GB reached and could not be opened."

// Message dialog
#define AC_STR_DoNotShowAgain "Do not show this message again"

// Base dialog
#define AC_STR_DefaultOKButton "OK"
#define AC_STR_Cancel_Button "Cancel"

// Multiplot
#define AC_STR_CounterSelectionString "Double-click to add or remove counters..."

// acCustomPlot
#define AC_STR_CustomPlotDragString "application/x-cxlcustomplot"

// HTML definitions (are used for extraction of HTML text to CSV):
#define AC_STR_HTMLTable "table"
#define AC_STR_HTMLTH "th"
#define AC_STR_HTMLTR "tr"
#define AC_STR_HTMLTD "td"

// General strings:
#define AC_STR_NotAvailable L"N/A"
#define AC_STR_NotAvailableA "N/A"

// "Send Error Report" dialog:
#define AC_STR_SendErrorReportTitle "Error Report"
#define AC_STR_SendErrorReportSendButton "&Send"
#define AC_STR_SendErrorReportDontSendButton "&Don't Send"
#define AC_STR_SendErrorReportPrivacyPolicyButtonCaption "&Privacy Policy"
#define AC_STR_SendErrorReportHeaderDescription "Information that will be sent to the %1 support team."
#define AC_STR_SendErrorReportSucceededHeaderDescription "Thank you, information was submitted to the %1 support team."
#define AC_STR_SendErrorReportFailedHeaderDescription "Error report failed.\n\nPlease add the issue to CodeXL forum https://github.com/GPUOpen-Tools/CodeXL/issues."
#define AC_STR_SendErrorReportCallStackTitle "Call stack:"
#define AC_STR_SendErrorReportOperatingSystemTitle "Operating System:"
#define AC_STR_SendErrorReportDetailsDialogTitle " %1 error details"
#define AC_STR_SendErrorReportDialogTitle "Error Report Status"
#define AC_STR_SendErrorReportString1 "%1 has encountered a problem. We are very sorry for the inconvenience."
#define AC_STR_SendErrorReportString2 "Please tell %1 support about this problem."
#define AC_STR_SendErrorReportString3 "We have created an error report which will help us improve %1. We will treat this report as confidential and anonymous. No personal data will be transmitted other than\nwhat you provide to us."
#define AC_STR_SendErrorReportString4 "To see what data this error report contains and how it will be used, "
#define AC_STR_SendErrorReportClickHere "click here."
#define AC_STR_sendErrorReportClickHereLink "click_here"
#define AC_STR_SendErrorReportStringProxy1 "If you are using an HTTP proxy server, "
#define AC_STR_SendErrorReportStringProxy2 "set it up"
#define AC_STR_SendErrorReportStringProxy3 " before sending the report."
#define AC_STR_SendErrorReportStringProxyLink "proxy_setup"
#define AC_STR_SendErrorReportString5 "What were you doing when the problem happened (optional)?"
#define AC_STR_SendErrorReportString6 "Email address (optional):"
#define AC_STR_pleaseWaitReportingErrorToCRMSystem "Please wait, sending error report to CodeXL support..."

// Privacy policy related items:
#define AC_STR_PrivacyPolicyURL L"http://www.amd.com/us/aboutamd/Pages/privacy.aspx"
#define AC_STR_PrivacyPolicyUserInformationDisclaimer "This information is used to help AMD analyze system problems and improve this product.\nWe will not share this information without your permission.\nSee AMD's privacy policy for more details."

// Check for updates dialog ASCII Strings:
#define AC_STR_CheckForUpdatesPRODUCTNAMEConst "PRODUCTNAME"
#define AC_STR_CheckForUpdatesPRODUCTNAMEConstW L"PRODUCTNAME"
#define AC_STR_CheckForUpdatesEnvVarName L"%ls_UPDATER_URL"

#define AC_STR_CheckForUpdatesVersionHistoryFolderRelativeURL "/version_history/"
#define AC_STR_CheckForUpdatesPHPExtension ".php"
#define AC_STR_CheckForUpdatesGraphicRemedyWebsite "http://gpuopen.com/"
#define AC_STR_CheckForUpdatesNoNewUpdatesMessageTitle "No new version available"
#define AC_STR_CheckForUpdatesLatestVersionPageRelativeURLAndEchoParam "/latest_version.php?echo=1"
#define AC_STR_CheckForUpdatesLatestVersionPageWindowsOSParam "&os=windows"
#define AC_STR_CheckForUpdatesLatestVersionPageLinuxOSParam "&os=linux"
#define AC_STR_CheckForUpdatesLatestVersionPageMacOSParam "&os=mac"
#define AC_STR_CheckForUpdatesLatestVersionPage32BitOSParam "&osbits=32"
#define AC_STR_CheckForUpdatesLatestVersionPage64BitOSParam "&osbits=64"
#define AC_STR_CheckForUpdatesLatestVersionPageGNUCCompiler3Param "&cppbuild=3"
#define AC_STR_CheckForUpdatesLatestVersionPageGNUCCompiler4Param "&cppbuild=4"
#define AC_STR_CheckForUpdatesXMLFileName L"PRODUCTNAMEUpdates.xml"
#define AC_STR_CheckForUpdatesDownloadingAvailableVersion "Downloading latest available version"
#define AC_STR_CheckForUpdatesNewUpdatesAvailable "New software updates are available!"
#define AC_STR_CheckForUpdatesDescriptionPageHTMLFormat "<html><body style=\"font-size:small;margin:0\"><b>%1</b><br><br>%2</body></html>"
#define AC_STR_CheckForUpdatesDescriptionProductUpToDate1 "%1 is up to date"
#define AC_STR_CheckForUpdatesDescriptionProductUpToDate2 "You have the latest %1 version installed on your computer"
#define AC_STR_CheckForUpdatesVersionIsAvailableNow "Version %s is available now"
#define AC_STR_CheckForUpdatesVersionIsAvailableTitle "%1 version %2 is now available (version %3 is currently installed)"
#define AC_STR_CheckForUpdatesDownloading "Downloading..."
#define AC_STR_CheckForUpdatesConnectionError "Connection Error"
#define AC_STR_CheckForUpdatesConnectionErrorText "Failed to connect to AMD server<br>Please check your internet connection and proxy settings."
#define AC_STR_CheckForUpdatesConnectionErrorText2 "<br>Go to PRODUCTNAME download page in <a href='http://gpuopen.com/'>gpuopen.com/</a> for latest version information."
#define AC_STR_CheckForUpdatesConnectionErrorText3 "Failed to update %1"
#define AC_STR_CheckForUpdatesStatusText "%1 installed version is: %2. Checking for updates..."
#define AC_STR_CheckForUpdatesDescriptionText "To find %1 new version details go to <a href='http://gpuopen.com/%2/'>%3 web page</a>"
#define AC_STR_CheckForUpdatesDownloadError "Download Error"
#define AC_STR_CheckForUpdatesDownloadErrorText "<br>Go to PRODUCTNAME download page in <a href='http://gpuopen.com/'>gpuopen.com/</a> and download the version manually"
#define AC_STR_CheckForUpdatesDownloadTarball "Download tarball"
#define AC_STR_CheckForUpdatesDownloadRPM "Download RPM"
#define AC_STR_CheckForUpdatesDownloadDebianPackage "Download Debian Package"
#define AC_STR_CheckForUpdatesLoadingMessage "Loading %1 new version details..."
#define AC_STR_CheckForUpdatesWindowTitle "%1 - Check for updates"

#define AC_STR_CheckForUpdatesFailureTitle "PRODUCTNAME Update Failure"
#define AC_STR_CheckForUpdatesDownloadCompleteTar "File download is complete. <br>Extract from path: %s "
#define AC_STR_CheckForUpdatesDownloadCompleteRPM "File download is complete. <br>Execute RPM from path: %s "
#define AC_STR_CheckForUpdatesDownloadCompleteDebian "File download is complete. <br>Install the Debian package from the following path: %s "
#define AC_STR_CheckForUpdatesDownloadComplete "Download Complete"
#define AC_STR_CheckForUpdatesSelectDestinationFolder "Select the destination folder"
#define AC_STR_CheckForUpdatesInvalidDestinationFolderErrorTitle "Destination folder does not exist"
#define AC_STR_CheckForUpdatesInvalidDestinationFolderErrorMsg "Please select a valid destination folder."
#define AC_STR_CheckForUpdatesTempFolderLabelText "Temporary folder for install package:"
#define AC_STR_CheckForUpdatesDescriptionPageHTMLFormat "<html><body style=\"font-size:small;margin:0\"><b>%1</b><br><br>%2</body></html>" // NZ 

#if (AMDT_BUILD_TARGET == AMDT_WINDOWS_OS)
    #if (AMDT_BUILD_CONFIGURATION != AMDT_DEBUG_BUILD)
        #define AC_STR_CheckForUpdatesServerXMLFileName L"http://developer.amd.com/assets//PRODUCTNAMEUpdate_win32.xml"
        #define AC_STR_CheckForUpdatesServerXMLFileNameFor64Bits L"http://developer.amd.com/assets//PRODUCTNAMEUpdate_win64.xml"
    #else
        #define AC_STR_CheckForUpdatesServerXMLFileName L"http://bdclin64-gdt-jenkins.amd.com:8080/view/PRODUCTNAME/job/PRODUCTNAME-Full/lastSuccessfulBuild/artifact/main/PRODUCTNAME/Installer/PRODUCTNAMEUpdate_win32.xml"
        #define AC_STR_CheckForUpdatesServerXMLFileNameFor64Bits L"http://bdclin64-gdt-jenkins.amd.com:8080/view/PRODUCTNAME/job/PRODUCTNAME-Full/lastSuccessfulBuild/artifact/main/PRODUCTNAME/Installer/PRODUCTNAMEUpdate_win64.xml"
    #endif
#elif (AMDT_BUILD_TARGET == AMDT_LINUX_OS)
    #if (AMDT_BUILD_CONFIGURATION != AMDT_DEBUG_BUILD)
        #define AC_STR_CheckForUpdatesServerXMLFileName L"http://developer.amd.com/assets//PRODUCTNAMEUpdate_linux64.xml"
    #else
        #define AC_STR_CheckForUpdatesServerXMLFileName L"http://bdclin64-gdt-jenkins.amd.com:8080/view/PRODUCTNAME/job/PRODUCTNAME-Full-Linux/lastSuccessfulBuild/artifact/main/PRODUCTNAMEUpdate_linux64.xml"
    #endif
#else
    # error unkown system
#endif

// images
#define AC_STR_image_folder L"folder.png"
#define AC_STR_image_file L"file.png"

#define AC_STR_image_cancel L"cancel.png"
#define AC_STR_image_open L"open.png"
#define AC_STR_image_save L"save.png"

#define AC_STR_image_back L"back.png"
#define AC_STR_image_forward L"forward.png"
#define AC_STR_image_toParent L"toParent.png"
#define AC_STR_image_newFolder L"newFolder.png"
#define AC_STR_image_detailMode L"detailMode.png"
#define AC_STR_image_listMode L"listMode.png"


// "Help About" dialog:
#define AC_STR_HelpAboutGLCLTitle " About "
#define AC_STR_HelpAboutVersion "Version: "
#define AC_STR_HelpAboutRadeonSoftwareVersion "Radeon Software version: "
#define AC_STR_HelpAboutWebPageText "gpuopen.com"
#define AC_STR_HelpAboutWebPage "http://gpuopen.com/"
//#define AC_STR_HelpAboutLGPLCopyRightCaption "LGPL Components:"
//#define AC_STR_HelpAboutLGPLCopyRightHeader "The GNU Lesser General Public License, version 2.1 (LGPL-2.1)\nGNU Lesser General Public License"
//#define AC_STR_HelpAboutLGPLCopyRightBody "Copyright (C) 1991, 1999 Free Software Foundation, Inc.\n51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA\nEveryone is permitted to copy and distribute verbatim copies\nof this license document, but changing it is not allowed.\nUse of the Qt library is governed by the GNU\nLesser General Public License version 2.1 (LGPL v 2.1)."

// EULA dialog:
#define AC_STR_EULADirectory L"Legal"
#define AC_STR_EULAFileName L"CodeXLEndUserLicenseAgreement-Linux"
#define AC_STR_EULAFileExtension L"htm"
// #define AF_STR_EULAMacTitle L" CodeXL Mac End-User License Agreement"
#define AC_STR_EULALinuxTitle " CodeXL End-User License Agreement"
#define AC_STR_EULASubTitle "Please read the following License Agreement\n      You must accept the terms of this agreement before using CodeXL"
// #define AF_STR_EULAMacESTitle L" CodeXL iPhone End-User License Agreement"
// #define AF_STR_EULALinuxESTitle L" CodeXL Linux ES End-User License Agreement"
#define AC_STR_EULA_Agree "I &accept the terms in the License Agreement"
#define AC_STR_EULA_DoNotAgree "I &do not accept the terms in the License Agreement"
#define AC_STR_EULALoadHtmlError L"Could not load the License Agreement"
#define AC_STR_EULALoadDialogError "CodeXL failed to load the License Agreement dialog"
#define AC_STR_EULALoadDialogErrorUnicode L"CodeXL failed to load the License Agreement dialog"
#define AC_STR_EULANotAcceptedMessage "You must accept the terms of this agreement before using CodeXL"
#define AC_STR_EULA_NextButton "&Next >"
#define AC_STR_EULA_ExitButton "&Exit"

// Ribbon manager
#define AC_STR_BGWithParam "background-color: %1;"
#define AC_STR_CSS_TooltipStyle "border: 1px solid %1; border-radius: 2px; padding: 2px; background-color: %2;"

// timeline filter
#define AC_STR_TimelineFilterCPUThreads "CPU Threads (%1 of %2)"
#define AC_STR_TimelineFilterDlgCaption "Display Filters"

// export thread to csv
#define AC_STR_ExportThreadToCSVFileName "Thread_%1"

/// used for syntax highlighting
#define AC_STR_FILE_EXTENSIONS_QREGEXP "\\.cpp|hpp|cl|cxlil|cxlisa|vs|hs|ps|gs|ds|cs|hlsl|c|h|css|vert|tesc|tese|frag|comp|geom|glsl|fs|java|htm|xml|gdb|gdbvs|bpt"

// units
#define AC_STR_UnitsMilliseconds "ms"

// replacement string
#define AC_STR_PathReplacementString L"$CXL_Install_Path$\\"

#endif  // __ACSTRINGCONSTANTS
