#!/bin/bash

# CodeXLGpuProfilerRun requires bash. Do not remove the above shebang line!

# ----------------------------------------------------------------------------------------------------------------------------------
# File name: CodeXLGpuProfilerRun
# This script sets CodeXLGpuProfilerRun's related environment variables and
# execute the CodeXLGpuProfilerRun binary executable.
#
# (c) 2015 Advanced Micro Devices Inc. All Rights Reserved.
# ----------------------------------------------------------------------------------------------------------------------------------

# Get this script full path:
if echo "$0" | grep '^/' ; then
	thisScriptFullPath="$0"
else
	thisScriptFullPath=`pwd`/$0
fi

# Enable the use of symbolic links to the script
if [ -h ${thisScriptFullPath} ]
then
    LINKTARGET=`readlink -f "$thisScriptFullPath"`
    thisScriptFullPath=${LINKTARGET}
fi

# CodeXLGpuProfilerRun's binaries directory is this scripts directory:
CodeXLGpuProfilerRunBinariesDir=`dirname "$thisScriptFullPath"`

# Calculate CodeXLGpuProfilerRun's binary executable path:
CodeXLGpuProfilerRunBinaryExePath="${CodeXLGpuProfilerRunBinariesDir}/CodeXLGpuProfiler-Internal"

# Obtain libstdc++ needed version
CRUNTIMEPATH=$(ldconfig -p | grep libstdc++.so.6 | grep 64)
if [ -z "$CRUNTIMEPATH" ] ; then
   CRUNTIMEPATH=$(/sbin/ldconfig -p | grep libstdc++.so.6 | grep 64)
fi
CRUNTIMEFILE=${CRUNTIMEPATH##*>}
# Test if current system C++ runtime is older from CodeXL version needed
CXL_CLIB=""
NEWCRUNTIME=$(strings $CRUNTIMEFILE | grep GLIBCXX_3.4.16)
if [ -z "$NEWCRUNTIME" ];then
    # System C++ runtime is older from CodeXL
    CXL_CLIB="${CodeXLGpuProfilerRunBinariesDir}/RuntimeLibs/x86_64"
fi

# Add CodeXLGpuProfilerRun's binaries directory to LD_LIBRARY_PATH:
if [ -z "$LD_LIBRARY_PATH" ]; then
	export LD_LIBRARY_PATH="${CodeXLGpuProfilerRunBinariesDir:${CXL_CLIB}}"
else
	export LD_LIBRARY_PATH="${CodeXLGpuProfilerRunBinariesDir}:${CXL_CLIB}:$LD_LIBRARY_PATH"
fi

# Run CodeXLGpuProfiler:
eval "$CodeXLGpuProfilerRunBinaryExePath $@"

