//==============================================================================
// Copyright (c) 2015-2016 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief THIS CODE WAS AUTOGENERATED BY PASSTHROUGHGENERATOR ON 05/18/16
//==============================================================================

#ifndef _HSARTMODULEFUNCTABLES_H_
#define _HSARTMODULEFUNCTABLES_H_

#define HSA_RUNTIME_API_TABLE \
    X(status_string) \
    X(init) \
    X(shut_down) \
    X(system_get_info) \
    X(system_extension_supported) \
    X(system_get_extension_table) \
    X(agent_get_info) \
    X(iterate_agents) \
    X(agent_get_exception_policies) \
    X(agent_extension_supported) \
    X(signal_create) \
    X(signal_destroy) \
    X(signal_load_acquire) \
    X(signal_load_relaxed) \
    X(signal_store_relaxed) \
    X(signal_store_release) \
    X(signal_exchange_acq_rel) \
    X(signal_exchange_acquire) \
    X(signal_exchange_relaxed) \
    X(signal_exchange_release) \
    X(signal_cas_acq_rel) \
    X(signal_cas_acquire) \
    X(signal_cas_relaxed) \
    X(signal_cas_release) \
    X(signal_add_acq_rel) \
    X(signal_add_acquire) \
    X(signal_add_relaxed) \
    X(signal_add_release) \
    X(signal_subtract_acq_rel) \
    X(signal_subtract_acquire) \
    X(signal_subtract_relaxed) \
    X(signal_subtract_release) \
    X(signal_and_acq_rel) \
    X(signal_and_acquire) \
    X(signal_and_relaxed) \
    X(signal_and_release) \
    X(signal_or_acq_rel) \
    X(signal_or_acquire) \
    X(signal_or_relaxed) \
    X(signal_or_release) \
    X(signal_xor_acq_rel) \
    X(signal_xor_acquire) \
    X(signal_xor_relaxed) \
    X(signal_xor_release) \
    X(signal_wait_acquire) \
    X(signal_wait_relaxed) \
    X(queue_create) \
    X(soft_queue_create) \
    X(queue_destroy) \
    X(queue_inactivate) \
    X(queue_load_read_index_acquire) \
    X(queue_load_read_index_relaxed) \
    X(queue_load_write_index_acquire) \
    X(queue_load_write_index_relaxed) \
    X(queue_store_write_index_relaxed) \
    X(queue_store_write_index_release) \
    X(queue_cas_write_index_acq_rel) \
    X(queue_cas_write_index_acquire) \
    X(queue_cas_write_index_relaxed) \
    X(queue_cas_write_index_release) \
    X(queue_add_write_index_acq_rel) \
    X(queue_add_write_index_acquire) \
    X(queue_add_write_index_relaxed) \
    X(queue_add_write_index_release) \
    X(queue_store_read_index_relaxed) \
    X(queue_store_read_index_release) \
    X(region_get_info) \
    X(agent_iterate_regions) \
    X(memory_allocate) \
    X(memory_free) \
    X(memory_copy) \
    X(memory_assign_agent) \
    X(memory_register) \
    X(memory_deregister) \
    X(isa_from_name) \
    X(isa_get_info) \
    X(isa_compatible) \
    X(code_object_serialize) \
    X(code_object_deserialize) \
    X(code_object_destroy) \
    X(code_object_get_info) \
    X(code_object_get_symbol) \
    X(code_symbol_get_info) \
    X(code_object_iterate_symbols) \
    X(executable_create) \
    X(executable_destroy) \
    X(executable_load_code_object) \
    X(executable_freeze) \
    X(executable_get_info) \
    X(executable_global_variable_define) \
    X(executable_agent_global_variable_define) \
    X(executable_readonly_variable_define) \
    X(executable_validate) \
    X(executable_get_symbol) \
    X(executable_symbol_get_info) \
    X(executable_iterate_symbols) \

#define HSA_EXT_FINALIZE_API_TABLE \
    X(ext_program_create) \
    X(ext_program_destroy) \
    X(ext_program_add_module) \
    X(ext_program_iterate_modules) \
    X(ext_program_get_info) \
    X(ext_program_finalize) \

#define HSA_EXT_IMAGE_API_TABLE \
    X(ext_image_get_capability) \
    X(ext_image_data_get_info) \
    X(ext_image_create) \
    X(ext_image_destroy) \
    X(ext_image_copy) \
    X(ext_image_import) \
    X(ext_image_export) \
    X(ext_image_clear) \
    X(ext_sampler_create) \
    X(ext_sampler_destroy) \

#define HSA_EXT_AMD_API_TABLE \
    X(amd_coherency_get_type) \
    X(amd_coherency_set_type) \
    X(amd_profiling_set_profiler_enabled) \
    X(amd_profiling_get_dispatch_time) \
    X(amd_profiling_convert_tick_to_system_domain) \
    X(amd_signal_async_handler) \
    X(amd_async_function) \
    X(amd_signal_wait_any) \
    X(amd_image_get_info_max_dim) \
    X(amd_queue_cu_set_mask) \
    X(amd_memory_pool_get_info) \
    X(amd_agent_iterate_memory_pools) \
    X(amd_memory_pool_allocate) \
    X(amd_memory_pool_free) \
    X(amd_memory_async_copy) \
    X(amd_agent_memory_pool_get_info) \
    X(amd_agents_allow_access) \
    X(amd_memory_pool_can_migrate) \
    X(amd_memory_migrate) \
    X(amd_memory_lock) \
    X(amd_memory_unlock) \
    X(amd_memory_fill) \
    X(amd_interop_map_buffer) \
    X(amd_interop_unmap_buffer) \
    X(amd_image_create) \

#define HSA_VEN_AMD_LOADED_CODE_OBJECT_API_TABLE \
    X(ven_amd_loaded_code_object_query_host_address) \



#endif // _HSARTMODULEFUNCTABLES_H_

