import os

###############################################################################
# Delete a file from the VulkanServer folder
def DeleteFile(file, rootFolder):
    command = "rm -f "
    command = command + rootFolder
    command = command + "/Server/VulkanServer/"
    command = command + file
    os.system(command)

###############################################################################
# Method to clean up the temporary shared source files
def VulkanCleanup(target, source, env):
    for file in commonSources:
        DeleteFile(file, env.rootFolder)

    for file in headers:
        DeleteFile(file, env.rootFolder)
    return None

###############################################################################
# Main scons build file for VulkanServer

from CXL_init import *

Import('*')
env = CXL_env.Clone()

libName="CXLGraphicsServerVulkan"

initGPSBackend (env)
UseTinyXml (env)
UseGPUPerfAPI (env)
initVulkanSDK (env)
UseJpgLib (env)

env.Append (CPPPATH =[
    env['CXL_commonproj_dir'],
    env['CXL_commonproj_dir'] + '/../../CodeXL/Components/Graphics/Server/Common',
    env['CXL_commonproj_dir'] + '/../../CodeXL/Components/Graphics/Server/Common/Linux',
    ])

GDT_LOG_MODULE="-D'LOG_MODULE=\"VulkanServer\"'"
cpp_flags= ' ' + GDT_LOG_MODULE + ' ' + ' -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XLIB_KHR -fPIC -fvisibility=hidden -Wno-error '
original_cpp_flag=env['CPPFLAGS']
original_cpp_flag = original_cpp_flag + cpp_flags
env.Replace(CPPFLAGS = original_cpp_flag) 

linker_flags = ' -Wl,-z,defs '
env.Prepend(LINKFLAGS = linker_flags)

# These need to be in their dependency order, with most derived first
env['LIBS'] = \
[
    #local libraries
    "libCXLGraphicsServerCommon",
    "libCXLOSWrappers",
    "libCXLBaseTools",
    "libJpg",
    "png",
    "z",               #used by PNG
    "libboost_system.a",
    #external libraries
    "dl",
    "rt",
    "pthread",
]

# Vulkan specific source files
sources = \
[

# glslang
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/glslang_tab.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/Constant.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/InfoSink.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/Initialize.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/IntermTraverse.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/Intermediate.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/ParseHelper.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/PoolAlloc.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/RemoveTree.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/Scan.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/ShaderLang.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/SymbolTable.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/Versions.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/intermOut.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/limits.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/linkValidate.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/parseConst.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/reflection.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/preprocessor/Pp.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/preprocessor/PpAtom.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/preprocessor/PpContext.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/preprocessor/PpMemory.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/preprocessor/PpScanner.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/preprocessor/PpSymbols.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/preprocessor/PpTokens.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/MachineIndependent/propagateNoContraction.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/GenericCodeGen/CodeGen.cpp",
    env['VulkanSDK_src_dir']+ "glslang/glslang/GenericCodeGen/Link.cpp",

# OSDependent
    env['VulkanSDK_src_dir']+ "glslang/glslang/OSDependent/Unix/ossource.cpp",

# OGLCompilersDLL
    env['VulkanSDK_src_dir']+ "glslang/OGLCompilersDLL/InitializeDll.cpp",

# HLSL
    env['VulkanSDK_src_dir']+ "glslang/hlsl/hlslParseHelper.cpp",
    env['VulkanSDK_src_dir']+ "glslang/hlsl/hlslScanContext.cpp",
    env['VulkanSDK_src_dir']+ "glslang/hlsl/hlslOpMap.cpp",
    env['VulkanSDK_src_dir']+ "glslang/hlsl/hlslTokenStream.cpp",
    env['VulkanSDK_src_dir']+ "glslang/hlsl/hlslGrammar.cpp",

# SPIRV
    env['VulkanSDK_src_dir']+ "glslang/SPIRV/GlslangToSpv.cpp",
    env['VulkanSDK_src_dir']+ "glslang/SPIRV/InReadableOrder.cpp",
    env['VulkanSDK_src_dir']+ "glslang/SPIRV/Logger.cpp",
    env['VulkanSDK_src_dir']+ "glslang/SPIRV/SpvBuilder.cpp",
    env['VulkanSDK_src_dir']+ "glslang/SPIRV/SPVRemapper.cpp",
    env['VulkanSDK_src_dir']+ "glslang/SPIRV/doc.cpp",
    env['VulkanSDK_src_dir']+ "glslang/SPIRV/disassemble.cpp",

# common sources
    env['VulkanSDK_src_dir']+ "layers/vk_layer_extension_utils.cpp",
    env['VulkanSDK_src_dir']+ "layers/vk_layer_table.cpp",

# VKT sources
    "OS/Linux/VulkanServer.cpp",

    "VKT/FrameDebugger/vktFrameDebuggerLayer.cpp",

    "VKT/Interception/vktIntercept.cpp",

    "VKT/Objects/Wrappers/vktWrappedCmdBuf.cpp",
    "VKT/Objects/Wrappers/vktWrappedObject.cpp",
    "VKT/Objects/Wrappers/vktWrappedQueue.cpp",
    "VKT/Objects/vktInstanceBase.cpp",
    "VKT/Objects/vktWrappedObjectDatabase.cpp",
    "VKT/Objects/vktObjectDatabaseProcessor.cpp",

    "VKT/Profiling/vktCmdBufProfiler.cpp",
    "VKT/Profiling/vktCmdBufProfilerStatic.cpp",
    "VKT/Profiling/vktFrameProfilerLayer.cpp",
    "VKT/Profiling/vktTimestampedCmdBuf.cpp",

    "VKT/Rendering/vktImageRenderer.cpp",

    "VKT/Tracing/vktAPIEntry.cpp",
    "VKT/Tracing/vktThreadTraceData.cpp",
    "VKT/Tracing/vktTraceAnalyzerLayer.cpp",

    "VKT/Util/vktUtil.cpp",

    "VKT/vktInterceptManager.cpp",
    "VKT/vktLayerManager.cpp",
    "VKT/vktPlugin.cpp",
]

# build the VulkanServer shared library
soFiles = env.SharedLibrary(
    target = libName,
    source = sources)
install = soFiles

# Installing libraries
VulkanServer = env.Install(
    dir = env['CXL_lib_dir']+'/Plugins',
    source = (install))

# clean up the source files when everything is built
env.Command( 'done', 'libVulkanServer.so', VulkanCleanup )
CopyJSON(env)

Return('VulkanServer')
