@echo off

set CONFIG_NAME=%1
set D_SUFFIX=%2
set HYPHEN_D_SUFFIX=%3

rem Create the Output Folders:
if not exist ..\Output\%CONFIG_NAME% mkdir ..\Output\%CONFIG_NAME%
if not exist ..\Output\%CONFIG_NAME%\bin mkdir ..\Output\%CONFIG_NAME%\bin
if not exist ..\Output\%CONFIG_NAME%\bin\x64 mkdir ..\Output\%CONFIG_NAME%\bin\x64
if not exist ..\Output\%CONFIG_NAME%\bin\x86 mkdir ..\Output\%CONFIG_NAME%\bin\x86
if not exist ..\Output\%CONFIG_NAME%\bin\Legal mkdir ..\Output\%CONFIG_NAME%\bin\Legal
if not exist ..\Output\%CONFIG_NAME%\bin\platforms mkdir ..\Output\%CONFIG_NAME%\bin\platforms
if not exist ..\Output\%CONFIG_NAME%\bin\HTML mkdir ..\Output\%CONFIG_NAME%\bin\HTML
if not exist ..\Output\%CONFIG_NAME%\bin\jqPlot mkdir ..\Output\%CONFIG_NAME%\bin\jqPlot
if not exist ..\Output\%CONFIG_NAME%\bin\Images mkdir ..\Output\%CONFIG_NAME%\bin\Images

rem Copy welcome page resources
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\welcome.css" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\low_resolution.css" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\Welcome.html" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\WelcomeAnalyzeNA.html" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\welcomepage_debug.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\welcomepage_debug_large.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\welcomepage_debug_selected.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\welcomepage_profile.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\welcomepage_profile_large.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\welcomepage_profile_selected.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\welcomepage_frame_analyze.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\welcomepage_frame_analyze_large.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\welcomepage_frame_analyze_selected.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\welcomepage_analyze.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\welcomepage_analyze_large.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\welcomepage_analyze_selected.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\analyze_add.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\analyze_new.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\frame_analyze_new.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\arrow.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\debug_new.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\empty.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\profile_attach.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\profile_new.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\profile_system.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\recent_projects.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\samples.png" "..\Output\%CONFIG_NAME%\bin\HTML\"
XCopy /r /d /y "..\AMDTApplicationFramework\Include\res\welcome\StartupPage_CodeXLLogo.png" "..\Output\%CONFIG_NAME%\bin\HTML\"

rem Copy Legal Files:
XCopy /r /d /y "..\Setup\Legal\Boost_Software_License.txt" "..\Output\%CONFIG_NAME%\bin\Legal\"
XCopy /r /d /y "..\Setup\Legal\GNU_LESSER_GENERAL_PUBLIC_LICENSE2_1.pdf" "..\Output\%CONFIG_NAME%\bin\Legal\"
XCopy /r /d /y "..\Setup\Legal\jqPlot.txt" "..\Output\%CONFIG_NAME%\bin\Legal\"
XCopy /r /d /y "..\Setup\Legal\LibDwarf.txt" "..\Output\%CONFIG_NAME%\bin\Legal\"
XCopy /r /d /y "..\Setup\Legal\QScintilla_COMMERCIAL_LICENSE_AGREEMENT.txt" "..\Output\%CONFIG_NAME%\bin\Legal\"
XCopy /r /d /y "..\Setup\Legal\zlibdoc.txt" "..\Output\%CONFIG_NAME%\bin\Legal\"

rem Copy Setup Files:
XCopy /r /d /y "..\Setup\Legal\Public\CodeXLEndUserLicenseAgreement-Win.rtf" "..\Output\%CONFIG_NAME%\bin\Legal\"
XCopy /r /d /y "..\Data\Public\VersionSettings.xml" "..\Output\%CONFIG_NAME%\bin\Data\"
XCopy /r /d /y "..\Setup\CodeXL_Release_Notes.pdf" "..\Output\%CONFIG_NAME%\bin\"
XCopy /r /d /y "..\Setup\Legal\Readme.txt" "..\Output\%CONFIG_NAME%\bin\"

rem Copy Debugger backend files:
XCopy /r /d /y "..\..\Common\Lib\AMD\OpenCLDebugAPI\1.3\lib\x64\AMDOpenCLDebug-x64%HYPHEN_D_SUFFIX%.dll" "..\Output\%CONFIG_NAME%\bin\"
XCopy /r /d /y "..\..\Common\Lib\AMD\OpenCLDebugAPI\1.3\lib\x64\amdopencldebug-x64%HYPHEN_D_SUFFIX%.pdb" "..\Output\%CONFIG_NAME%\bin\"
XCopy /r /d /y "..\..\Common\Lib\AMD\OpenCLDebugAPI\1.3\lib\x86\AMDOpenCLDebug%HYPHEN_D_SUFFIX%.dll" "..\Output\%CONFIG_NAME%\bin\"
XCopy /r /d /y "..\..\Common\Lib\AMD\OpenCLDebugAPI\1.3\lib\x86\amdopencldebug%HYPHEN_D_SUFFIX%.pdb" "..\Output\%CONFIG_NAME%\bin\"

rem Copy DbgHelp.dll
XCopy /r /d /y "..\..\Common\Lib\Ext\MicrooftDebuggingToolsForWindows\6.12.2.633\bin\dbghelp.dll" "..\Output\%CONFIG_NAME%\bin\"

rem Copy Hardware Debugger .dll files

XCopy /r /d /y "..\..\Common\Lib\AMD\HWDebugger\HwDbg\1.2\Lib\x64\AMDGPUDebugHSA-x64%HYPHEN_D_SUFFIX%.dll" "..\Output\%CONFIG_NAME%\bin\"
XCopy /r /d /y "..\..\Common\Lib\AMD\HWDebugger\HwDbg\1.2\Lib\x64\AMDGPUDebugHSA-x64%HYPHEN_D_SUFFIX%.pdb" "..\Output\%CONFIG_NAME%\bin\"
XCopy /r /d /y "..\..\Common\Lib\AMD\HWDebugger\HwDbgFacilities\1.0\Lib\x86\AMDHwDbgFacilities%HYPHEN_D_SUFFIX%.dll" "..\Output\%CONFIG_NAME%\bin\"
XCopy /r /d /y "..\..\Common\Lib\AMD\HWDebugger\HwDbgFacilities\1.0\Lib\x86\AMDHwDbgFacilities%HYPHEN_D_SUFFIX%.pdb" "..\Output\%CONFIG_NAME%\bin\"
XCopy /r /d /y "..\..\Common\Lib\AMD\HWDebugger\HwDbgFacilities\1.0\Lib\x64\AMDHwDbgFacilities-x64%HYPHEN_D_SUFFIX%.dll" "..\Output\%CONFIG_NAME%\bin\"
XCopy /r /d /y "..\..\Common\Lib\AMD\HWDebugger\HwDbgFacilities\1.0\Lib\x64\AMDHwDbgFacilities-x64%HYPHEN_D_SUFFIX%.pdb" "..\Output\%CONFIG_NAME%\bin\"

rem Copy CodeXL Images:
XCopy /r /d /y "..\Images\CodeXLAboutLogo.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\CodeXLDialogSmallLogo.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\CodeXLSplashScreen.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\StartupPage_CodeXLLogo.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\StartupPage_Documentation.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\StartupPage_Recent.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\DefaultFontTexture.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\GRSourceCodeIcon.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\InformationIcon.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\InformationIconSmall.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\LightBulbIconSmall.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\ShadingProgramIcon.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\WarningIconOrange.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\WarningIconOrangeSmall.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\WarningIconRed.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\WarningIconRedSmall.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\WarningIconYellow.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\WarningIconYellowSmall.png" "..\Output\%CONFIG_NAME%\bin\Images\"
XCopy /r /d /y "..\Images\CheckForUpdates.png" "..\Output\%CONFIG_NAME%\bin\Images\"

rem Copying Teapot Sample Files:
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeaPot.exe" "%Public%\Documents\CodeXL\Examples\Teapot\Release\"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeaPot.pdb" "%Public%\Documents\CodeXL\Examples\Teapot\Release\"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTSamples.props" "%Public%\Documents\CodeXL\Examples\Teapot"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeaPot.exe.manifest" "%Public%\Documents\CodeXL\Examples\Teapot"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeaPot*.sln" "%Public%\Documents\CodeXL\Examples\Teapot"
XCopy /r /d /y /i /s /h "..\Examples\AMDTTeaPot\*.suo" "%Public%\Documents\CodeXL\Examples\Teapot"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeapotLicense.txt" "%Public%\Documents\CodeXL\Examples\Teapot"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeapot\AMDTTeaPot*.*" "%Public%\Documents\CodeXL\Examples\Teapot\AMDTTeapot\"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeapot\resource.h" "%Public%\Documents\CodeXL\Examples\Teapot\AMDTTeapot\"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeapot\targetver.h" "%Public%\Documents\CodeXL\Examples\Teapot\AMDTTeapot\"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeapot\inc\*.*" "%Public%\Documents\CodeXL\Examples\Teapot\AMDTTeapot\inc\"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeapot\res\*.*" "%Public%\Documents\CodeXL\Examples\Teapot\AMDTTeapot\res\"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeapot\src\*.*" "%Public%\Documents\CodeXL\Examples\Teapot\AMDTTeapot\src\"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeapotLib\AMDTTeaPotLib*.*" "%Public%\Documents\CodeXL\Examples\Teapot\AMDTTeapotLib\"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeapotLib\inc\*.*" "%Public%\Documents\CodeXL\Examples\Teapot\AMDTTeapotLib\inc\"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeapotLib\inc\CL\*.*" "%Public%\Documents\CodeXL\Examples\Teapot\AMDTTeapotLib\inc\CL\"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeapotLib\inc\GL\*.*" "%Public%\Documents\CodeXL\Examples\Teapot\AMDTTeapotLib\inc\GL\"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeapotLib\res\*.*" "%Public%\Documents\CodeXL\Examples\Teapot\AMDTTeapotLib\res\"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeapotLib\src\*.*" "%Public%\Documents\CodeXL\Examples\Teapot\AMDTTeapotLib\src\"
XCopy /r /d /y /i "..\Examples\AMDTTeaPot\AMDTTeaPotLib\res\*.*" "%Public%\Documents\CodeXL\Examples\Teapot\res\"

rem Copying ClassicMatMul Sample Files:
XCopy /r /d /y /i "..\Examples\AMDTClassicMatMul\*" "%Public%\Documents\CodeXL\Examples\ClassicMatMul\"
XCopy /r /d /y /i /s /h "..\Examples\AMDTClassicMatMul\.vs\*" "%Public%\Documents\CodeXL\Examples\ClassicMatMul\.vs\"
XCopy /r /d /y /i "..\Examples\AMDTClassicMatMul\Release\AMDTClassicMatMul.exe" "%Public%\Documents\CodeXL\Examples\ClassicMatMul\Release\"
XCopy /r /d /y /i "..\Examples\AMDTClassicMatMul\Release\AMDTClassicMatMul.pdb" "%Public%\Documents\CodeXL\Examples\ClassicMatMul\Release\"

rem Copying D3D12Multithreading Sample Files
XCopy /r /d /y /i "..\Examples\D3D12Multithreading\*" "%Public%\Documents\CodeXL\Examples\D3D12Multithreading\"
XCopy /r /d /y /i "..\Examples\D3D12Multithreading\Release\*" "%Public%\Documents\CodeXL\Examples\D3D12Multithreading\Release\"
XCopy /r /d /y /i /s /h "..\Examples\D3D12Multithreading\.vs\*" "%Public%\Documents\CodeXL\Examples\D3D12Multithreading\.vs\"




rem Copying CodeXL Remote Agent files:
XCopy /r /d /y "..\Remote\AMDTRemoteAgent\CodeXLRemoteAgentConfig.xml" "..\Output\%CONFIG_NAME%\bin\"

rem Copy CodeXL Help files:
XCopy /r /d /y "..\Help\CodeXL_Quick_Start_Guide.pdf" "..\Output\%CONFIG_NAME%\bin\Help\"

rem Copy symsrv files:
XCopy /r /d /y "..\..\Common\Lib\Ext\MicrooftDebuggingToolsForWindows\6.12.2.633\x86\bin\symsrv.yes" "..\Output\%CONFIG_NAME%\bin\"
XCopy /r /d /y "..\..\Common\Lib\Ext\MicrooftDebuggingToolsForWindows\6.12.2.633\x86\bin\symsrv.dll" "..\Output\%CONFIG_NAME%\bin\"

rem Copy MS DIA files:
XCopy /r /d /y "%VS140COMNTOOLS%\..\IDE\msdia140.dll" "..\Output\%CONFIG_NAME%\bin\"

rem Copy Analyzer backend files:
XCopy /r /d /y "..\..\Common\Lib\Ext\Windows-Kits\10\bin\x86\d3dcompiler_47.dll" "..\Output\%CONFIG_NAME%\bin\x86"
XCopy /r /d /y "..\..\Common\Lib\Ext\Windows-Kits\10\bin\x64\d3dcompiler_47.dll" "..\Output\%CONFIG_NAME%\bin\x64"
XCopy /r /d /y "..\..\Common\Lib\AMD\Vulkan\rev_1_0_0\Release\win32\amdspv.exe" "..\Output\%CONFIG_NAME%\bin\x86"
XCopy /r /d /y "..\..\Common\Lib\AMD\Vulkan\rev_1_0_0\Release\win32\spvgen.dll" "..\Output\%CONFIG_NAME%\bin\x86"
XCopy /r /d /y "..\..\Common\Lib\AMD\Vulkan\rev_1_0_0\Release\win64\amdspv.exe" "..\Output\%CONFIG_NAME%\bin\x64"
XCopy /r /d /y "..\..\Common\Lib\AMD\Vulkan\rev_1_0_0\Release\win64\spvgen.dll" "..\Output\%CONFIG_NAME%\bin\x64"
XCopy /r /d /y "..\..\Common\Lib\AMD\OpenGL\VirtualContext\Release\win32\VirtualContext.exe" "..\Output\%CONFIG_NAME%\bin\x86"
XCopy /r /d /y "..\..\Common\Lib\AMD\OpenGL\VirtualContext\Release\win64\VirtualContext.exe" "..\Output\%CONFIG_NAME%\bin\x64"
XCopy /r /d /y "..\..\Common\Lib\AMD\ShaderAnalysis\Windows\x86\shae.exe" "..\Output\%CONFIG_NAME%\bin\x86"

rem Copy glew files:
XCopy /r /d /y "..\..\Common\Lib\Ext\glew\1.7.0\bin\x86\glew32.dll" "..\Output\%CONFIG_NAME%\bin\"

rem Copy CPU Profiler Backend profile files:
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\dcconfig.dtd" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\tbp.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x10\assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x10\branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x10\clu.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x10\data_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x10\ibs.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x10\inst_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x10\l2_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x11\assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x11\branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x11\data_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x11\inst_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x11\l2_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x12\assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x12\branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x12\clu.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x12\data_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x12\ibs.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x12\inst_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x12\l2_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x14\assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x14\branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x14\clu.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x14\data_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x14\ibs.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x14\inst_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x14\l2_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x0\assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x0\branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x0\clu.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x0\data_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x0\ibs.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x0\inst_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x0\l2_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x1\assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x1\branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x1\clu.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x1\data_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x1\ibs.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x1\inst_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x1\l2_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x3\assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x3\branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x3\clu.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x3\data_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x3\ibs.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x3\inst_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x3\l2_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x6\assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x6\branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x6\clu.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x6\data_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x6\ibs.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x6\inst_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x6\l2_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x7\assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x7\branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x7\clu.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x7\data_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x7\ibs.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x7\inst_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x15_0x7\l2_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x16_0x0\assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x16_0x0\branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x16_0x0\clu.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x16_0x0\data_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x16_0x0\ibs.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x16_0x0\inst_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x16_0x0\l2_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x16_0x3\assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x16_0x3\branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x16_0x3\clu.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x16_0x3\data_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x16_0x3\ibs.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x16_0x3\inst_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x16_0x3\l2_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x17_0x0\assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x17_0x0\branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x17_0x0\data_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x17_0x0\ibs.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0x17_0x0\inst_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0xf\assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0xf\branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0xf\data_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0xf\inst_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Profiles\0xf\l2_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Profiles\0xf\"

rem Copy CPU Profiler Backend events files:
XCopy /r /d /y "..\Components\CpuProfiling\Data\Events\Public\0x10.xml" "..\Output\%CONFIG_NAME%\bin\Data\Events\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Events\Public\0x11.xml" "..\Output\%CONFIG_NAME%\bin\Data\Events\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Events\Public\0x12.xml" "..\Output\%CONFIG_NAME%\bin\Data\Events\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Events\Public\0x14.xml" "..\Output\%CONFIG_NAME%\bin\Data\Events\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Events\Public\0x15_0x0.xml" "..\Output\%CONFIG_NAME%\bin\Data\Events\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Events\Public\0x15_0x1.xml" "..\Output\%CONFIG_NAME%\bin\Data\Events\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Events\Public\0x15_0x3.xml" "..\Output\%CONFIG_NAME%\bin\Data\Events\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Events\Public\0x15_0x6.xml" "..\Output\%CONFIG_NAME%\bin\Data\Events\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Events\Public\0x15_0x7.xml" "..\Output\%CONFIG_NAME%\bin\Data\Events\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Events\Public\0x16_0x0.xml" "..\Output\%CONFIG_NAME%\bin\Data\Events\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Events\Public\0x16_0x3.xml" "..\Output\%CONFIG_NAME%\bin\Data\Events\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Events\Public\0x17_0x0.xml" "..\Output\%CONFIG_NAME%\bin\Data\Events\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Events\Public\0xf.xml" "..\Output\%CONFIG_NAME%\bin\Data\Events\"

rem Copy CPU Profiler Backend views files:
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\README_viewconfig.txt" "..\Output\%CONFIG_NAME%\bin\Data\Views\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\timer.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\viewconfig.dtd" "..\Output\%CONFIG_NAME%\bin\Data\Views\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\br_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\dc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\dc_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\dtlb_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\dtlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_fetch_ic.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_fetch_itlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_fetch_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_fetch_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_op_branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_op_ls.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_op_ls_dc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_op_ls_dtlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_op_ls_expert.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_op_ls_memacc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_op_ls_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_op_nb_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_op_nb_cache.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_op_nb_service.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_op_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ibs_op_return.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ic_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\ipc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\itlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\l2_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\misalign_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\return_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\taken_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x10\triage_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x10\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x11\br_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x11\dc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x11\dc_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x11\dtlb_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x11\dtlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x11\ic_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x11\ipc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x11\itlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x11\l2_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x11\misalign_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x11\return_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x11\taken_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x11\triage_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x11\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\br_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\dc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\dc_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\dtlb_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\dtlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_fetch_ic.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_fetch_itlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_fetch_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_fetch_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_op_branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_op_ls.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_op_ls_dc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_op_ls_dtlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_op_ls_expert.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_op_ls_memacc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_op_ls_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_op_nb_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_op_nb_cache.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_op_nb_service.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_op_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ibs_op_return.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ic_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\ipc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\itlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\l2_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\misalign_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\return_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\taken_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x12\triage_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x12\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\br_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\dc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\dc_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\dtlb_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\dtlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_fetch_ic.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_fetch_itlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_fetch_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_fetch_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_op_branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_op_ls.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_op_ls_dc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_op_ls_dtlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_op_ls_expert.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_op_ls_memacc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_op_ls_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_op_nb_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_op_nb_cache.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_op_nb_service.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_op_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ibs_op_return.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ic_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\ipc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\itlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\l2_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\misalign_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\return_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\taken_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x14\triage_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x14\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\br_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\dc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\dc_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\dtlb_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\dtlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_fetch_ic.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_fetch_itlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_fetch_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_fetch_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_op_branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_op_ls.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_op_ls_dc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_op_ls_dtlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_op_ls_expert.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_op_ls_memacc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_op_ls_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_op_nb_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_op_nb_cache.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_op_nb_service.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_op_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ibs_op_return.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ic_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\ipc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\itlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\l2_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\misalign_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\return_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\taken_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x0\triage_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\br_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\dc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\dc_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\dtlb_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\dtlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_fetch_ic.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_fetch_itlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_fetch_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_fetch_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_op_branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_op_ls.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_op_ls_dc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_op_ls_dtlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_op_ls_expert.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_op_ls_memacc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_op_ls_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_op_nb_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_op_nb_cache.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_op_nb_service.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_op_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ibs_op_return.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ic_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\ipc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\itlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\l2_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\misalign_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\return_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\taken_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x1\triage_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x1\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\br_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\dc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\dc_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\dtlb_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\dtlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_fetch_ic.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_fetch_itlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_fetch_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_fetch_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_op_branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_op_ls.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_op_ls_dc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_op_ls_dtlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_op_ls_expert.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_op_ls_memacc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_op_ls_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_op_nb_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_op_nb_cache.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_op_nb_service.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_op_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ibs_op_return.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ic_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\ipc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\itlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\l2_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\misalign_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\return_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\taken_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x3\triage_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\br_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\dc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\dc_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\dtlb_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\dtlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_fetch_ic.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_fetch_itlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_fetch_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_fetch_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_op_branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_op_ls.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_op_ls_dc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_op_ls_dtlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_op_ls_expert.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_op_ls_memacc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_op_ls_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_op_nb_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_op_nb_cache.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_op_nb_service.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_op_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ibs_op_return.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ic_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\ipc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\itlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\l2_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\misalign_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\return_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\taken_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x6\triage_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x6\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\br_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\dc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\dc_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\dtlb_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\dtlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_fetch_ic.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_fetch_itlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_fetch_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_fetch_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_op_branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_op_ls.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_op_ls_dc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_op_ls_dtlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_op_ls_expert.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_op_ls_memacc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_op_ls_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_op_nb_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_op_nb_cache.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_op_nb_service.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_op_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ibs_op_return.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ic_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\ipc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\itlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\l2_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\misalign_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\return_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\taken_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x15_0x7\triage_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x15_0x7\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\br_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\dc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\dc_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\dtlb_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\dtlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_fetch_ic.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_fetch_itlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_fetch_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_fetch_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_op_branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_op_ls.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_op_ls_dc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_op_ls_dtlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_op_ls_expert.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_op_ls_memacc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_op_ls_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_op_nb_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_op_nb_cache.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_op_nb_service.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_op_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ibs_op_return.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ic_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\ipc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\itlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\l2_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\misalign_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\return_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\taken_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x0\triage_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\br_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\dc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\dc_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\dtlb_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\dtlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_fetch_ic.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_fetch_itlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_fetch_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_fetch_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_op_branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_op_ls.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_op_ls_dc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_op_ls_dtlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_op_ls_expert.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_op_ls_memacc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_op_ls_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_op_nb_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_op_nb_cache.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_op_nb_service.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_op_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ibs_op_return.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ic_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\ipc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\itlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\l2_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\misalign_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\return_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\taken_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x16_0x3\triage_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x16_0x3\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\br_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\dc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\dc_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\dtlb_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\dtlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_fetch_ic.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_fetch_itlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_fetch_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_fetch_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_op_branch.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_op_ls.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_op_ls_dc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_op_ls_dtlb.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_op_ls_expert.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_op_ls_memacc.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_op_ls_page.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_op_nb_access.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_op_nb_cache.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_op_nb_service.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_op_overall.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ibs_op_return.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ic_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\ipc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\itlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\misalign_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\return_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\taken_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0x17_0x0\triage_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0x17_0x0\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0xf\br_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0xf\dc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0xf\dc_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0xf\dtlb_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0xf\dtlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0xf\ic_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0xf\ipc_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0xf\itlb_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0xf\l2_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0xf\misalign_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0xf\return_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0xf\taken_focus.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0xf\"
XCopy /r /d /y "..\Components\CpuProfiling\Data\Views\0xf\triage_assess.xml" "..\Output\%CONFIG_NAME%\bin\Data\Views\0xf\"

rem Copy GPU Profiler's jqPlot JavaScript files
XCopy /r /d /y  "..\Components\GpuProfiling\Backend\Common\jqPlot\*.*" "..\Output\%CONFIG_NAME%\bin\jqPlot\"

rem Copy Graphics Backend files
XCopy /r /d /y  "..\Components\Graphics\Server\media\ErrorImage.png" ..\Output\%CONFIG_NAME%\bin\Images
XCopy /r /d /y  "..\Components\Graphics\Server\media\EmptyImage.png" ..\Output\%CONFIG_NAME%\bin\Images

rem copy frame analysis config files
XCopy /r /d /y  "..\Data\CodeXLFrameAnalysisServer.cfg" "..\Output\%CONFIG_NAME%\bin"
XCopy /r /d /y  "..\Data\Public\FrameAnalysisDefaultCounterSets.cfg" "..\Output\%CONFIG_NAME%\bin\Data"

rem copy AGS file
XCopy /r /d /y "..\..\Common\Lib\AMD\ags\ags_lib_v4.0.0\lib\amd_ags_x86.dll" "..\Output\%CONFIG_NAME%\bin\"