//==============================================================================
// Copyright (c) 2015 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief  This file defines an enum for interceptable HSA APIs
//==============================================================================

#ifndef _HSA_FUNCTION_DEFS_H_
#define _HSA_FUNCTION_DEFS_H_

#include <AutoGenerated/HSARTModuleFuncTables.h>

/// enum containing an item for each interceptable HSA API
enum HSA_API_Type
{
    HSA_API_Type_UNKNOWN = -1,

#define X(SYM) HSA_API_Type_hsa_##SYM,
    HSA_RUNTIME_API_TABLE
    HSA_EXT_FINALIZE_API_TABLE
    HSA_EXT_IMAGE_API_TABLE
    //HSA_EXT_AMD_API_TABLE // pending discussion with RT team whether these should be added to interception table
#undef X

    // HSA tools library entrypoints
    HSA_API_Type_Init,
    HSA_API_Type_Unload,

    // Non-API items (used to mark dispatches in the ATP file)
    HSA_API_Type_Non_API_First,
    HSA_API_Type_Non_API_Dispatch = HSA_API_Type_Non_API_First,

    HSA_API_Type_COUNT
};

#endif // _HSA_FUNCTION_DEFS_H_
