# -*- Python -*-

Import('*')
from CXL_init import *

libName = "CXLCpuProfilingControl"

env = CXL_env.Clone()

env.Append( CPPPATH = [ 
	".",
	"inc",
	"..",
	env['CXL_commonproj_dir'],
	env['CXL_common_dir'] + '/../CodeXL/Components/CpuProfiling/Backend',
	env['CXL_common_dir'] + '/../CodeXL/Components/CpuProfiling',
])

UseQt4(env)

env.Append (LIBS = [
	"CXLBaseTools",
	"CXLOSWrappers",
	"CXLCpuCallstackSampling",
	"CXLCpuPerfEventUtils",
	"CXLCpuProfilingRawData",
	"CXLCpuProfilingTranslation",
])

sources = \
[
	"src/CpuProfileControl.cpp",
	"src/Linux/CaPerfConfig.cpp",
	"src/Linux/CaPerfEvent.cpp",
	"src/Linux/CaPerfProfiler.cpp",
	"src/Linux/CpuProfileControl_Lin.cpp",
	"src/Linux/PerfConfig.cpp",
	"src/Linux/PerfEvent.cpp",
	"src/Linux/PerfEventInternal.cpp",
	"src/Linux/PerfPmuSession.cpp",
	"src/Linux/PerfPmuTarget.cpp",
	"src/Linux/PerfProfiler.cpp",
]

# Creating object files	
objFiles = env.SharedObject(sources)

# Creating shared libraries
soFiles = env.SharedLibrary(
	target = libName, 
	source = objFiles)

# Installing libraries
libInstall = env.Install( 
	dir = env['CXL_lib_dir'], 
	source = (soFiles))

Return('libInstall')
