# -*- Python -*-

from CXL_init import *

Import('*')

libName = "CXLGraphicsServerInterface"

env = CXL_env.Clone()
env.Append( CPPPATH = [ 
	".",
	"..",
	env['CXL_commonproj_dir'],
])

sources = \
[
	"src/common/AMDTGraphicsServerInterface.cpp",
#	"src/common/AMDTGraphicsServerInterfaceDLL.cpp",
	"src/common/GraphicsServerInitFunc.cpp",
]

env.Append( LIBS=
[
	"CXLBaseTools",
	"CXLOSWrappers",
])

# Creating object files	
objFiles = env.SharedObject(sources)

# Creating shared libraries
soFiles = env.SharedLibrary(
	target = libName, 
	source = objFiles)

# Installing libraries
libInstall = env.Install( 
	dir = env['CXL_lib_dir'], 
	source = (soFiles))

Return('libInstall')
