// CodeXLVSPackage.idl : IDL source for CodeXLVSPackage.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (CodeXLVSPackage.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "msdbg.idl";
midl_pragma warning (disable : 2015)
import "vsshell.idl";
midl_pragma warning (default : 2015)

//standard dispids
#define DISPID_Name                     (-800)
#define DISPID_Delete                   (-801)
#define DISPID_Object                   (-802)
#define DISPID_Parent                   (-803)
#define DISPID_NewEnum					(-4)
#define DISPID_Value					(0)

[
	object,
	uuid(FFC8EA61-39F4-4481-BDDA-5C94DC1A5B12),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IvspPackageCommandHandler2 : IDispatch{
};
[
	uuid(04c0963f-51c7-495f-b1f2-720cd554f315),
	version(1.0),
	helpstring("CodeXLVSPackage 1.0 Type Library")
]
library CodeXLVSPackageLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");


	importlib("dte80a.olb");

	interface ISingleViewEditor;

	[
		object,
		uuid(4D44CB80-7E76-4408-BD9C-586FF54FF40F),
		oleautomation,
		nonextensible,
		helpstring("CodeXLVSPackage Single View Editor Interface"),
		pointer_default(unique)
	]
	interface ISingleViewEditor : IDispatch
	{
		[propget, id(1), helpstring("property DTE")] HRESULT DTE([out, retval] _DTE* *pVal);
		[propget, id(DISPID_Parent), helpstring("property Parent")] HRESULT Parent([out, retval] _DTE* *pVal);
		[propget, id(2), helpstring("property DefaultTabStop")] HRESULT DefaultTabStop([out, retval] float *pdVal);
		[propput, id(2), helpstring("property DefaultTabStop")] HRESULT DefaultTabStop([in] float dVal);
		[propget, id(3), helpstring("property Range")] HRESULT Range([out, retval] /*ITextRange*/ IDispatch** ppRange);
		[propget, id(4), helpstring("property Selection")] HRESULT Selection([out, retval] /*ITextSelection*/ IDispatch** ppSelection);
		[propget, id(5), helpstring("property Flags")] HRESULT Flags([out, retval] long *plFlags);
		[propput, id(5), helpstring("property Flags")] HRESULT Flags([in] long lFlags);
		[id(6), helpstring("method FindText")] HRESULT FindText([in] BSTR pStr);
		[id(7), helpstring("method SetText")] HRESULT SetText([in] BSTR pStr);
		[id(8), helpstring("method TypeText")] HRESULT TypeText([in] BSTR pStr);
		[id(9), helpstring("method Cut")] HRESULT Cut(void);
		[id(10), helpstring("method Copy")] HRESULT Copy(void);
		[id(11), helpstring("method Paste")] HRESULT Paste(void);
		[id(12), helpstring("method Delete")] HRESULT Delete([in] long lUnit, [in] long cUnit);
		[id(13), helpstring("method MoveUp")] HRESULT MoveUp([in] long lUnit, [in] long cUnit, [in] long lExtend);
		[id(14), helpstring("method MoveDown")] HRESULT MoveDown([in] long lUnit, [in] long cUnit, [in] long lExtend);
		[id(15), helpstring("method MoveLeft")] HRESULT MoveLeft([in] long lUnit, [in] long cUnit, [in] long lExtend);
		[id(16), helpstring("method MoveRight")] HRESULT MoveRight([in] long lUnit, [in] long cUnit, [in] long lExtend);
		[id(17), helpstring("method EndKey")] HRESULT EndKey([in] long lUnit, [in] long lExtend);
		[id(18), helpstring("method HomeKey")] HRESULT HomeKey([in] long lUnit, [in] long lExtend);
	};
	[
		uuid(ecdfbaee-ad99-452d-874c-99fce5a48b8e),
		helpstring("CodeXLVSPackage Package")
	]
	coclass CodeXLVSPackagePackage
	{
		[default] interface IVsPackage;
	};
	[
		uuid(A0B4A997-916E-4ED5-A703-1D06B6F1C831),
		helpstring("vspDebugEngine Class")
	]
	coclass vspDebugEngine
	{
		[default] interface IDebugEngine2;
	};
	[
		uuid(A2359309-4A8D-42A6-8D63-07EEEC35D443)
	]
	coclass vspPackageCommandHandler2
	{
		[default] interface IvspPackageCommandHandler2;
	};
};
