//==============================================================================
// Copyright (c) 2016 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief  This file defines the interceptor helpers for the 1.0 runtime
//==============================================================================

#include <cstdlib>
#include <cstring>

#include "AutoGenerated/HSAPMCInterception.h"
#include "HSAPMCInterceptionTable1_0.h"

/// Intercepts HSA APIs for this HSA Profiler agent
void InitHSAAPIInterceptPMC1_0(ApiTable1_0* pTable)
{
    g_pRealCoreFunctions = (CoreApiTable*)malloc(sizeof(CoreApiTable));
    g_pRealFinalizerExtFunctions = (FinalizerExtTable*)malloc(sizeof(FinalizerExtTable));
    g_pRealImageExtFunctions = (ImageExtTable*)malloc(sizeof(ImageExtTable));

    g_pRealCoreFunctions->hsa_status_string_fn = pTable->hsa_status_string_fn;
    g_pRealCoreFunctions->hsa_init_fn = pTable->hsa_init_fn;
    g_pRealCoreFunctions->hsa_shut_down_fn = pTable->hsa_shut_down_fn;
    g_pRealCoreFunctions->hsa_system_get_info_fn = pTable->hsa_system_get_info_fn;
    g_pRealCoreFunctions->hsa_system_extension_supported_fn = pTable->hsa_system_extension_supported_fn;
    g_pRealCoreFunctions->hsa_system_get_extension_table_fn = pTable->hsa_system_get_extension_table_fn;
    g_pRealCoreFunctions->hsa_agent_get_info_fn = pTable->hsa_agent_get_info_fn;
    g_pRealCoreFunctions->hsa_iterate_agents_fn = pTable->hsa_iterate_agents_fn;
    g_pRealCoreFunctions->hsa_agent_get_exception_policies_fn = pTable->hsa_agent_get_exception_policies_fn;
    g_pRealCoreFunctions->hsa_agent_extension_supported_fn = pTable->hsa_agent_extension_supported_fn;
    g_pRealCoreFunctions->hsa_signal_create_fn = pTable->hsa_signal_create_fn;
    g_pRealCoreFunctions->hsa_signal_destroy_fn = pTable->hsa_signal_destroy_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_signal_load_scacquire_fn = pTable->hsa_signal_load_acquire_fn;
#else
    g_pRealCoreFunctions->hsa_signal_load_acquire_fn = pTable->hsa_signal_load_acquire_fn;
#endif
    g_pRealCoreFunctions->hsa_signal_load_relaxed_fn = pTable->hsa_signal_load_relaxed_fn;
    g_pRealCoreFunctions->hsa_signal_store_relaxed_fn = pTable->hsa_signal_store_relaxed_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_signal_store_screlease_fn = pTable->hsa_signal_store_release_fn;
    g_pRealCoreFunctions->hsa_signal_exchange_scacq_screl_fn = pTable->hsa_signal_exchange_acq_rel_fn;
    g_pRealCoreFunctions->hsa_signal_exchange_scacquire_fn = pTable->hsa_signal_exchange_acquire_fn;
#else
    g_pRealCoreFunctions->hsa_signal_store_release_fn = pTable->hsa_signal_store_release_fn;
    g_pRealCoreFunctions->hsa_signal_exchange_acq_rel_fn = pTable->hsa_signal_exchange_acq_rel_fn;
    g_pRealCoreFunctions->hsa_signal_exchange_acquire_fn = pTable->hsa_signal_exchange_acquire_fn;
#endif
    g_pRealCoreFunctions->hsa_signal_exchange_relaxed_fn = pTable->hsa_signal_exchange_relaxed_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_signal_exchange_screlease_fn = pTable->hsa_signal_exchange_release_fn;
    g_pRealCoreFunctions->hsa_signal_cas_scacq_screl_fn = pTable->hsa_signal_cas_acq_rel_fn;
    g_pRealCoreFunctions->hsa_signal_cas_scacquire_fn = pTable->hsa_signal_cas_acquire_fn;
#else
    g_pRealCoreFunctions->hsa_signal_exchange_release_fn = pTable->hsa_signal_exchange_release_fn;
    g_pRealCoreFunctions->hsa_signal_cas_acq_rel_fn = pTable->hsa_signal_cas_acq_rel_fn;
    g_pRealCoreFunctions->hsa_signal_cas_acquire_fn = pTable->hsa_signal_cas_acquire_fn;
#endif
    g_pRealCoreFunctions->hsa_signal_cas_relaxed_fn = pTable->hsa_signal_cas_relaxed_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_signal_cas_screlease_fn = pTable->hsa_signal_cas_release_fn;
    g_pRealCoreFunctions->hsa_signal_add_scacq_screl_fn = pTable->hsa_signal_add_acq_rel_fn;
    g_pRealCoreFunctions->hsa_signal_add_scacquire_fn = pTable->hsa_signal_add_acquire_fn;
#else
    g_pRealCoreFunctions->hsa_signal_cas_release_fn = pTable->hsa_signal_cas_release_fn;
    g_pRealCoreFunctions->hsa_signal_add_acq_rel_fn = pTable->hsa_signal_add_acq_rel_fn;
    g_pRealCoreFunctions->hsa_signal_add_acquire_fn = pTable->hsa_signal_add_acquire_fn;
#endif
    g_pRealCoreFunctions->hsa_signal_add_relaxed_fn = pTable->hsa_signal_add_relaxed_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_signal_add_screlease_fn = pTable->hsa_signal_add_release_fn;
    g_pRealCoreFunctions->hsa_signal_subtract_scacq_screl_fn = pTable->hsa_signal_subtract_acq_rel_fn;
    g_pRealCoreFunctions->hsa_signal_subtract_scacquire_fn = pTable->hsa_signal_subtract_acquire_fn;
#else
    g_pRealCoreFunctions->hsa_signal_add_release_fn = pTable->hsa_signal_add_release_fn;
    g_pRealCoreFunctions->hsa_signal_subtract_acq_rel_fn = pTable->hsa_signal_subtract_acq_rel_fn;
    g_pRealCoreFunctions->hsa_signal_subtract_acquire_fn = pTable->hsa_signal_subtract_acquire_fn;
#endif
    g_pRealCoreFunctions->hsa_signal_subtract_relaxed_fn = pTable->hsa_signal_subtract_relaxed_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_signal_subtract_screlease_fn = pTable->hsa_signal_subtract_release_fn;
    g_pRealCoreFunctions->hsa_signal_and_scacq_screl_fn = pTable->hsa_signal_and_acq_rel_fn;
    g_pRealCoreFunctions->hsa_signal_and_scacquire_fn = pTable->hsa_signal_and_acquire_fn;
#else
    g_pRealCoreFunctions->hsa_signal_subtract_release_fn = pTable->hsa_signal_subtract_release_fn;
    g_pRealCoreFunctions->hsa_signal_and_acq_rel_fn = pTable->hsa_signal_and_acq_rel_fn;
    g_pRealCoreFunctions->hsa_signal_and_acquire_fn = pTable->hsa_signal_and_acquire_fn;
#endif
    g_pRealCoreFunctions->hsa_signal_and_relaxed_fn = pTable->hsa_signal_and_relaxed_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_signal_and_screlease_fn = pTable->hsa_signal_and_release_fn;
    g_pRealCoreFunctions->hsa_signal_or_scacq_screl_fn = pTable->hsa_signal_or_acq_rel_fn;
    g_pRealCoreFunctions->hsa_signal_or_scacquire_fn = pTable->hsa_signal_or_acquire_fn;
#else
    g_pRealCoreFunctions->hsa_signal_and_release_fn = pTable->hsa_signal_and_release_fn;
    g_pRealCoreFunctions->hsa_signal_or_acq_rel_fn = pTable->hsa_signal_or_acq_rel_fn;
    g_pRealCoreFunctions->hsa_signal_or_acquire_fn = pTable->hsa_signal_or_acquire_fn;
#endif
    g_pRealCoreFunctions->hsa_signal_or_relaxed_fn = pTable->hsa_signal_or_relaxed_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_signal_or_screlease_fn = pTable->hsa_signal_or_release_fn;
    g_pRealCoreFunctions->hsa_signal_xor_scacq_screl_fn = pTable->hsa_signal_xor_acq_rel_fn;
    g_pRealCoreFunctions->hsa_signal_xor_scacquire_fn = pTable->hsa_signal_xor_acquire_fn;
#else
    g_pRealCoreFunctions->hsa_signal_or_release_fn = pTable->hsa_signal_or_release_fn;
    g_pRealCoreFunctions->hsa_signal_xor_acq_rel_fn = pTable->hsa_signal_xor_acq_rel_fn;
    g_pRealCoreFunctions->hsa_signal_xor_acquire_fn = pTable->hsa_signal_xor_acquire_fn;
#endif
    g_pRealCoreFunctions->hsa_signal_xor_relaxed_fn = pTable->hsa_signal_xor_relaxed_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_signal_xor_screlease_fn = pTable->hsa_signal_xor_release_fn;
    g_pRealCoreFunctions->hsa_signal_wait_scacquire_fn = pTable->hsa_signal_wait_acquire_fn;
#else
    g_pRealCoreFunctions->hsa_signal_xor_release_fn = pTable->hsa_signal_xor_release_fn;
    g_pRealCoreFunctions->hsa_signal_wait_acquire_fn = pTable->hsa_signal_wait_acquire_fn;
#endif
    g_pRealCoreFunctions->hsa_signal_wait_relaxed_fn = pTable->hsa_signal_wait_relaxed_fn;
    g_pRealCoreFunctions->hsa_queue_create_fn = pTable->hsa_queue_create_fn;
    g_pRealCoreFunctions->hsa_soft_queue_create_fn = pTable->hsa_soft_queue_create_fn;
    g_pRealCoreFunctions->hsa_queue_destroy_fn = pTable->hsa_queue_destroy_fn;
    g_pRealCoreFunctions->hsa_queue_inactivate_fn = pTable->hsa_queue_inactivate_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_queue_load_read_index_scacquire_fn = pTable->hsa_queue_load_read_index_acquire_fn;
#else
    g_pRealCoreFunctions->hsa_queue_load_read_index_acquire_fn = pTable->hsa_queue_load_read_index_acquire_fn;
#endif
    g_pRealCoreFunctions->hsa_queue_load_read_index_relaxed_fn = pTable->hsa_queue_load_read_index_relaxed_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_queue_load_write_index_scacquire_fn = pTable->hsa_queue_load_write_index_acquire_fn;
#else
    g_pRealCoreFunctions->hsa_queue_load_write_index_acquire_fn = pTable->hsa_queue_load_write_index_acquire_fn;
#endif
    g_pRealCoreFunctions->hsa_queue_load_write_index_relaxed_fn = pTable->hsa_queue_load_write_index_relaxed_fn;
    g_pRealCoreFunctions->hsa_queue_store_write_index_relaxed_fn = pTable->hsa_queue_store_write_index_relaxed_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_queue_store_write_index_screlease_fn = pTable->hsa_queue_store_write_index_release_fn;
    g_pRealCoreFunctions->hsa_queue_cas_write_index_scacq_screl_fn = pTable->hsa_queue_cas_write_index_acq_rel_fn;
    g_pRealCoreFunctions->hsa_queue_cas_write_index_scacquire_fn = pTable->hsa_queue_cas_write_index_acquire_fn;
#else
    g_pRealCoreFunctions->hsa_queue_store_write_index_release_fn = pTable->hsa_queue_store_write_index_release_fn;
    g_pRealCoreFunctions->hsa_queue_cas_write_index_acq_rel_fn = pTable->hsa_queue_cas_write_index_acq_rel_fn;
    g_pRealCoreFunctions->hsa_queue_cas_write_index_acquire_fn = pTable->hsa_queue_cas_write_index_acquire_fn;
#endif
    g_pRealCoreFunctions->hsa_queue_cas_write_index_relaxed_fn = pTable->hsa_queue_cas_write_index_relaxed_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_queue_cas_write_index_screlease_fn = pTable->hsa_queue_cas_write_index_release_fn;
    g_pRealCoreFunctions->hsa_queue_add_write_index_scacq_screl_fn = pTable->hsa_queue_add_write_index_acq_rel_fn;
    g_pRealCoreFunctions->hsa_queue_add_write_index_scacquire_fn = pTable->hsa_queue_add_write_index_acquire_fn;
#else
    g_pRealCoreFunctions->hsa_queue_cas_write_index_release_fn = pTable->hsa_queue_cas_write_index_release_fn;
    g_pRealCoreFunctions->hsa_queue_add_write_index_acq_rel_fn = pTable->hsa_queue_add_write_index_acq_rel_fn;
    g_pRealCoreFunctions->hsa_queue_add_write_index_acquire_fn = pTable->hsa_queue_add_write_index_acquire_fn;
#endif
    g_pRealCoreFunctions->hsa_queue_add_write_index_relaxed_fn = pTable->hsa_queue_add_write_index_relaxed_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_queue_add_write_index_screlease_fn = pTable->hsa_queue_add_write_index_release_fn;
#else
    g_pRealCoreFunctions->hsa_queue_add_write_index_release_fn = pTable->hsa_queue_add_write_index_release_fn;
#endif
    g_pRealCoreFunctions->hsa_queue_store_read_index_relaxed_fn = pTable->hsa_queue_store_read_index_relaxed_fn;
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions->hsa_queue_store_read_index_screlease_fn = pTable->hsa_queue_store_read_index_release_fn;
#else
    g_pRealCoreFunctions->hsa_queue_store_read_index_release_fn = pTable->hsa_queue_store_read_index_release_fn;
#endif
    g_pRealCoreFunctions->hsa_region_get_info_fn = pTable->hsa_region_get_info_fn;
    g_pRealCoreFunctions->hsa_agent_iterate_regions_fn = pTable->hsa_agent_iterate_regions_fn;
    g_pRealCoreFunctions->hsa_memory_allocate_fn = pTable->hsa_memory_allocate_fn;
    g_pRealCoreFunctions->hsa_memory_free_fn = pTable->hsa_memory_free_fn;
    g_pRealCoreFunctions->hsa_memory_copy_fn = pTable->hsa_memory_copy_fn;
    g_pRealCoreFunctions->hsa_memory_assign_agent_fn = pTable->hsa_memory_assign_agent_fn;
    g_pRealCoreFunctions->hsa_memory_register_fn = pTable->hsa_memory_register_fn;
    g_pRealCoreFunctions->hsa_memory_deregister_fn = pTable->hsa_memory_deregister_fn;
    g_pRealCoreFunctions->hsa_isa_from_name_fn = pTable->hsa_isa_from_name_fn;
    g_pRealCoreFunctions->hsa_isa_get_info_fn = pTable->hsa_isa_get_info_fn;
    g_pRealCoreFunctions->hsa_isa_compatible_fn = pTable->hsa_isa_compatible_fn;
    g_pRealCoreFunctions->hsa_code_object_serialize_fn = pTable->hsa_code_object_serialize_fn;
    g_pRealCoreFunctions->hsa_code_object_deserialize_fn = pTable->hsa_code_object_deserialize_fn;
    g_pRealCoreFunctions->hsa_code_object_destroy_fn = pTable->hsa_code_object_destroy_fn;
    g_pRealCoreFunctions->hsa_code_object_get_info_fn = pTable->hsa_code_object_get_info_fn;
    g_pRealCoreFunctions->hsa_code_object_get_symbol_fn = pTable->hsa_code_object_get_symbol_fn;
    g_pRealCoreFunctions->hsa_code_symbol_get_info_fn = pTable->hsa_code_symbol_get_info_fn;
    g_pRealCoreFunctions->hsa_code_object_iterate_symbols_fn = pTable->hsa_code_object_iterate_symbols_fn;
    g_pRealCoreFunctions->hsa_executable_create_fn = pTable->hsa_executable_create_fn;
    g_pRealCoreFunctions->hsa_executable_destroy_fn = pTable->hsa_executable_destroy_fn;
    g_pRealCoreFunctions->hsa_executable_load_code_object_fn = pTable->hsa_executable_load_code_object_fn;
    g_pRealCoreFunctions->hsa_executable_freeze_fn = pTable->hsa_executable_freeze_fn;
    g_pRealCoreFunctions->hsa_executable_get_info_fn = pTable->hsa_executable_get_info_fn;
    g_pRealCoreFunctions->hsa_executable_global_variable_define_fn = pTable->hsa_executable_global_variable_define_fn;
    g_pRealCoreFunctions->hsa_executable_agent_global_variable_define_fn = pTable->hsa_executable_agent_global_variable_define_fn;
    g_pRealCoreFunctions->hsa_executable_readonly_variable_define_fn = pTable->hsa_executable_readonly_variable_define_fn;
    g_pRealCoreFunctions->hsa_executable_validate_fn = pTable->hsa_executable_validate_fn;
    g_pRealCoreFunctions->hsa_executable_get_symbol_fn = pTable->hsa_executable_get_symbol_fn;
    g_pRealCoreFunctions->hsa_executable_symbol_get_info_fn = pTable->hsa_executable_symbol_get_info_fn;
    g_pRealCoreFunctions->hsa_executable_iterate_symbols_fn = pTable->hsa_executable_iterate_symbols_fn;
    g_pRealFinalizerExtFunctions->hsa_ext_program_create_fn = pTable->std_exts_->hsa_ext_program_create_fn;
    g_pRealFinalizerExtFunctions->hsa_ext_program_destroy_fn = pTable->std_exts_->hsa_ext_program_destroy_fn;
    g_pRealFinalizerExtFunctions->hsa_ext_program_add_module_fn = pTable->std_exts_->hsa_ext_program_add_module_fn;
    g_pRealFinalizerExtFunctions->hsa_ext_program_iterate_modules_fn = pTable->std_exts_->hsa_ext_program_iterate_modules_fn;
    g_pRealFinalizerExtFunctions->hsa_ext_program_get_info_fn = pTable->std_exts_->hsa_ext_program_get_info_fn;
    g_pRealFinalizerExtFunctions->hsa_ext_program_finalize_fn = pTable->std_exts_->hsa_ext_program_finalize_fn;
    g_pRealImageExtFunctions->hsa_ext_image_get_capability_fn = pTable->std_exts_->hsa_ext_image_get_capability_fn;
    g_pRealImageExtFunctions->hsa_ext_image_data_get_info_fn = pTable->std_exts_->hsa_ext_image_data_get_info_fn;
    g_pRealImageExtFunctions->hsa_ext_image_create_fn = pTable->std_exts_->hsa_ext_image_create_fn;
    g_pRealImageExtFunctions->hsa_ext_image_destroy_fn = pTable->std_exts_->hsa_ext_image_destroy_fn;
    g_pRealImageExtFunctions->hsa_ext_image_copy_fn = pTable->std_exts_->hsa_ext_image_copy_fn;
    g_pRealImageExtFunctions->hsa_ext_image_import_fn = pTable->std_exts_->hsa_ext_image_import_fn;
    g_pRealImageExtFunctions->hsa_ext_image_export_fn = pTable->std_exts_->hsa_ext_image_export_fn;
    g_pRealImageExtFunctions->hsa_ext_image_clear_fn = pTable->std_exts_->hsa_ext_image_clear_fn;
    g_pRealImageExtFunctions->hsa_ext_sampler_create_fn = pTable->std_exts_->hsa_ext_sampler_create_fn;
    g_pRealImageExtFunctions->hsa_ext_sampler_destroy_fn = pTable->std_exts_->hsa_ext_sampler_destroy_fn;

    pTable->hsa_agent_get_info_fn = HSA_PMC_hsa_agent_get_info;
    pTable->hsa_queue_create_fn = HSA_PMC_hsa_queue_create;
    pTable->hsa_queue_destroy_fn = HSA_PMC_hsa_queue_destroy;
    pTable->hsa_executable_get_symbol_fn = HSA_PMC_hsa_executable_get_symbol;
    pTable->hsa_iterate_agents_fn = HSA_PMC_hsa_iterate_agents;
}
