//==============================================================================
// Copyright (c) 2016 Advanced Micro Devices, Inc. All rights reserved.
/// \author AMD Developer Tools Team
/// \file
/// \brief  This file defines the interceptor helpers for the 1.0 runtime
//==============================================================================

#include <cstdlib>
#include <cstring>

#include "AutoGenerated/HSAPMCInterception.h"
#include "HSAPMCInterceptionTable1_0.h"

/// Intercepts HSA APIs for this HSA Profiler agent
void InitHSAAPIInterceptPMC1_0(ApiTable1_0* pTable)
{
#ifdef FUTURE_ROCR_VERSION
    g_pRealCoreFunctions = (CoreApiTable*)malloc(sizeof(CoreApiTable));
#else
    g_pRealCoreFunctions = (ApiTable*)malloc(sizeof(ApiTable));
#endif

//TODO: assign all functions (even ext functions) in case profiler code ever calls them
    g_pRealCoreFunctions->hsa_agent_get_info_fn = pTable->hsa_agent_get_info_fn;
    g_pRealCoreFunctions->hsa_queue_create_fn = pTable->hsa_queue_create_fn;
    g_pRealCoreFunctions->hsa_queue_destroy_fn = pTable->hsa_queue_destroy_fn;
    g_pRealCoreFunctions->hsa_executable_get_symbol_fn = pTable->hsa_executable_get_symbol_fn;
    g_pRealCoreFunctions->hsa_executable_symbol_get_info_fn = pTable->hsa_executable_symbol_get_info_fn;
    g_pRealCoreFunctions->hsa_iterate_agents_fn = pTable->hsa_iterate_agents_fn;

    pTable->hsa_agent_get_info_fn = HSA_PMC_hsa_agent_get_info;
    pTable->hsa_queue_create_fn = HSA_PMC_hsa_queue_create;
    pTable->hsa_queue_destroy_fn = HSA_PMC_hsa_queue_destroy;
    pTable->hsa_executable_get_symbol_fn = HSA_PMC_hsa_executable_get_symbol;
}
