# -*- Python -*-

Import('*')
import subprocess
import os
import SCons.Script
import time
from CXL_init import *

cxl_env = CXL_env.Clone()

env = Environment() 

PwrProfInstaller    = "CodeXLPwrProfDriver.sh"
PwrProSourceInstall = "CodeXLPwrProfDriverSource.tar.gz"
PwrProfVersion      = "CodeXLPwrProfVersion"
baseDir     = Dir("#./Components/PowerProfiling/Backend/AMDTPowerProfilingDrivers/Linux/src").abspath

def run(cmd):
    res = subprocess.call(cmd, shell=True)
    if res != 0:
      print "Error: Failed in building Power Profile Drv: " + str(res)
      sys.exit(1)

def buildDrv(target, source, env):
    # do a clean 
    cmd = "make clean -C %s" %baseDir
    run(cmd)

    # do a make 
    cmd = "make -C %s" %baseDir
    print cmd
    run(cmd)

    # create CodeXLPwrProfDriverSource.tar.gz file
    # cmd = "%s/AMDTPwrProfCreateSrcPkg.sh" %scriptDir
    # run(cmd)

    return 0

def drvMessage(target = None, source = None, env = None):
    return "Building Power Profile driver from '%s'\n at: %s" % (source[0], 
      time.asctime(time.localtime(time.time())))

drvMake = env.Command(
    target      = 'PwrProfDriver', 
    source      = Dir("#./Components/PowerProfiling/Backend/AMDTPowerProfilingDrivers/Linux/src"),
    action      = Action(buildDrv, strfunction = drvMessage),
)

moduleSource = cxl_env.Install( 
	dir = cxl_env['CXL_lib_dir'], 
	source = PwrProSourceInstall)

moduleVersion = cxl_env.Install( 
	dir = cxl_env['CXL_lib_dir'], 
	source = PwrProfVersion)

moduleInstallScript = cxl_env.Install( 
	dir = cxl_env['CXL_lib_dir'], 
	source = PwrProfInstaller)

ResultsAction = drvMake + moduleSource + moduleVersion + moduleInstallScript

Return('ResultsAction')
