# Copyright (c) 2016 Advanced Micro Devices, Inc. All rights reserved.
#
# Main scons build file for Capture Player
#

from CXL_init import *

Import('*')
env = CXL_env.Clone()

appName="CXLGraphicsServerPlayer"

initGPSBackend (env)
UseTinyXml (env)
initVulkanSDK (env)

env.Append (CPPPATH =[
    env['CXL_commonproj_dir'],
    env['CXL_commonproj_dir'] + '/../../CodeXL/Components/Graphics/Server/Common',
    env['CXL_commonproj_dir'] + '/../../CodeXL/Components/Graphics/Server/Common/Linux',
    ])

GDT_DATADIR="-D'DATADIR=\"share\"'"
GDT_SYSCONFDIR="-D'SYSCONFDIR=\"etc\"'"
cpp_flags= ' ' + GDT_DATADIR + ' ' + GDT_SYSCONFDIR+ ' -Dvulkan_EXPORTS -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XLIB_KHR '
original_cpp_flag=env['CPPFLAGS']
original_cpp_flag = original_cpp_flag + cpp_flags
env.Replace(CPPFLAGS = original_cpp_flag) 

# These need to be in their dependency order. Most derived first
env['LIBS'] = \
[
    #internal libraries
    "libCXLGraphicsServerCommon",
    "libCXLOSWrappers",
    "libCXLBaseTools",
    "libvulkan",
    #enternal libraries
    "rt",
    "pthread",
    "dl",
    "X11",
    "xcb"
]

sources = [
    "PlayerMain.cpp",
    "XcbWindow.cpp",
    "VulkanPlayer.cpp",
    ]

exe = env.Program(
    target = appName,
    source = sources)

# Installing libraries
libInstall = env.Install(
    dir = env['CXL_lib_dir'],
    source = (exe))

Return('libInstall')
