//==================================================================================
// Copyright (c) 2016 , Advanced Micro Devices, Inc.  All rights reserved.
//
/// \author AMD Developer Tools Team
/// \file apDebuggedProcessOutputStringEvent.h
///
//==================================================================================

//------------------------------ apDebuggedProcessOutputStringEvent.h ------------------------------

#ifndef __APDEBUGGEDPROCESSOUTPUTSTRINGEVENT_H
#define __APDEBUGGEDPROCESSOUTPUTSTRINGEVENT_H

// Forward declarations:
template <class TransferableObjectType> class osTransferableObjectCreator;

// Infra:
#include <AMDTBaseTools/Include/gtString.h>

// Local:
#include <AMDTAPIClasses/Include/Events/apEvent.h>


// ----------------------------------------------------------------------------------
// Class Name:           AP_API apDebuggedProcessOutputStringEvent
// General Description:
//   Contains a string output, generated by the debugged process.
// Author:  AMD Developer Tools Team
// Creation Date:        15/8/2007
// ----------------------------------------------------------------------------------
class AP_API apDebuggedProcessOutputStringEvent : public apEvent
{
public:
    apDebuggedProcessOutputStringEvent(const gtString& outputString);

    // Overrides osTransferableObject:
    virtual osTransferableObjectType type() const;
    virtual bool writeSelfIntoChannel(osChannel& ipcChannel) const;
    virtual bool readSelfFromChannel(osChannel& ipcChannel);

    // Overrides apEvent:
    virtual EventType eventType() const;
    virtual apEvent* clone() const;

    // Self functions:
    const gtString& debuggedProcessOutputString() const { return _debuggedProcessOutputString; };

private:
    friend class osTransferableObjectCreator<apDebuggedProcessOutputStringEvent>;

    // Do not allow the use of the default constructor:
    apDebuggedProcessOutputStringEvent();

private:
    // The debugged process output string:
    gtString _debuggedProcessOutputString;
};


#endif //__APDEBUGGEDPROCESSOUTPUTSTRINGEVENT_H
