//==================================================================================
// Copyright (c) 2016 , Advanced Micro Devices, Inc.  All rights reserved.
//
/// \author AMD Developer Tools Team
/// \file apGDBErrorEvent.h
///
//==================================================================================

//------------------------------ apGDBErrorEvent.h ------------------------------

#ifndef __APGDBERROREVENT_H
#define __APGDBERROREVENT_H

// Forward declarations:
template <class TransferableObjectType> class osTransferableObjectCreator;

// Infra:
#include <AMDTBaseTools/Include/gtString.h>

// Local:
#include <AMDTAPIClasses/Include/Events/apEvent.h>


// ----------------------------------------------------------------------------------
// Class Name:           AP_API apGDBErrorEvent
// General Description:
//   Contains an error string, generated by GDB - the GNU Debugger.
// Author:  AMD Developer Tools Team
// Creation Date:        13/01/2009
// ----------------------------------------------------------------------------------
class AP_API apGDBErrorEvent : public apEvent
{
public:
    apGDBErrorEvent(const gtString& gdbErrorString);

    // Overrides osTransferableObject:
    virtual osTransferableObjectType type() const;
    virtual bool writeSelfIntoChannel(osChannel& ipcChannel) const;
    virtual bool readSelfFromChannel(osChannel& ipcChannel);

    // Overrides apEvent:
    virtual EventType eventType() const;
    virtual apEvent* clone() const;

    // Self functions:
    const gtString& gdbErrorString() const { return _gdbErrorString; };

private:
    friend class osTransferableObjectCreator<apGDBErrorEvent>;

    // Do not allow the use of the default constructor:
    apGDBErrorEvent();

private:
    // The outputted debug string:
    gtString _gdbErrorString;
};


#endif //__APGDBERROREVENT_H

