//==================================================================================
// Copyright (c) 2016 , Advanced Micro Devices, Inc.  All rights reserved.
//
/// \author AMD Developer Tools Team
/// \file apMonitoredFunctionId.h
///
//==================================================================================

//------------------------------ apMonitoredFunctionId.h ------------------------------

#ifndef __APMONITOREDFUNCTIONID
#define __APMONITOREDFUNCTIONID

// Infra:
#include <AMDTBaseTools/Include/AMDTDefinitions.h>

// An enumeration that lists all the monitored functions:
// The enum value is the function Id.

// !!! NOTICE !!!!
// We depend on the facts that:
// a. apLastOpenGLBaseFunctionIndex - Marks the last function that belongs to the Open GL base functions (functions to which a client program can link statically).
//                                    (This definition is platform dependent)
// b. apLastOpenGLExtensionFunctionIndex - Marks the last extension function.
// c. The core functions order is the same as in gsWrappersFunctionPointers.
//    (See gsExtensionsManager implementation for the reason for the above limitations).

enum apMonitoredFunctionId
{
    apFirstOpenGLFunction = 0,
#if AMDT_BUILD_TARGET == AMDT_WINDOWS_OS

    // WGL monitored functions:
    ap_wglChoosePixelFormat = apFirstOpenGLFunction,
    ap_wglCopyContext,
    ap_wglCreateContext,
    ap_wglCreateLayerContext,
    ap_wglDeleteContext,
    ap_wglDescribeLayerPlane,
    ap_wglDescribePixelFormat,
    ap_wglGetCurrentContext,
    ap_wglGetCurrentDC,
    ap_wglGetDefaultProcAddress,
    ap_wglGetLayerPaletteEntries,
    ap_wglGetPixelFormat,
    ap_wglGetProcAddress,
    ap_wglMakeCurrent,
    ap_wglRealizeLayerPalette,
    ap_wglSetLayerPaletteEntries,
    ap_wglSetPixelFormat,
    ap_wglShareLists,
    ap_wglSwapBuffers,
    ap_wglSwapLayerBuffers,
    ap_wglSwapMultipleBuffers,
    ap_wglUseFontBitmapsA,
    ap_wglUseFontBitmapsW,
    ap_wglUseFontOutlinesA,
    ap_wglUseFontOutlinesW,

#elif ((AMDT_BUILD_TARGET == AMDT_LINUX_OS) && (AMDT_LINUX_VARIANT == AMDT_GENERIC_LINUX_VARIANT))

    // GLX monitored functions:
    ap_glXChooseVisual = apFirstOpenGLFunction,
    ap_glXCreateContext,
    ap_glXDestroyContext,
    ap_glXMakeCurrent,
    ap_glXCopyContext,
    ap_glXSwapBuffers,
    ap_glXCreateGLXPixmap,
    ap_glXDestroyGLXPixmap,
    ap_glXQueryExtension,
    ap_glXQueryVersion,
    ap_glXIsDirect,
    ap_glXGetConfig,
    ap_glXGetCurrentContext,
    ap_glXGetCurrentDrawable,
    ap_glXWaitGL,
    ap_glXWaitX,
    ap_glXUseXFont,
    ap_glXQueryExtensionsString,
    ap_glXQueryServerString,
    ap_glXGetClientString,
    ap_glXGetCurrentDisplay,
    ap_glXChooseFBConfig,
    ap_glXGetFBConfigAttrib,
    ap_glXGetFBConfigs,
    ap_glXGetVisualFromFBConfig,
    ap_glXCreateWindow,
    ap_glXDestroyWindow,
    ap_glXCreatePixmap,
    ap_glXDestroyPixmap,
    ap_glXCreatePbuffer,
    ap_glXDestroyPbuffer,
    ap_glXQueryDrawable,
    ap_glXCreateNewContext,
    ap_glXMakeContextCurrent,
    ap_glXGetCurrentReadDrawable,
    ap_glXQueryContext,
    ap_glXSelectEvent,
    ap_glXGetSelectedEvent,
    ap_glXGetProcAddress,
    ap_glXGetProcAddressARB,

    // GLX_ARB_create_context
    ap_glXCreateContextAttribsARB,

    /*
    ap_glXGetContextIDEXT,
    ap_glXGetCurrentDrawableEXT,
    ap_glXImportContextEXT,
    ap_glXFreeContextEXT,
    ap_glXQueryContextInfoEXT,
    ap_glXGetProcAddressARB,
    */

#elif ((AMDT_BUILD_TARGET == AMDT_LINUX_OS) && (AMDT_LINUX_VARIANT == AMDT_MAC_OS_X_LINUX_VARIANT))

    // CGL monitored functions:
    ap_CGLChoosePixelFormat = apFirstOpenGLFunction,
    ap_CGLDestroyPixelFormat,
    ap_CGLDescribePixelFormat,
    ap_CGLCreateContext,
    ap_CGLCopyContext,
    ap_CGLDestroyContext,
    ap_CGLGetCurrentContext,
    ap_CGLSetCurrentContext,
    ap_CGLEnable,
    ap_CGLDisable,
    ap_CGLIsEnabled,
    ap_CGLSetParameter,
    ap_CGLGetParameter,
    ap_CGLLockContext,
    ap_CGLUnlockContext,
    ap_CGLSetOffScreen,
    ap_CGLGetOffScreen,
    ap_CGLSetFullScreen,
    ap_CGLClearDrawable,
    ap_CGLFlushDrawable,
    ap_CGLCreatePBuffer,
    ap_CGLDescribePBuffer,
    ap_CGLDestroyPBuffer,
    ap_CGLGetPBuffer,
    ap_CGLSetPBuffer,
    ap_CGLTexImagePBuffer,
    ap_CGLErrorString,
    ap_CGLSetOption,
    ap_CGLGetOption,
    ap_CGLGetVersion,
    ap_CGLDescribeRenderer,
    ap_CGLDestroyRendererInfo,
    ap_CGLQueryRendererInfo,
    ap_CGLSetVirtualScreen,
    ap_CGLGetVirtualScreen,

#endif // AMDT_BUILD_TARGET


    // OpenGL 1.0 and 1.1 monitored functions:
    ap_glAccum,
    ap_glAlphaFunc,
    ap_glAreTexturesResident,
    ap_glArrayElement,
    ap_glBegin,
    ap_glBindTexture,
    ap_glBitmap,
    ap_glBlendFunc,
    ap_glCallList,
    ap_glCallLists,
    ap_glClear,
    ap_glClearAccum,
    ap_glClearColor,
    ap_glClearDepth,
    ap_glClearIndex,
    ap_glClearStencil,
    ap_glClipPlane,
    ap_glColor3b,
    ap_glColor3bv,
    ap_glColor3d,
    ap_glColor3dv,
    ap_glColor3f,
    ap_glColor3fv,
    ap_glColor3i,
    ap_glColor3iv,
    ap_glColor3s,
    ap_glColor3sv,
    ap_glColor3ub,
    ap_glColor3ubv,
    ap_glColor3ui,
    ap_glColor3uiv,
    ap_glColor3us,
    ap_glColor3usv,
    ap_glColor4b,
    ap_glColor4bv,
    ap_glColor4d,
    ap_glColor4dv,
    ap_glColor4f,
    ap_glColor4fv,
    ap_glColor4i,
    ap_glColor4iv,
    ap_glColor4s,
    ap_glColor4sv,
    ap_glColor4ub,
    ap_glColor4ubv,
    ap_glColor4ui,
    ap_glColor4uiv,
    ap_glColor4us,
    ap_glColor4usv,
    ap_glColorMask,
    ap_glColorMaterial,
    ap_glColorPointer,
    ap_glCopyPixels,
    ap_glCopyTexImage1D,
    ap_glCopyTexImage2D,
    ap_glCopyTexSubImage1D,
    ap_glCopyTexSubImage2D,
    ap_glCullFace,
    ap_glDeleteLists,
    ap_glDeleteTextures,
    ap_glDepthFunc,
    ap_glDepthMask,
    ap_glDepthRange,
    ap_glDisable,
    ap_glDisableClientState,
    ap_glDrawArrays,
    ap_glDrawBuffer,
    ap_glDrawElements,
    ap_glDrawPixels,
    ap_glEdgeFlag,
    ap_glEdgeFlagPointer,
    ap_glEdgeFlagv,
    ap_glEnable,
    ap_glEnableClientState,
    ap_glEnd,
    ap_glEndList,
    ap_glEvalCoord1d,
    ap_glEvalCoord1dv,
    ap_glEvalCoord1f,
    ap_glEvalCoord1fv,
    ap_glEvalCoord2d,
    ap_glEvalCoord2dv,
    ap_glEvalCoord2f,
    ap_glEvalCoord2fv,
    ap_glEvalMesh1,
    ap_glEvalMesh2,
    ap_glEvalPoint1,
    ap_glEvalPoint2,
    ap_glFeedbackBuffer,
    ap_glFinish,
    ap_glFlush,
    ap_glFogf,
    ap_glFogfv,
    ap_glFogi,
    ap_glFogiv,
    ap_glFrontFace,
    ap_glFrustum,
    ap_glGenLists,
    ap_glGenTextures,
    ap_glGetBooleanv,
    ap_glGetClipPlane,
    ap_glGetDoublev,
    ap_glGetError,
    ap_glGetFloatv,
    ap_glGetIntegerv,
    ap_glGetLightfv,
    ap_glGetLightiv,
    ap_glGetMapdv,
    ap_glGetMapfv,
    ap_glGetMapiv,
    ap_glGetMaterialfv,
    ap_glGetMaterialiv,
    ap_glGetPixelMapfv,
    ap_glGetPixelMapuiv,
    ap_glGetPixelMapusv,
    ap_glGetPointerv,
    ap_glGetPolygonStipple,
    ap_glGetString,
    ap_glGetTexEnvfv,
    ap_glGetTexEnviv,
    ap_glGetTexGendv,
    ap_glGetTexGenfv,
    ap_glGetTexGeniv,
    ap_glGetTexImage,
    ap_glGetTexLevelParameterfv,
    ap_glGetTexLevelParameteriv,
    ap_glGetTexParameterfv,
    ap_glGetTexParameteriv,
    ap_glHint,
    ap_glIndexMask,
    ap_glIndexPointer,
    ap_glIndexd,
    ap_glIndexdv,
    ap_glIndexf,
    ap_glIndexfv,
    ap_glIndexi,
    ap_glIndexiv,
    ap_glIndexs,
    ap_glIndexsv,
    ap_glIndexub,
    ap_glIndexubv,
    ap_glInitNames,
    ap_glInterleavedArrays,
    ap_glIsEnabled,
    ap_glIsList,
    ap_glIsTexture,
    ap_glLightModelf,
    ap_glLightModelfv,
    ap_glLightModeli,
    ap_glLightModeliv,
    ap_glLightf,
    ap_glLightfv,
    ap_glLighti,
    ap_glLightiv,
    ap_glLineStipple,
    ap_glLineWidth,
    ap_glListBase,
    ap_glLoadIdentity,
    ap_glLoadMatrixd,
    ap_glLoadMatrixf,
    ap_glLoadName,
    ap_glLogicOp,
    ap_glMap1d,
    ap_glMap1f,
    ap_glMap2d,
    ap_glMap2f,
    ap_glMapGrid1d,
    ap_glMapGrid1f,
    ap_glMapGrid2d,
    ap_glMapGrid2f,
    ap_glMaterialf,
    ap_glMaterialfv,
    ap_glMateriali,
    ap_glMaterialiv,
    ap_glMatrixMode,
    ap_glMultMatrixd,
    ap_glMultMatrixf,
    ap_glNewList,
    ap_glNormal3b,
    ap_glNormal3bv,
    ap_glNormal3d,
    ap_glNormal3dv,
    ap_glNormal3f,
    ap_glNormal3fv,
    ap_glNormal3i,
    ap_glNormal3iv,
    ap_glNormal3s,
    ap_glNormal3sv,
    ap_glNormalPointer,
    ap_glOrtho,
    ap_glPassThrough,
    ap_glPixelMapfv,
    ap_glPixelMapuiv,
    ap_glPixelMapusv,
    ap_glPixelStoref,
    ap_glPixelStorei,
    ap_glPixelTransferf,
    ap_glPixelTransferi,
    ap_glPixelZoom,
    ap_glPointSize,
    ap_glPolygonMode,
    ap_glPolygonOffset,
    ap_glPolygonStipple,
    ap_glPopAttrib,
    ap_glPopClientAttrib,
    ap_glPopMatrix,
    ap_glPopName,
    ap_glPrioritizeTextures,
    ap_glPushAttrib,
    ap_glPushClientAttrib,
    ap_glPushMatrix,
    ap_glPushName,
    ap_glRasterPos2d,
    ap_glRasterPos2dv,
    ap_glRasterPos2f,
    ap_glRasterPos2fv,
    ap_glRasterPos2i,
    ap_glRasterPos2iv,
    ap_glRasterPos2s,
    ap_glRasterPos2sv,
    ap_glRasterPos3d,
    ap_glRasterPos3dv,
    ap_glRasterPos3f,
    ap_glRasterPos3fv,
    ap_glRasterPos3i,
    ap_glRasterPos3iv,
    ap_glRasterPos3s,
    ap_glRasterPos3sv,
    ap_glRasterPos4d,
    ap_glRasterPos4dv,
    ap_glRasterPos4f,
    ap_glRasterPos4fv,
    ap_glRasterPos4i,
    ap_glRasterPos4iv,
    ap_glRasterPos4s,
    ap_glRasterPos4sv,
    ap_glReadBuffer,
    ap_glReadPixels,
    ap_glRectd,
    ap_glRectdv,
    ap_glRectf,
    ap_glRectfv,
    ap_glRecti,
    ap_glRectiv,
    ap_glRects,
    ap_glRectsv,
    ap_glRenderMode,
    ap_glRotated,
    ap_glRotatef,
    ap_glScaled,
    ap_glScalef,
    ap_glScissor,
    ap_glSelectBuffer,
    ap_glShadeModel,
    ap_glStencilFunc,
    ap_glStencilMask,
    ap_glStencilOp,
    ap_glTexCoord1d,
    ap_glTexCoord1dv,
    ap_glTexCoord1f,
    ap_glTexCoord1fv,
    ap_glTexCoord1i,
    ap_glTexCoord1iv,
    ap_glTexCoord1s,
    ap_glTexCoord1sv,
    ap_glTexCoord2d,
    ap_glTexCoord2dv,
    ap_glTexCoord2f,
    ap_glTexCoord2fv,
    ap_glTexCoord2i,
    ap_glTexCoord2iv,
    ap_glTexCoord2s,
    ap_glTexCoord2sv,
    ap_glTexCoord3d,
    ap_glTexCoord3dv,
    ap_glTexCoord3f,
    ap_glTexCoord3fv,
    ap_glTexCoord3i,
    ap_glTexCoord3iv,
    ap_glTexCoord3s,
    ap_glTexCoord3sv,
    ap_glTexCoord4d,
    ap_glTexCoord4dv,
    ap_glTexCoord4f,
    ap_glTexCoord4fv,
    ap_glTexCoord4i,
    ap_glTexCoord4iv,
    ap_glTexCoord4s,
    ap_glTexCoord4sv,
    ap_glTexCoordPointer,
    ap_glTexEnvf,
    ap_glTexEnvfv,
    ap_glTexEnvi,
    ap_glTexEnviv,
    ap_glTexGend,
    ap_glTexGendv,
    ap_glTexGenf,
    ap_glTexGenfv,
    ap_glTexGeni,
    ap_glTexGeniv,
    ap_glTexImage1D,
    ap_glTexImage2D,
    ap_glTexParameterf,
    ap_glTexParameterfv,
    ap_glTexParameteri,
    ap_glTexParameteriv,
    ap_glTexSubImage1D,
    ap_glTexSubImage2D,
    ap_glTranslated,
    ap_glTranslatef,
    ap_glVertex2d,
    ap_glVertex2dv,
    ap_glVertex2f,
    ap_glVertex2fv,
    ap_glVertex2i,
    ap_glVertex2iv,
    ap_glVertex2s,
    ap_glVertex2sv,
    ap_glVertex3d,
    ap_glVertex3dv,
    ap_glVertex3f,
    ap_glVertex3fv,
    ap_glVertex3i,
    ap_glVertex3iv,
    ap_glVertex3s,
    ap_glVertex3sv,
    ap_glVertex4d,
    ap_glVertex4dv,
    ap_glVertex4f,
    ap_glVertex4fv,
    ap_glVertex4i,
    ap_glVertex4iv,
    ap_glVertex4s,
    ap_glVertex4sv,
    ap_glVertexPointer,
    ap_glViewport,

#if (AMDT_BUILD_TARGET == AMDT_WINDOWS_OS)
    // Windows last base function index:
    apLastOpenGLBaseFunction = ap_glViewport,
#endif

    // OpenGL 1.2
    ap_glTexImage3D,
    ap_glDrawRangeElements,
    ap_glColorTable,
    ap_glColorTableParameterfv,
    ap_glColorTableParameteriv,
    ap_glCopyColorTable,
    ap_glGetColorTable,
    ap_glGetColorTableParameterfv,
    ap_glGetColorTableParameteriv,
    ap_glTexSubImage3D,
    ap_glCopyTexSubImage3D,
    ap_glColorSubTable,
    ap_glCopyColorSubTable,
    ap_glConvolutionFilter1D,
    ap_glConvolutionFilter2D,
    ap_glConvolutionParameterf,
    ap_glConvolutionParameterfv,
    ap_glConvolutionParameteri,
    ap_glConvolutionParameteriv,
    ap_glCopyConvolutionFilter1D,
    ap_glCopyConvolutionFilter2D,
    ap_glGetConvolutionFilter,
    ap_glGetConvolutionParameterfv,
    ap_glGetConvolutionParameteriv,
    ap_glGetSeparableFilter,
    ap_glSeparableFilter2D,
    ap_glGetHistogram,
    ap_glGetHistogramParameterfv,
    ap_glGetHistogramParameteriv,
    ap_glGetMinmax,
    ap_glGetMinmaxParameterfv,
    ap_glGetMinmaxParameteriv,
    ap_glHistogram,
    ap_glMinmax,
    ap_glResetHistogram,
    ap_glResetMinmax,
    ap_glBlendColor,
    ap_glBlendEquation,

    // OpenGL 1.3
    ap_glActiveTexture,
    ap_glClientActiveTexture,
    ap_glMultiTexCoord1d,
    ap_glMultiTexCoord1dv,
    ap_glMultiTexCoord1f,
    ap_glMultiTexCoord1fv,
    ap_glMultiTexCoord1i,
    ap_glMultiTexCoord1iv,
    ap_glMultiTexCoord1s,
    ap_glMultiTexCoord1sv,
    ap_glMultiTexCoord2d,
    ap_glMultiTexCoord2dv,
    ap_glMultiTexCoord2f,
    ap_glMultiTexCoord2fv,
    ap_glMultiTexCoord2i,
    ap_glMultiTexCoord2iv,
    ap_glMultiTexCoord2s,
    ap_glMultiTexCoord2sv,
    ap_glMultiTexCoord3d,
    ap_glMultiTexCoord3dv,
    ap_glMultiTexCoord3f,
    ap_glMultiTexCoord3fv,
    ap_glMultiTexCoord3i,
    ap_glMultiTexCoord3iv,
    ap_glMultiTexCoord3s,
    ap_glMultiTexCoord3sv,
    ap_glMultiTexCoord4d,
    ap_glMultiTexCoord4dv,
    ap_glMultiTexCoord4f,
    ap_glMultiTexCoord4fv,
    ap_glMultiTexCoord4i,
    ap_glMultiTexCoord4iv,
    ap_glMultiTexCoord4s,
    ap_glMultiTexCoord4sv,
    ap_glCompressedTexImage3D,
    ap_glCompressedTexImage2D,
    ap_glCompressedTexImage1D,
    ap_glCompressedTexSubImage3D,
    ap_glCompressedTexSubImage2D,
    ap_glCompressedTexSubImage1D,
    ap_glGetCompressedTexImage,
    ap_glSampleCoverage,
    ap_glLoadTransposeMatrixf,
    ap_glLoadTransposeMatrixd,
    ap_glMultTransposeMatrixf,
    ap_glMultTransposeMatrixd,

#if ((AMDT_BUILD_TARGET == AMDT_LINUX_OS) && (AMDT_LINUX_VARIANT == AMDT_GENERIC_LINUX_VARIANT))
    // Linux last base function index:
    apLastOpenGLBaseFunction = ap_glMultTransposeMatrixd,
#endif

    // OpenGL 1.4
    ap_glBlendFuncSeparate,
    ap_glFogCoordf,
    ap_glFogCoordfv,
    ap_glFogCoordd,
    ap_glFogCoorddv,
    ap_glFogCoordPointer,
    ap_glMultiDrawArrays,
    ap_glMultiDrawElements,
    ap_glPointParameterf,
    ap_glPointParameterfv,
    ap_glPointParameteri,
    ap_glPointParameteriv,
    ap_glSecondaryColor3b,
    ap_glSecondaryColor3bv,
    ap_glSecondaryColor3d,
    ap_glSecondaryColor3dv,
    ap_glSecondaryColor3f,
    ap_glSecondaryColor3fv,
    ap_glSecondaryColor3i,
    ap_glSecondaryColor3iv,
    ap_glSecondaryColor3s,
    ap_glSecondaryColor3sv,
    ap_glSecondaryColor3ub,
    ap_glSecondaryColor3ubv,
    ap_glSecondaryColor3ui,
    ap_glSecondaryColor3uiv,
    ap_glSecondaryColor3us,
    ap_glSecondaryColor3usv,
    ap_glSecondaryColorPointer,
    ap_glWindowPos2d,
    ap_glWindowPos2dv,
    ap_glWindowPos2f,
    ap_glWindowPos2fv,
    ap_glWindowPos2i,
    ap_glWindowPos2iv,
    ap_glWindowPos2s,
    ap_glWindowPos2sv,
    ap_glWindowPos3d,
    ap_glWindowPos3dv,
    ap_glWindowPos3f,
    ap_glWindowPos3fv,
    ap_glWindowPos3i,
    ap_glWindowPos3iv,
    ap_glWindowPos3s,
    ap_glWindowPos3sv,

    // OpenGL 1.5
    ap_glGenQueries,
    ap_glDeleteQueries,
    ap_glIsQuery,
    ap_glBeginQuery,
    ap_glEndQuery,
    ap_glGetQueryiv,
    ap_glGetQueryObjectiv,
    ap_glGetQueryObjectuiv,
    ap_glBindBuffer,
    ap_glDeleteBuffers,
    ap_glGenBuffers,
    ap_glIsBuffer,
    ap_glBufferData,
    ap_glBufferSubData,
    ap_glGetBufferSubData,
    ap_glMapBuffer,
    ap_glUnmapBuffer,
    ap_glGetBufferParameteriv,
    ap_glGetBufferPointerv,

    // OpenGL 2.0
    ap_glBlendEquationSeparate,
    ap_glDrawBuffers,
    ap_glStencilOpSeparate,
    ap_glStencilFuncSeparate,
    ap_glStencilMaskSeparate,
    ap_glAttachShader,
    ap_glBindAttribLocation,
    ap_glCompileShader,
    ap_glCreateProgram,
    ap_glCreateShader,
    ap_glDeleteProgram,
    ap_glDeleteShader,
    ap_glDetachShader,
    ap_glDisableVertexAttribArray,
    ap_glEnableVertexAttribArray,
    ap_glGetActiveAttrib,
    ap_glGetActiveUniform,
    ap_glGetAttachedShaders,
    ap_glGetAttribLocation,
    ap_glGetProgramiv,
    ap_glGetProgramInfoLog,
    ap_glGetShaderiv,
    ap_glGetShaderInfoLog,
    ap_glGetShaderSource,
    ap_glGetUniformLocation,
    ap_glGetUniformfv,
    ap_glGetUniformiv,
    ap_glGetVertexAttribdv,
    ap_glGetVertexAttribfv,
    ap_glGetVertexAttribiv,
    ap_glGetVertexAttribPointerv,
    ap_glIsProgram,
    ap_glIsShader,
    ap_glLinkProgram,
    ap_glShaderSource,
    ap_glUseProgram,
    ap_glUniform1f,
    ap_glUniform2f,
    ap_glUniform3f,
    ap_glUniform4f,
    ap_glUniform1i,
    ap_glUniform2i,
    ap_glUniform3i,
    ap_glUniform4i,
    ap_glUniform1fv,
    ap_glUniform2fv,
    ap_glUniform3fv,
    ap_glUniform4fv,
    ap_glUniform1iv,
    ap_glUniform2iv,
    ap_glUniform3iv,
    ap_glUniform4iv,
    ap_glUniformMatrix2fv,
    ap_glUniformMatrix3fv,
    ap_glUniformMatrix4fv,
    ap_glValidateProgram,
    ap_glVertexAttrib1d,
    ap_glVertexAttrib1dv,
    ap_glVertexAttrib1f,
    ap_glVertexAttrib1fv,
    ap_glVertexAttrib1s,
    ap_glVertexAttrib1sv,
    ap_glVertexAttrib2d,
    ap_glVertexAttrib2dv,
    ap_glVertexAttrib2f,
    ap_glVertexAttrib2fv,
    ap_glVertexAttrib2s,
    ap_glVertexAttrib2sv,
    ap_glVertexAttrib3d,
    ap_glVertexAttrib3dv,
    ap_glVertexAttrib3f,
    ap_glVertexAttrib3fv,
    ap_glVertexAttrib3s,
    ap_glVertexAttrib3sv,
    ap_glVertexAttrib4Nbv,
    ap_glVertexAttrib4Niv,
    ap_glVertexAttrib4Nsv,
    ap_glVertexAttrib4Nub,
    ap_glVertexAttrib4Nubv,
    ap_glVertexAttrib4Nuiv,
    ap_glVertexAttrib4Nusv,
    ap_glVertexAttrib4bv,
    ap_glVertexAttrib4d,
    ap_glVertexAttrib4dv,
    ap_glVertexAttrib4f,
    ap_glVertexAttrib4fv,
    ap_glVertexAttrib4iv,
    ap_glVertexAttrib4s,
    ap_glVertexAttrib4sv,
    ap_glVertexAttrib4ubv,
    ap_glVertexAttrib4uiv,
    ap_glVertexAttrib4usv,
    ap_glVertexAttribPointer,

#if ((AMDT_BUILD_TARGET == AMDT_LINUX_OS) && (AMDT_LINUX_VARIANT == AMDT_MAC_OS_X_LINUX_VARIANT))
    // Mac last base function index:
    apLastOpenGLBaseFunction = ap_glVertexAttribPointer,
#endif

    // OpenGL 2.1 functions are currently not supported on any platform as base functions:
    // OpenGL 2.1
    ap_glUniformMatrix2x3fv,
    ap_glUniformMatrix3x2fv,
    ap_glUniformMatrix2x4fv,
    ap_glUniformMatrix4x2fv,
    ap_glUniformMatrix3x4fv,
    ap_glUniformMatrix4x3fv,

    // OpenGL3.0
    ap_glColorMaski,
    ap_glGetBooleani_v,
    ap_glGetIntegeri_v,
    ap_glEnablei,
    ap_glDisablei,
    ap_glIsEnabledi,
    ap_glBeginTransformFeedback,
    ap_glEndTransformFeedback,
    ap_glBindBufferRange,
    ap_glBindBufferBase,
    ap_glTransformFeedbackVaryings,
    ap_glGetTransformFeedbackVarying,
    ap_glClampColor,
    ap_glBeginConditionalRender,
    ap_glEndConditionalRender,
    ap_glVertexAttribI1i,
    ap_glVertexAttribI2i,
    ap_glVertexAttribI3i,
    ap_glVertexAttribI4i,
    ap_glVertexAttribI1ui,
    ap_glVertexAttribI2ui,
    ap_glVertexAttribI3ui,
    ap_glVertexAttribI4ui,
    ap_glVertexAttribI1iv,
    ap_glVertexAttribI2iv,
    ap_glVertexAttribI3iv,
    ap_glVertexAttribI4iv,
    ap_glVertexAttribI1uiv,
    ap_glVertexAttribI2uiv,
    ap_glVertexAttribI3uiv,
    ap_glVertexAttribI4uiv,
    ap_glVertexAttribI4bv,
    ap_glVertexAttribI4sv,
    ap_glVertexAttribI4ubv,
    ap_glVertexAttribI4usv,
    ap_glVertexAttribIPointer,
    ap_glGetVertexAttribIiv,
    ap_glGetVertexAttribIuiv,
    ap_glGetUniformuiv,
    ap_glBindFragDataLocation,
    ap_glGetFragDataLocation,
    ap_glUniform1ui,
    ap_glUniform2ui,
    ap_glUniform3ui,
    ap_glUniform4ui,
    ap_glUniform1uiv,
    ap_glUniform2uiv,
    ap_glUniform3uiv,
    ap_glUniform4uiv,
    ap_glTexParameterIiv,
    ap_glTexParameterIuiv,
    ap_glGetTexParameterIiv,
    ap_glGetTexParameterIuiv,
    ap_glClearBufferiv,
    ap_glClearBufferuiv,
    ap_glClearBufferfv,
    ap_glClearBufferfi,
    ap_glGetStringi,

    // OpenGL 3.1
    ap_glDrawArraysInstanced,
    ap_glDrawElementsInstanced,
    ap_glTexBuffer,
    ap_glPrimitiveRestartIndex,

    // OpenGL 3.2
    ap_glGetInteger64i_v,
    ap_glGetBufferParameteri64v,
    ap_glFramebufferTexture,
    ap_glFramebufferTextureFace,

    // OpenGL 3.3
    ap_glBindFragDataLocationIndexed,
    ap_glGetFragDataIndex,
    ap_glGenSamplers,
    ap_glDeleteSamplers,
    ap_glIsSampler,
    ap_glBindSampler,
    ap_glSamplerParameteri,
    ap_glSamplerParameteriv,
    ap_glSamplerParameterf,
    ap_glSamplerParameterfv,
    ap_glSamplerParameterIiv,
    ap_glSamplerParameterIuiv,
    ap_glGetSamplerParameteriv,
    ap_glGetSamplerParameterIiv,
    ap_glGetSamplerParameterfv,
    ap_glGetSamplerParameterIuiv,
    ap_glQueryCounter,
    ap_glGetQueryObjecti64v,
    ap_glGetQueryObjectui64v,
    ap_glVertexAttribDivisor,
    ap_glVertexAttribP1ui,
    ap_glVertexAttribP1uiv,
    ap_glVertexAttribP2ui,
    ap_glVertexAttribP2uiv,
    ap_glVertexAttribP3ui,
    ap_glVertexAttribP3uiv,
    ap_glVertexAttribP4ui,
    ap_glVertexAttribP4uiv,
    ap_glVertexP2ui,
    ap_glVertexP2uiv,
    ap_glVertexP3ui,
    ap_glVertexP3uiv,
    ap_glVertexP4ui,
    ap_glVertexP4uiv,
    ap_glTexCoordP1ui,
    ap_glTexCoordP1uiv,
    ap_glTexCoordP2ui,
    ap_glTexCoordP2uiv,
    ap_glTexCoordP3ui,
    ap_glTexCoordP3uiv,
    ap_glTexCoordP4ui,
    ap_glTexCoordP4uiv,
    ap_glMultiTexCoordP1ui,
    ap_glMultiTexCoordP1uiv,
    ap_glMultiTexCoordP2ui,
    ap_glMultiTexCoordP2uiv,
    ap_glMultiTexCoordP3ui,
    ap_glMultiTexCoordP3uiv,
    ap_glMultiTexCoordP4ui,
    ap_glMultiTexCoordP4uiv,
    ap_glNormalP3ui,
    ap_glNormalP3uiv,
    ap_glColorP3ui,
    ap_glColorP3uiv,
    ap_glColorP4ui,
    ap_glColorP4uiv,
    ap_glSecondaryColorP3ui,
    ap_glSecondaryColorP3uiv,

    // OpenGL 4.0
    ap_glMinSampleShading,
    ap_glBlendEquationi,
    ap_glBlendEquationSeparatei,
    ap_glBlendFunci,
    ap_glBlendFuncSeparatei,
    ap_glDrawArraysIndirect,
    ap_glDrawElementsIndirect,
    ap_glUniform1d,
    ap_glUniform2d,
    ap_glUniform3d,
    ap_glUniform4d,
    ap_glUniform1dv,
    ap_glUniform2dv,
    ap_glUniform3dv,
    ap_glUniform4dv,
    ap_glUniformMatrix2dv,
    ap_glUniformMatrix3dv,
    ap_glUniformMatrix4dv,
    ap_glUniformMatrix2x3dv,
    ap_glUniformMatrix2x4dv,
    ap_glUniformMatrix3x2dv,
    ap_glUniformMatrix3x4dv,
    ap_glUniformMatrix4x2dv,
    ap_glUniformMatrix4x3dv,
    ap_glGetUniformdv,
    ap_glGetSubroutineUniformLocation,
    ap_glGetSubroutineIndex,
    ap_glGetActiveSubroutineUniformiv,
    ap_glGetActiveSubroutineUniformName,
    ap_glGetActiveSubroutineName,
    ap_glUniformSubroutinesuiv,
    ap_glGetUniformSubroutineuiv,
    ap_glGetProgramStageiv,
    ap_glPatchParameteri,
    ap_glPatchParameterfv,
    ap_glBindTransformFeedback,
    ap_glDeleteTransformFeedbacks,
    ap_glGenTransformFeedbacks,
    ap_glIsTransformFeedback,
    ap_glPauseTransformFeedback,
    ap_glResumeTransformFeedback,
    ap_glDrawTransformFeedback,
    ap_glDrawTransformFeedbackStream,
    ap_glBeginQueryIndexed,
    ap_glEndQueryIndexed,
    ap_glGetQueryIndexediv,

    // OpenGL 4.1
    ap_glReleaseShaderCompiler,
    ap_glShaderBinary,
    ap_glGetShaderPrecisionFormat,
    ap_glDepthRangef,
    ap_glClearDepthf,
    ap_glGetProgramBinary,
    ap_glProgramBinary,
    ap_glProgramParameteri,
    ap_glUseProgramStages,
    ap_glActiveShaderProgram,
    ap_glCreateShaderProgramv,
    ap_glBindProgramPipeline,
    ap_glDeleteProgramPipelines,
    ap_glGenProgramPipelines,
    ap_glIsProgramPipeline,
    ap_glGetProgramPipelineiv,
    ap_glProgramUniform1i,
    ap_glProgramUniform1iv,
    ap_glProgramUniform1f,
    ap_glProgramUniform1fv,
    ap_glProgramUniform1d,
    ap_glProgramUniform1dv,
    ap_glProgramUniform1ui,
    ap_glProgramUniform1uiv,
    ap_glProgramUniform2i,
    ap_glProgramUniform2iv,
    ap_glProgramUniform2f,
    ap_glProgramUniform2fv,
    ap_glProgramUniform2d,
    ap_glProgramUniform2dv,
    ap_glProgramUniform2ui,
    ap_glProgramUniform2uiv,
    ap_glProgramUniform3i,
    ap_glProgramUniform3iv,
    ap_glProgramUniform3f,
    ap_glProgramUniform3fv,
    ap_glProgramUniform3d,
    ap_glProgramUniform3dv,
    ap_glProgramUniform3ui,
    ap_glProgramUniform3uiv,
    ap_glProgramUniform4i,
    ap_glProgramUniform4iv,
    ap_glProgramUniform4f,
    ap_glProgramUniform4fv,
    ap_glProgramUniform4d,
    ap_glProgramUniform4dv,
    ap_glProgramUniform4ui,
    ap_glProgramUniform4uiv,
    ap_glProgramUniformMatrix2fv,
    ap_glProgramUniformMatrix3fv,
    ap_glProgramUniformMatrix4fv,
    ap_glProgramUniformMatrix2dv,
    ap_glProgramUniformMatrix3dv,
    ap_glProgramUniformMatrix4dv,
    ap_glProgramUniformMatrix2x3fv,
    ap_glProgramUniformMatrix3x2fv,
    ap_glProgramUniformMatrix2x4fv,
    ap_glProgramUniformMatrix4x2fv,
    ap_glProgramUniformMatrix3x4fv,
    ap_glProgramUniformMatrix4x3fv,
    ap_glProgramUniformMatrix2x3dv,
    ap_glProgramUniformMatrix3x2dv,
    ap_glProgramUniformMatrix2x4dv,
    ap_glProgramUniformMatrix4x2dv,
    ap_glProgramUniformMatrix3x4dv,
    ap_glProgramUniformMatrix4x3dv,
    ap_glValidateProgramPipeline,
    ap_glGetProgramPipelineInfoLog,
    ap_glVertexAttribL1d,
    ap_glVertexAttribL2d,
    ap_glVertexAttribL3d,
    ap_glVertexAttribL4d,
    ap_glVertexAttribL1dv,
    ap_glVertexAttribL2dv,
    ap_glVertexAttribL3dv,
    ap_glVertexAttribL4dv,
    ap_glVertexAttribLPointer,
    ap_glGetVertexAttribLdv,
    ap_glViewportArrayv,
    ap_glViewportIndexedf,
    ap_glViewportIndexedfv,
    ap_glScissorArrayv,
    ap_glScissorIndexed,
    ap_glScissorIndexedv,
    ap_glDepthRangeArrayv,
    ap_glDepthRangeIndexed,
    ap_glGetFloati_v,
    ap_glGetDoublei_v,

    // OpenGL 4.2
    ap_glDrawArraysInstancedBaseInstance,
    ap_glDrawElementsInstancedBaseInstance,
    ap_glDrawElementsInstancedBaseVertexBaseInstance,
    ap_glGetInternalformativ,
    ap_glGetActiveAtomicCounterBufferiv,
    ap_glBindImageTexture,
    ap_glMemoryBarrier,
    ap_glTexStorage1D,
    ap_glTexStorage2D,
    ap_glTexStorage3D,
    ap_glDrawTransformFeedbackInstanced,
    ap_glDrawTransformFeedbackStreamInstanced,

    // OpenGL 4.3
    ap_glClearBufferData,
    ap_glClearBufferSubData,
    ap_glDispatchCompute,
    ap_glDispatchComputeIndirect,
    ap_glCopyImageSubData,
    ap_glFramebufferParameteri,
    ap_glGetFramebufferParameteriv,
    ap_glGetInternalformati64v,
    ap_glInvalidateTexSubImage,
    ap_glInvalidateTexImage,
    ap_glInvalidateBufferSubData,
    ap_glInvalidateBufferData,
    ap_glInvalidateFramebuffer,
    ap_glInvalidateSubFramebuffer,
    ap_glMultiDrawArraysIndirect,
    ap_glMultiDrawElementsIndirect,
    ap_glGetProgramInterfaceiv,
    ap_glGetProgramResourceIndex,
    ap_glGetProgramResourceName,
    ap_glGetProgramResourceiv,
    ap_glGetProgramResourceLocation,
    ap_glGetProgramResourceLocationIndex,
    ap_glShaderStorageBlockBinding,
    ap_glTexBufferRange,
    ap_glTexStorage2DMultisample,
    ap_glTexStorage3DMultisample,
    ap_glTextureView,
    ap_glBindVertexBuffer,
    ap_glVertexAttribFormat,
    ap_glVertexAttribIFormat,
    ap_glVertexAttribLFormat,
    ap_glVertexAttribBinding,
    ap_glVertexBindingDivisor,
    ap_glDebugMessageControl,
    ap_glDebugMessageInsert,
    ap_glDebugMessageCallback,
    ap_glGetDebugMessageLog,
    ap_glPushDebugGroup,
    ap_glPopDebugGroup,
    ap_glObjectLabel,
    ap_glGetObjectLabel,
    ap_glObjectPtrLabel,
    ap_glGetObjectPtrLabel,

    // OpenGL 4.4
    ap_glBufferStorage,
    ap_glClearTexImage,
    ap_glClearTexSubImage,
    ap_glBindBuffersBase,
    ap_glBindBuffersRange,
    ap_glBindTextures,
    ap_glBindSamplers,
    ap_glBindImageTextures,
    ap_glBindVertexBuffers,

    // OpenGL 4.5
    ap_glClipControl,
    ap_glCreateTransformFeedbacks,
    ap_glTransformFeedbackBufferBase,
    ap_glTransformFeedbackBufferRange,
    ap_glGetTransformFeedbackiv,
    ap_glGetTransformFeedbacki_v,
    ap_glGetTransformFeedbacki64_v,
    ap_glCreateBuffers,
    ap_glNamedBufferStorage,
    ap_glNamedBufferData,
    ap_glNamedBufferSubData,
    ap_glCopyNamedBufferSubData,
    ap_glClearNamedBufferData,
    ap_glClearNamedBufferSubData,
    ap_glMapNamedBuffer,
    ap_glMapNamedBufferRange,
    ap_glUnmapNamedBuffer,
    ap_glFlushMappedNamedBufferRange,
    ap_glGetNamedBufferParameteriv,
    ap_glGetNamedBufferParameteri64v,
    ap_glGetNamedBufferPointerv,
    ap_glGetNamedBufferSubData,
    ap_glCreateFramebuffers,
    ap_glNamedFramebufferRenderbuffer,
    ap_glNamedFramebufferParameteri,
    ap_glNamedFramebufferTexture,
    ap_glNamedFramebufferTextureLayer,
    ap_glNamedFramebufferDrawBuffer,
    ap_glNamedFramebufferDrawBuffers,
    ap_glNamedFramebufferReadBuffer,
    ap_glInvalidateNamedFramebufferData,
    ap_glInvalidateNamedFramebufferSubData,
    ap_glClearNamedFramebufferiv,
    ap_glClearNamedFramebufferuiv,
    ap_glClearNamedFramebufferfv,
    ap_glClearNamedFramebufferfi,
    ap_glBlitNamedFramebuffer,
    ap_glCheckNamedFramebufferStatus,
    ap_glGetNamedFramebufferParameteriv,
    ap_glGetNamedFramebufferAttachmentParameteriv,
    ap_glCreateRenderbuffers,
    ap_glNamedRenderbufferStorage,
    ap_glNamedRenderbufferStorageMultisample,
    ap_glGetNamedRenderbufferParameteriv,
    ap_glCreateTextures,
    ap_glTextureBuffer,
    ap_glTextureBufferRange,
    ap_glTextureStorage1D,
    ap_glTextureStorage2D,
    ap_glTextureStorage3D,
    ap_glTextureStorage2DMultisample,
    ap_glTextureStorage3DMultisample,
    ap_glTextureSubImage1D,
    ap_glTextureSubImage2D,
    ap_glTextureSubImage3D,
    ap_glCompressedTextureSubImage1D,
    ap_glCompressedTextureSubImage2D,
    ap_glCompressedTextureSubImage3D,
    ap_glCopyTextureSubImage1D,
    ap_glCopyTextureSubImage2D,
    ap_glCopyTextureSubImage3D,
    ap_glTextureParameterf,
    ap_glTextureParameterfv,
    ap_glTextureParameteri,
    ap_glTextureParameterIiv,
    ap_glTextureParameterIuiv,
    ap_glTextureParameteriv,
    ap_glGenerateTextureMipmap,
    ap_glBindTextureUnit,
    ap_glGetTextureImage,
    ap_glGetCompressedTextureImage,
    ap_glGetTextureLevelParameterfv,
    ap_glGetTextureLevelParameteriv,
    ap_glGetTextureParameterfv,
    ap_glGetTextureParameterIiv,
    ap_glGetTextureParameterIuiv,
    ap_glGetTextureParameteriv,
    ap_glCreateVertexArrays,
    ap_glDisableVertexArrayAttrib,
    ap_glEnableVertexArrayAttrib,
    ap_glVertexArrayElementBuffer,
    ap_glVertexArrayVertexBuffer,
    ap_glVertexArrayVertexBuffers,
    ap_glVertexArrayAttribBinding,
    ap_glVertexArrayAttribFormat,
    ap_glVertexArrayAttribIFormat,
    ap_glVertexArrayAttribLFormat,
    ap_glVertexArrayBindingDivisor,
    ap_glGetVertexArrayiv,
    ap_glGetVertexArrayIndexediv,
    ap_glGetVertexArrayIndexed64iv,
    ap_glCreateSamplers,
    ap_glCreateProgramPipelines,
    ap_glCreateQueries,
    ap_glGetQueryBufferObjecti64v,
    ap_glGetQueryBufferObjectiv,
    ap_glGetQueryBufferObjectui64v,
    ap_glGetQueryBufferObjectuiv,
    ap_glMemoryBarrierByRegion,
    ap_glGetTextureSubImage,
    ap_glGetCompressedTextureSubImage,
    ap_glGetGraphicsResetStatus,
    ap_glGetnCompressedTexImage,
    ap_glGetnTexImage,
    ap_glGetnUniformdv,
    ap_glGetnUniformfv,
    ap_glGetnUniformiv,
    ap_glGetnUniformuiv,
    ap_glReadnPixels,
    ap_glGetnMapdv,
    ap_glGetnMapfv,
    ap_glGetnMapiv,
    ap_glGetnPixelMapfv,
    ap_glGetnPixelMapuiv,
    ap_glGetnPixelMapusv,
    ap_glGetnPolygonStipple,
    ap_glGetnColorTable,
    ap_glGetnConvolutionFilter,
    ap_glGetnSeparableFilter,
    ap_glGetnHistogram,
    ap_glGetnMinmax,
    ap_glTextureBarrier,

    // OpenGL Extensions monitored functions:
    // -------------------------------------

    // GL_NV_primitive_restart
    ap_glPrimitiveRestartNV,
    ap_glPrimitiveRestartIndexNV,

    // GL_HP_occlusion_test extension
    // No functions

    // GL_NV_occlusion_query
    ap_glGenOcclusionQueriesNV,
    ap_glDeleteOcclusionQueriesNV,
    ap_glIsOcclusionQueryNV,
    ap_glBeginOcclusionQueryNV,
    ap_glEndOcclusionQueryNV,
    ap_glGetOcclusionQueryivNV,
    ap_glGetOcclusionQueryuivNV,

    // GL_ARB_occlusion_query extension
    ap_glGenQueriesARB,
    ap_glDeleteQueriesARB,
    ap_glIsQueryARB,
    ap_glBeginQueryARB,
    ap_glEndQueryARB,
    ap_glGetQueryivARB,
    ap_glGetQueryObjectivARB,
    ap_glGetQueryObjectuivARB,

    // GL_ARB_texture_cube_map extension
    // No functions

    // GL_ARB_texture_compression extension
    ap_glCompressedTexImage3DARB,
    ap_glCompressedTexImage2DARB,
    ap_glCompressedTexImage1DARB,
    ap_glCompressedTexSubImage3DARB,
    ap_glCompressedTexSubImage2DARB,
    ap_glCompressedTexSubImage1DARB,
    ap_glGetCompressedTexImageARB,

    // GL_ARB_vertex_buffer_object extension
    ap_glBindBufferARB,
    ap_glDeleteBuffersARB,
    ap_glGenBuffersARB,
    ap_glIsBufferARB,
    ap_glBufferDataARB,
    ap_glBufferSubDataARB,
    ap_glGetBufferSubDataARB,
    ap_glMapBufferARB,
    ap_glUnmapBufferARB,
    ap_glGetBufferParameterivARB,
    ap_glGetBufferPointervARB,

    // GL_ARB_vertex_blend extension
    ap_glWeightbvARB,
    ap_glWeightsvARB,
    ap_glWeightivARB,
    ap_glWeightfvARB,
    ap_glWeightdvARB,
    ap_glWeightubvARB,
    ap_glWeightusvARB,
    ap_glWeightuivARB,
    ap_glWeightPointerARB,
    ap_glVertexBlendARB,

    // GL_EXT_texture3D extension:
    ap_glTexImage3DEXT,
    ap_glTexSubImage3DEXT,

    // GL_ARB_vertex_program:
    ap_glVertexAttrib1dARB,
    ap_glVertexAttrib1dvARB,
    ap_glVertexAttrib1fARB,
    ap_glVertexAttrib1fvARB,
    ap_glVertexAttrib1sARB,
    ap_glVertexAttrib1svARB,
    ap_glVertexAttrib2dARB,
    ap_glVertexAttrib2dvARB,
    ap_glVertexAttrib2fARB,
    ap_glVertexAttrib2fvARB,
    ap_glVertexAttrib2sARB,
    ap_glVertexAttrib2svARB,
    ap_glVertexAttrib3dARB,
    ap_glVertexAttrib3dvARB,
    ap_glVertexAttrib3fARB,
    ap_glVertexAttrib3fvARB,
    ap_glVertexAttrib3sARB,
    ap_glVertexAttrib3svARB,
    ap_glVertexAttrib4NbvARB,
    ap_glVertexAttrib4NivARB,
    ap_glVertexAttrib4NsvARB,
    ap_glVertexAttrib4NubARB,
    ap_glVertexAttrib4NubvARB,
    ap_glVertexAttrib4NuivARB,
    ap_glVertexAttrib4NusvARB,
    ap_glVertexAttrib4bvARB,
    ap_glVertexAttrib4dARB,
    ap_glVertexAttrib4dvARB,
    ap_glVertexAttrib4fARB,
    ap_glVertexAttrib4fvARB,
    ap_glVertexAttrib4ivARB,
    ap_glVertexAttrib4sARB,
    ap_glVertexAttrib4svARB,
    ap_glVertexAttrib4ubvARB,
    ap_glVertexAttrib4uivARB,
    ap_glVertexAttrib4usvARB,
    ap_glVertexAttribPointerARB,
    ap_glEnableVertexAttribArrayARB,
    ap_glDisableVertexAttribArrayARB,

    // GL_ARB_fragment_program
    ap_glProgramStringARB,
    ap_glBindProgramARB,
    ap_glDeleteProgramsARB,
    ap_glGenProgramsARB,
    ap_glProgramEnvParameter4dARB,
    ap_glProgramEnvParameter4dvARB,
    ap_glProgramEnvParameter4fARB,
    ap_glProgramEnvParameter4fvARB,
    ap_glProgramLocalParameter4dARB,
    ap_glProgramLocalParameter4dvARB,
    ap_glProgramLocalParameter4fARB,
    ap_glProgramLocalParameter4fvARB,
    ap_glGetProgramEnvParameterdvARB,
    ap_glGetProgramEnvParameterfvARB,
    ap_glGetProgramLocalParameterdvARB,
    ap_glGetProgramLocalParameterfvARB,
    ap_glGetProgramivARB,
    ap_glGetProgramStringARB,
    ap_glGetVertexAttribdvARB,
    ap_glGetVertexAttribfvARB,
    ap_glGetVertexAttribivARB,
    ap_glGetVertexAttribPointervARB,
    ap_glIsProgramARB,

    // GL_ARB_vertex_shader:
    ap_glBindAttribLocationARB,
    ap_glGetActiveAttribARB,
    ap_glGetAttribLocationARB,

    // GL_ARB_shader_objects:
    ap_glDeleteObjectARB,
    ap_glGetHandleARB,
    ap_glDetachObjectARB,
    ap_glCreateShaderObjectARB,
    ap_glShaderSourceARB,
    ap_glCompileShaderARB,
    ap_glCreateProgramObjectARB,
    ap_glAttachObjectARB,
    ap_glLinkProgramARB,
    ap_glUseProgramObjectARB,
    ap_glValidateProgramARB,
    ap_glUniform1fARB,
    ap_glUniform2fARB,
    ap_glUniform3fARB,
    ap_glUniform4fARB,
    ap_glUniform1iARB,
    ap_glUniform2iARB,
    ap_glUniform3iARB,
    ap_glUniform4iARB,
    ap_glUniform1fvARB,
    ap_glUniform2fvARB,
    ap_glUniform3fvARB,
    ap_glUniform4fvARB,
    ap_glUniform1ivARB,
    ap_glUniform2ivARB,
    ap_glUniform3ivARB,
    ap_glUniform4ivARB,
    ap_glUniformMatrix2fvARB,
    ap_glUniformMatrix3fvARB,
    ap_glUniformMatrix4fvARB,
    ap_glGetObjectParameterfvARB,
    ap_glGetObjectParameterivARB,
    ap_glGetInfoLogARB,
    ap_glGetAttachedObjectsARB,
    ap_glGetUniformLocationARB,
    ap_glGetActiveUniformARB,
    ap_glGetUniformfvARB,
    ap_glGetUniformivARB,
    ap_glGetShaderSourceARB,

    // GL_NV_vertex_program:
    ap_glAreProgramsResidentNV,
    ap_glBindProgramNV,
    ap_glDeleteProgramsNV,
    ap_glExecuteProgramNV,
    ap_glGenProgramsNV,
    ap_glGetProgramParameterdvNV,
    ap_glGetProgramParameterfvNV,
    ap_glGetProgramivNV,
    ap_glGetProgramStringNV,
    ap_glGetTrackMatrixivNV,
    ap_glGetVertexAttribdvNV,
    ap_glGetVertexAttribfvNV,
    ap_glGetVertexAttribivNV,
    ap_glGetVertexAttribPointervNV,
    ap_glIsProgramNV,
    ap_glLoadProgramNV,
    ap_glProgramParameter4dNV,
    ap_glProgramParameter4dvNV,
    ap_glProgramParameter4fNV,
    ap_glProgramParameter4fvNV,
    ap_glProgramParameters4dvNV,
    ap_glProgramParameters4fvNV,
    ap_glRequestResidentProgramsNV,
    ap_glTrackMatrixNV,
    ap_glVertexAttribPointerNV,
    ap_glVertexAttrib1dNV,
    ap_glVertexAttrib1dvNV,
    ap_glVertexAttrib1fNV,
    ap_glVertexAttrib1fvNV,
    ap_glVertexAttrib1sNV,
    ap_glVertexAttrib1svNV,
    ap_glVertexAttrib2dNV,
    ap_glVertexAttrib2dvNV,
    ap_glVertexAttrib2fNV,
    ap_glVertexAttrib2fvNV,
    ap_glVertexAttrib2sNV,
    ap_glVertexAttrib2svNV,
    ap_glVertexAttrib3dNV,
    ap_glVertexAttrib3dvNV,
    ap_glVertexAttrib3fNV,
    ap_glVertexAttrib3fvNV,
    ap_glVertexAttrib3sNV,
    ap_glVertexAttrib3svNV,
    ap_glVertexAttrib4dNV,
    ap_glVertexAttrib4dvNV,
    ap_glVertexAttrib4fNV,
    ap_glVertexAttrib4fvNV,
    ap_glVertexAttrib4sNV,
    ap_glVertexAttrib4svNV,
    ap_glVertexAttrib4ubNV,
    ap_glVertexAttrib4ubvNV,
    ap_glVertexAttribs1dvNV,
    ap_glVertexAttribs1fvNV,
    ap_glVertexAttribs1svNV,
    ap_glVertexAttribs2dvNV,
    ap_glVertexAttribs2fvNV,
    ap_glVertexAttribs2svNV,
    ap_glVertexAttribs3dvNV,
    ap_glVertexAttribs3fvNV,
    ap_glVertexAttribs3svNV,
    ap_glVertexAttribs4dvNV,
    ap_glVertexAttribs4fvNV,
    ap_glVertexAttribs4svNV,
    ap_glVertexAttribs4ubvNV,

    // GL_ATI_fragment_shader:
    ap_glGenFragmentShadersATI,
    ap_glBindFragmentShaderATI,
    ap_glDeleteFragmentShaderATI,
    ap_glBeginFragmentShaderATI,
    ap_glEndFragmentShaderATI,
    ap_glPassTexCoordATI,
    ap_glSampleMapATI,
    ap_glColorFragmentOp1ATI,
    ap_glColorFragmentOp2ATI,
    ap_glColorFragmentOp3ATI,
    ap_glAlphaFragmentOp1ATI,
    ap_glAlphaFragmentOp2ATI,
    ap_glAlphaFragmentOp3ATI,
    ap_glSetFragmentShaderConstantATI,

    // GL_EXT_vertex_shader:
    ap_glBeginVertexShaderEXT,
    ap_glEndVertexShaderEXT,
    ap_glBindVertexShaderEXT,
    ap_glGenVertexShadersEXT,
    ap_glDeleteVertexShaderEXT,
    ap_glShaderOp1EXT,
    ap_glShaderOp2EXT,
    ap_glShaderOp3EXT,
    ap_glSwizzleEXT,
    ap_glWriteMaskEXT,
    ap_glInsertComponentEXT,
    ap_glExtractComponentEXT,
    ap_glGenSymbolsEXT,
    ap_glSetInvariantEXT,
    ap_glSetLocalConstantEXT,
    ap_glVariantbvEXT,
    ap_glVariantsvEXT,
    ap_glVariantivEXT,
    ap_glVariantfvEXT,
    ap_glVariantdvEXT,
    ap_glVariantubvEXT,
    ap_glVariantusvEXT,
    ap_glVariantuivEXT,
    ap_glVariantPointerEXT,
    ap_glEnableVariantClientStateEXT,
    ap_glDisableVariantClientStateEXT,
    ap_glBindLightParameterEXT,
    ap_glBindMaterialParameterEXT,
    ap_glBindTexGenParameterEXT,
    ap_glBindTextureUnitParameterEXT,
    ap_glBindParameterEXT,
    ap_glIsVariantEnabledEXT,
    ap_glGetVariantBooleanvEXT,
    ap_glGetVariantIntegervEXT,
    ap_glGetVariantFloatvEXT,
    ap_glGetVariantPointervEXT,
    ap_glGetInvariantBooleanvEXT,
    ap_glGetInvariantIntegervEXT,
    ap_glGetInvariantFloatvEXT,
    ap_glGetLocalConstantBooleanvEXT,
    ap_glGetLocalConstantIntegervEXT,
    ap_glGetLocalConstantFloatvEXT,

    // GL_NV_fragment_program:
    ap_glProgramNamedParameter4fNV,
    ap_glProgramNamedParameter4dNV,
    ap_glProgramNamedParameter4fvNV,
    ap_glProgramNamedParameter4dvNV,
    ap_glGetProgramNamedParameterfvNV,
    ap_glGetProgramNamedParameterdvNV,

    // GL_ARB_draw_buffers:
    ap_glDrawBuffersARB,

    // GL_ATI_draw_buffers:
    ap_glDrawBuffersATI,

    // GL_ARB_multitexture:
    ap_glActiveTextureARB,
    ap_glClientActiveTextureARB,
    ap_glMultiTexCoord1dARB,
    ap_glMultiTexCoord1dvARB,
    ap_glMultiTexCoord1fARB,
    ap_glMultiTexCoord1fvARB,
    ap_glMultiTexCoord1iARB,
    ap_glMultiTexCoord1ivARB,
    ap_glMultiTexCoord1sARB,
    ap_glMultiTexCoord1svARB,
    ap_glMultiTexCoord2dARB,
    ap_glMultiTexCoord2dvARB,
    ap_glMultiTexCoord2fARB,
    ap_glMultiTexCoord2fvARB,
    ap_glMultiTexCoord2iARB,
    ap_glMultiTexCoord2ivARB,
    ap_glMultiTexCoord2sARB,
    ap_glMultiTexCoord2svARB,
    ap_glMultiTexCoord3dARB,
    ap_glMultiTexCoord3dvARB,
    ap_glMultiTexCoord3fARB,
    ap_glMultiTexCoord3fvARB,
    ap_glMultiTexCoord3iARB,
    ap_glMultiTexCoord3ivARB,
    ap_glMultiTexCoord3sARB,
    ap_glMultiTexCoord3svARB,
    ap_glMultiTexCoord4dARB,
    ap_glMultiTexCoord4dvARB,
    ap_glMultiTexCoord4fARB,
    ap_glMultiTexCoord4fvARB,
    ap_glMultiTexCoord4iARB,
    ap_glMultiTexCoord4ivARB,
    ap_glMultiTexCoord4sARB,
    ap_glMultiTexCoord4svARB,

    // GL_ARB_color_buffer_float
    ap_glClampColorARB,

    // GL_EXT_stencil_two_side
    ap_glActiveStencilFaceEXT,

    // GL_EXT_framebuffer_object
    ap_glIsRenderbufferEXT,
    ap_glBindRenderbufferEXT,
    ap_glDeleteRenderbuffersEXT,
    ap_glGenRenderbuffersEXT,
    ap_glRenderbufferStorageEXT,
    ap_glGetRenderbufferParameterivEXT,
    ap_glIsFramebufferEXT,
    ap_glBindFramebufferEXT,
    ap_glDeleteFramebuffersEXT,
    ap_glGenFramebuffersEXT,
    ap_glCheckFramebufferStatusEXT,
    ap_glFramebufferTexture1DEXT,
    ap_glFramebufferTexture2DEXT,
    ap_glFramebufferTexture3DEXT,
    ap_glFramebufferRenderbufferEXT,
    ap_glGetFramebufferAttachmentParameterivEXT,
    ap_glGenerateMipmapEXT,

    // GL_EXT_framebuffer_blit
    ap_glBlitFramebufferEXT,

    // GL_EXT_framebuffer_multisample
    ap_glRenderbufferStorageMultisampleEXT,

    // GL_ARB_framebuffer_object
    ap_glIsRenderbuffer,
    ap_glBindRenderbuffer,
    ap_glDeleteRenderbuffers,
    ap_glGenRenderbuffers,
    ap_glRenderbufferStorage,
    ap_glGetRenderbufferParameteriv,
    ap_glIsFramebuffer,
    ap_glBindFramebuffer,
    ap_glDeleteFramebuffers,
    ap_glGenFramebuffers,
    ap_glCheckFramebufferStatus,
    ap_glFramebufferTexture1D,
    ap_glFramebufferTexture2D,
    ap_glFramebufferTexture3D,
    ap_glFramebufferRenderbuffer,
    ap_glGetFramebufferAttachmentParameteriv,
    ap_glGenerateMipmap,
    ap_glBlitFramebuffer,
    ap_glRenderbufferStorageMultisample,
    ap_glFramebufferTextureLayer,

    // GL_EXT_direct_state_access
    ap_glClientAttribDefaultEXT,
    ap_glPushClientAttribDefaultEXT,
    ap_glMatrixLoadfEXT,
    ap_glMatrixLoaddEXT,
    ap_glMatrixMultfEXT,
    ap_glMatrixMultdEXT,
    ap_glMatrixLoadIdentityEXT,
    ap_glMatrixRotatefEXT,
    ap_glMatrixRotatedEXT,
    ap_glMatrixScalefEXT,
    ap_glMatrixScaledEXT,
    ap_glMatrixTranslatefEXT,
    ap_glMatrixTranslatedEXT,
    ap_glMatrixFrustumEXT,
    ap_glMatrixOrthoEXT,
    ap_glMatrixPopEXT,
    ap_glMatrixPushEXT,
    ap_glMatrixLoadTransposefEXT,
    ap_glMatrixLoadTransposedEXT,
    ap_glMatrixMultTransposefEXT,
    ap_glMatrixMultTransposedEXT,
    ap_glTextureParameterfEXT,
    ap_glTextureParameterfvEXT,
    ap_glTextureParameteriEXT,
    ap_glTextureParameterivEXT,
    ap_glTextureImage1DEXT,
    ap_glTextureImage2DEXT,
    ap_glTextureSubImage1DEXT,
    ap_glTextureSubImage2DEXT,
    ap_glCopyTextureImage1DEXT,
    ap_glCopyTextureImage2DEXT,
    ap_glCopyTextureSubImage1DEXT,
    ap_glCopyTextureSubImage2DEXT,
    ap_glGetTextureImageEXT,
    ap_glGetTextureParameterfvEXT,
    ap_glGetTextureParameterivEXT,
    ap_glGetTextureLevelParameterfvEXT,
    ap_glGetTextureLevelParameterivEXT,
    ap_glTextureImage3DEXT,
    ap_glTextureSubImage3DEXT,
    ap_glCopyTextureSubImage3DEXT,
    ap_glMultiTexParameterfEXT,
    ap_glMultiTexParameterfvEXT,
    ap_glMultiTexParameteriEXT,
    ap_glMultiTexParameterivEXT,
    ap_glMultiTexImage1DEXT,
    ap_glMultiTexImage2DEXT,
    ap_glMultiTexSubImage1DEXT,
    ap_glMultiTexSubImage2DEXT,
    ap_glCopyMultiTexImage1DEXT,
    ap_glCopyMultiTexImage2DEXT,
    ap_glCopyMultiTexSubImage1DEXT,
    ap_glCopyMultiTexSubImage2DEXT,
    ap_glGetMultiTexImageEXT,
    ap_glGetMultiTexParameterfvEXT,
    ap_glGetMultiTexParameterivEXT,
    ap_glGetMultiTexLevelParameterfvEXT,
    ap_glGetMultiTexLevelParameterivEXT,
    ap_glMultiTexImage3DEXT,
    ap_glMultiTexSubImage3DEXT,
    ap_glCopyMultiTexSubImage3DEXT,
    ap_glBindMultiTextureEXT,
    ap_glEnableClientStateIndexedEXT,
    ap_glDisableClientStateIndexedEXT,
    ap_glMultiTexCoordPointerEXT,
    ap_glMultiTexEnvfEXT,
    ap_glMultiTexEnvfvEXT,
    ap_glMultiTexEnviEXT,
    ap_glMultiTexEnvivEXT,
    ap_glMultiTexGendEXT,
    ap_glMultiTexGendvEXT,
    ap_glMultiTexGenfEXT,
    ap_glMultiTexGenfvEXT,
    ap_glMultiTexGeniEXT,
    ap_glMultiTexGenivEXT,
    ap_glGetMultiTexEnvfvEXT,
    ap_glGetMultiTexEnvivEXT,
    ap_glGetMultiTexGendvEXT,
    ap_glGetMultiTexGenfvEXT,
    ap_glGetMultiTexGenivEXT,
    ap_glGetFloatIndexedvEXT,
    ap_glGetDoubleIndexedvEXT,
    ap_glGetPointerIndexedvEXT,
    ap_glCompressedTextureImage3DEXT,
    ap_glCompressedTextureImage2DEXT,
    ap_glCompressedTextureImage1DEXT,
    ap_glCompressedTextureSubImage3DEXT,
    ap_glCompressedTextureSubImage2DEXT,
    ap_glCompressedTextureSubImage1DEXT,
    ap_glGetCompressedTextureImageEXT,
    ap_glCompressedMultiTexImage3DEXT,
    ap_glCompressedMultiTexImage2DEXT,
    ap_glCompressedMultiTexImage1DEXT,
    ap_glCompressedMultiTexSubImage3DEXT,
    ap_glCompressedMultiTexSubImage2DEXT,
    ap_glCompressedMultiTexSubImage1DEXT,
    ap_glGetCompressedMultiTexImageEXT,
    ap_glNamedProgramStringEXT,
    ap_glNamedProgramLocalParameter4dEXT,
    ap_glNamedProgramLocalParameter4dvEXT,
    ap_glNamedProgramLocalParameter4fEXT,
    ap_glNamedProgramLocalParameter4fvEXT,
    ap_glGetNamedProgramLocalParameterdvEXT,
    ap_glGetNamedProgramLocalParameterfvEXT,
    ap_glGetNamedProgramivEXT,
    ap_glGetNamedProgramStringEXT,
    ap_glNamedProgramLocalParameters4fvEXT,
    ap_glNamedProgramLocalParameterI4iEXT,
    ap_glNamedProgramLocalParameterI4ivEXT,
    ap_glNamedProgramLocalParametersI4ivEXT,
    ap_glNamedProgramLocalParameterI4uiEXT,
    ap_glNamedProgramLocalParameterI4uivEXT,
    ap_glNamedProgramLocalParametersI4uivEXT,
    ap_glGetNamedProgramLocalParameterIivEXT,
    ap_glGetNamedProgramLocalParameterIuivEXT,
    ap_glTextureParameterIivEXT,
    ap_glTextureParameterIuivEXT,
    ap_glGetTextureParameterIivEXT,
    ap_glGetTextureParameterIuivEXT,
    ap_glMultiTexParameterIivEXT,
    ap_glMultiTexParameterIuivEXT,
    ap_glGetMultiTexParameterIivEXT,
    ap_glGetMultiTexParameterIuivEXT,
    ap_glProgramUniform1fEXT,
    ap_glProgramUniform2fEXT,
    ap_glProgramUniform3fEXT,
    ap_glProgramUniform4fEXT,
    ap_glProgramUniform1iEXT,
    ap_glProgramUniform2iEXT,
    ap_glProgramUniform3iEXT,
    ap_glProgramUniform4iEXT,
    ap_glProgramUniform1fvEXT,
    ap_glProgramUniform2fvEXT,
    ap_glProgramUniform3fvEXT,
    ap_glProgramUniform4fvEXT,
    ap_glProgramUniform1ivEXT,
    ap_glProgramUniform2ivEXT,
    ap_glProgramUniform3ivEXT,
    ap_glProgramUniform4ivEXT,
    ap_glProgramUniformMatrix2fvEXT,
    ap_glProgramUniformMatrix3fvEXT,
    ap_glProgramUniformMatrix4fvEXT,
    ap_glProgramUniformMatrix2x3fvEXT,
    ap_glProgramUniformMatrix3x2fvEXT,
    ap_glProgramUniformMatrix2x4fvEXT,
    ap_glProgramUniformMatrix4x2fvEXT,
    ap_glProgramUniformMatrix3x4fvEXT,
    ap_glProgramUniformMatrix4x3fvEXT,
    ap_glProgramUniform1uiEXT,
    ap_glProgramUniform2uiEXT,
    ap_glProgramUniform3uiEXT,
    ap_glProgramUniform4uiEXT,
    ap_glProgramUniform1uivEXT,
    ap_glProgramUniform2uivEXT,
    ap_glProgramUniform3uivEXT,
    ap_glProgramUniform4uivEXT,
    ap_glNamedBufferDataEXT,
    ap_glNamedBufferSubDataEXT,
    ap_glMapNamedBufferEXT,
    ap_glUnmapNamedBufferEXT,
    ap_glMapNamedBufferRangeEXT,
    ap_glFlushMappedNamedBufferRangeEXT,
    ap_glNamedCopyBufferSubDataEXT,
    ap_glGetNamedBufferParameterivEXT,
    ap_glGetNamedBufferPointervEXT,
    ap_glGetNamedBufferSubDataEXT,
    ap_glTextureBufferEXT,
    ap_glMultiTexBufferEXT,
    ap_glNamedRenderbufferStorageEXT,
    ap_glGetNamedRenderbufferParameterivEXT,
    ap_glCheckNamedFramebufferStatusEXT,
    ap_glNamedFramebufferTexture1DEXT,
    ap_glNamedFramebufferTexture2DEXT,
    ap_glNamedFramebufferTexture3DEXT,
    ap_glNamedFramebufferRenderbufferEXT,
    ap_glGetNamedFramebufferAttachmentParameterivEXT,
    ap_glGenerateTextureMipmapEXT,
    ap_glGenerateMultiTexMipmapEXT,
    ap_glFramebufferDrawBufferEXT,
    ap_glFramebufferDrawBuffersEXT,
    ap_glFramebufferReadBufferEXT,
    ap_glGetFramebufferParameterivEXT,
    ap_glNamedRenderbufferStorageMultisampleEXT,
    ap_glNamedRenderbufferStorageMultisampleCoverageEXT,
    ap_glNamedFramebufferTextureEXT,
    ap_glNamedFramebufferTextureLayerEXT,
    ap_glNamedFramebufferTextureFaceEXT,
    ap_glTextureRenderbufferEXT,
    ap_glMultiTexRenderbufferEXT,

    // AP_GL_EXT_bindable_uniform
    ap_glUniformBufferEXT,
    ap_glGetUniformBufferSizeEXT,
    ap_glGetUniformOffsetEXT,

    // GL_EXT_texture_integer
    ap_glTexParameterIivEXT,
    ap_glTexParameterIuivEXT,
    ap_glGetTexParameterIivEXT,
    ap_glGetTexParameterIuivEXT,
    ap_glClearColorIiEXT,
    ap_glClearColorIuiEXT,

    // GL_EXT_multi_draw_arrays
    ap_glMultiDrawArraysEXT,
    ap_glMultiDrawElementsEXT,

    // GL_ARB_multisample
    ap_glSampleCoverageARB,

    // GL_EXT_blend_minmax
    ap_glBlendEquationEXT,

    // GL_EXT_geometry_shader4
    ap_glProgramParameteriEXT,
    ap_glFramebufferTextureEXT,
    ap_glFramebufferTextureLayerEXT,
    ap_glFramebufferTextureFaceEXT,

    // GL_NV_shader_buffer_load
    ap_glMakeBufferResidentNV,
    ap_glMakeBufferNonResidentNV,
    ap_glIsBufferResidentNV,
    ap_glMakeNamedBufferResidentNV,
    ap_glMakeNamedBufferNonResidentNV,
    ap_glNamedMakeBufferResidentNV,
    ap_glNamedMakeBufferNonResidentNV,
    ap_glIsNamedBufferResidentNV,
    ap_glGetBufferParameterui64vNV,
    ap_glGetNamedBufferParameterui64vNV,
    ap_glGetIntegerui64vNV,
    ap_glUniformui64NV,
    ap_glUniformui64vNV,
    ap_glGetUniformui64vNV,
    ap_glProgramUniformui64NV,
    ap_glProgramUniformui64vNV,

    // GL_NV_vertex_buffer_unified_memory
    ap_glBufferAddressRangeNV,
    ap_glVertexFormatNV,
    ap_glNormalFormatNV,
    ap_glColorFormatNV,
    ap_glIndexFormatNV,
    ap_glTexCoordFormatNV,
    ap_glEdgeFlagFormatNV,
    ap_glSecondaryColorFormatNV,
    ap_glFogCoordFormatNV,
    ap_glVertexAttribFormatNV,
    ap_glVertexAttribIFormatNV,
    ap_glGetIntegerui64i_vNV,

    // GL_AMD_debug_output
    ap_glDebugMessageEnableAMD,
    ap_glDebugMessageInsertAMD,
    ap_glDebugMessageCallbackAMD,
    ap_glGetDebugMessageLogAMD,

    // GL_AMDX_debug_output
    ap_glDebugMessageEnableAMDX,
    ap_glDebugMessageInsertAMDX,
    ap_glDebugMessageCallbackAMDX,
    ap_glGetDebugMessageLogAMDX,

    // GL_ARB_debug_output
    ap_glDebugMessageControlARB,
    ap_glDebugMessageInsertARB,
    ap_glDebugMessageCallbackARB,
    ap_glGetDebugMessageLogARB,

    // GL_EXT_draw_instanced
    ap_glDrawArraysInstancedEXT,
    ap_glDrawElementsInstancedEXT,

    // GL_ARB_draw_instanced
    ap_glDrawArraysInstancedARB,
    ap_glDrawElementsInstancedARB,

    // GL_EXT_texture_buffer_object
    ap_glTexBufferEXT,

    // GL_EXT_compiled_vertex_array
    ap_glLockArraysEXT,
    ap_glUnlockArraysEXT,

    // GL_ARB_transpose_matrix
    ap_glLoadTransposeMatrixfARB,
    ap_glLoadTransposeMatrixdARB,
    ap_glMultTransposeMatrixfARB,
    ap_glMultTransposeMatrixdARB,

    // GL_ARB_point_parameters
    ap_glPointParameterfARB,
    ap_glPointParameterfvARB,

    // GL_ARB_matrix_palette
    ap_glCurrentPaletteMatrixARB,
    ap_glMatrixIndexubvARB,
    ap_glMatrixIndexusvARB,
    ap_glMatrixIndexuivARB,
    ap_glMatrixIndexPointerARB,

    // GL_ARB_window_pos
    ap_glWindowPos2dARB,
    ap_glWindowPos2fARB,
    ap_glWindowPos2iARB,
    ap_glWindowPos2sARB,
    ap_glWindowPos2dvARB,
    ap_glWindowPos2fvARB,
    ap_glWindowPos2ivARB,
    ap_glWindowPos2svARB,
    ap_glWindowPos3dARB,
    ap_glWindowPos3fARB,
    ap_glWindowPos3iARB,
    ap_glWindowPos3sARB,
    ap_glWindowPos3dvARB,
    ap_glWindowPos3fvARB,
    ap_glWindowPos3ivARB,
    ap_glWindowPos3svARB,

    // GL_ARB_fragment_program_shadow
    // No new functions

    // GL_ARB_half_float_pixel
    // No new functions

    // GL_ARB_texture_float
    // No new functions

    // GL_ARB_pixel_buffer_object
    // No new functions

    // GL_ARB_depth_buffer_float
    // No new functions

    // GL_ARB_framebuffer_sRGB
    // No new functions

    // GL_ARB_geometry_shader4
    ap_glProgramParameteriARB,
    ap_glFramebufferTextureARB,
    ap_glFramebufferTextureLayerARB,
    ap_glFramebufferTextureFaceARB,

    // GL_ARB_half_float_vertex
    // No new functions

    // GL_ARB_instanced_arrays
    ap_glVertexAttribDivisorARB,

    // GL_ARB_map_buffer_range
    ap_glMapBufferRange,
    ap_glFlushMappedBufferRange,

    // GL_ARB_texture_buffer_object
    ap_glTexBufferARB,

    // GL_ARB_texture_compression_rgtc
    // No new functions

    // GL_ARB_texture_rg
    // No new functions

    // GL_ARB_vertex_array_object
    ap_glBindVertexArray,
    ap_glDeleteVertexArrays,
    ap_glGenVertexArrays,
    ap_glIsVertexArray,

    // GL_ARB_uniform_buffer_object
    ap_glGetUniformIndices,
    ap_glGetActiveUniformsiv,
    ap_glGetActiveUniformName,
    ap_glGetUniformBlockIndex,
    ap_glGetActiveUniformBlockiv,
    ap_glGetActiveUniformBlockName,
    ap_glUniformBlockBinding,

    // GL_ARB_copy_buffer
    ap_glCopyBufferSubData,

    // GL_ARB_draw_elements_base_vertex
    ap_glDrawElementsBaseVertex,
    ap_glDrawRangeElementsBaseVertex,
    ap_glDrawElementsInstancedBaseVertex,
    ap_glMultiDrawElementsBaseVertex,

    // GL_ARB_provoking_vertex
    ap_glProvokingVertex,

    // GL_ARB_sync
    ap_glFenceSync,
    ap_glIsSync,
    ap_glDeleteSync,
    ap_glClientWaitSync,
    ap_glWaitSync,
    ap_glGetInteger64v,
    ap_glGetSynciv,

    // GL_ARB_texture_multisample
    ap_glTexImage2DMultisample,
    ap_glTexImage3DMultisample,
    ap_glGetMultisamplefv,
    ap_glSampleMaski,

    // GL_ARB_cl_event
    ap_glCreateSyncFromCLeventARB,

    // GL_APPLE_aux_depth_stencil
    // No new functions

    // GL_APPLE_client_storage
    // No new functions

    // GL_APPLE_element_array
    ap_glElementPointerAPPLE,
    ap_glDrawElementArrayAPPLE,
    ap_glDrawRangeElementArrayAPPLE,
    ap_glMultiDrawElementArrayAPPLE,
    ap_glMultiDrawRangeElementArrayAPPLE,

    // GL_APPLE_fence

    ap_glGenFencesAPPLE,
    ap_glDeleteFencesAPPLE,
    ap_glSetFenceAPPLE,
    ap_glIsFenceAPPLE,
    ap_glTestFenceAPPLE,
    ap_glFinishFenceAPPLE,
    ap_glTestObjectAPPLE,
    ap_glFinishObjectAPPLE,

    // GL_APPLE_float_pixels
    // No new functions

    // GL_APPLE_flush_buffer_range
    ap_glBufferParameteriAPPLE,
    ap_glFlushMappedBufferRangeAPPLE,

    // GL_APPLE_flush_render
    // No new functions
    //TO_DO: search for this functions (spec is unavailable on the net)
    // ap_glFlushRenderAPPLE,
    // ap_glFinishRenderAPPLE,

    // GL_APPLE_object_purgeable
    ap_glObjectPurgeableAPPLE,
    ap_glObjectUnpurgeableAPPLE,
    ap_glGetObjectParameterivAPPLE,

    // GL_APPLE_packed_pixels
    // No new functions

    // GL_APPLE_pixel_buffer
    // No new functions
    //TO_DO: search for this functions (spec is unavailable on the net)

    // GL_APPLE_specular_vector
    // No new functions

    // GL_APPLE_texture_range
    ap_glTextureRangeAPPLE,
    ap_glGetTexParameterPointervAPPLE,

    // GL_APPLE_transform_hint
    // No new functions

    // GL_APPLE_vertex_array_object
    ap_glBindVertexArrayAPPLE,
    ap_glDeleteVertexArraysAPPLE,

    ap_glGenVertexArraysAPPLE,
    ap_glIsVertexArrayAPPLE,

    // GL_APPLE_vertex_array_range
    ap_glVertexArrayRangeAPPLE,
    ap_glFlushVertexArrayRangeAPPLE,
    ap_glVertexArrayParameteriAPPLE,

    // GL_APPLE_vertex_program_evaluators
    ap_glEnableVertexAttribAPPLE,
    ap_glDisableVertexAttribAPPLE,
    ap_glIsVertexAttribEnabledAPPLE,
    ap_glMapVertexAttrib1dAPPLE,
    ap_glMapVertexAttrib1fAPPLE,
    ap_glMapVertexAttrib2dAPPLE,
    ap_glMapVertexAttrib2fAPPLE,

    // GL_APPLE_ycbcr_422
    // No new functions

    // Add new extensions here:


#if AMDT_BUILD_TARGET == AMDT_WINDOWS_OS

    //////////////////////////////////////////////////////////////////////////
    // WGL Extensions monitored functions:
    //////////////////////////////////////////////////////////////////////////

    // WGL_ARB_extensions_string
    ap_wglGetExtensionsStringARB,

    // WGL_I3D_genlock Extension
    ap_wglEnableGenlockI3D,
    ap_wglDisableGenlockI3D,
    ap_wglIsEnabledGenlockI3D,
    ap_wglGenlockSourceI3D,
    ap_wglGetGenlockSourceI3D,
    ap_wglGenlockSourceEdgeI3D,
    ap_wglGetGenlockSourceEdgeI3D,
    ap_wglGenlockSampleRateI3D,
    ap_wglGetGenlockSampleRateI3D,
    ap_wglGenlockSourceDelayI3D,
    ap_wglGetGenlockSourceDelayI3D,
    ap_wglQueryGenlockMaxSourceDelayI3D,

    // WGL_ARB_pbuffer
    ap_wglCreatePbufferARB,
    ap_wglGetPbufferDCARB,
    ap_wglReleasePbufferDCARB,
    ap_wglDestroyPbufferARB,
    ap_wglQueryPbufferARB,

    // WGL_ARB_pixel_format
    ap_wglGetPixelFormatAttribivARB,
    ap_wglGetPixelFormatAttribfvARB,
    ap_wglChoosePixelFormatARB,

    // WGL_ARB_make_current_read
    ap_wglMakeContextCurrentARB,
    ap_wglGetCurrentReadDCARB,

    // WGL_ARB_render_texture
    ap_wglBindTexImageARB,
    ap_wglReleaseTexImageARB,
    ap_wglSetPbufferAttribARB,

    // WGL_ARB_buffer_region
    ap_wglCreateBufferRegionARB,
    ap_wglDeleteBufferRegionARB,
    ap_wglSaveBufferRegionARB,
    ap_wglRestoreBufferRegionARB,

    // WGL_ARB_multisample
    // See GL_ARB_multisample

    // WGL_ARB_pixel_format_float
    // See GL_ARB_color_buffer_float

    // WGL_ARB_framebuffer_sRGB
    // No new functions

    // WGL_ARB_create_context
    ap_wglCreateContextAttribsARB,

    // WGL_EXT_swap_control
    ap_wglSwapIntervalEXT,
    ap_wglGetSwapIntervalEXT,

    // WGL_NV_present_video
    ap_wglEnumerateVideoDevicesNV,
    ap_wglBindVideoDeviceNV,
    ap_wglQueryCurrentContextNV,

    // WGL_NV_video_out
    ap_wglGetVideoDeviceNV,
    ap_wglReleaseVideoDeviceNV,
    ap_wglBindVideoImageNV,
    ap_wglReleaseVideoImageNV,
    ap_wglSendPbufferToVideoNV,
    ap_wglGetVideoInfoNV,

    // WGL_NV_swap_group
    ap_wglJoinSwapGroupNV,
    ap_wglBindSwapBarrierNV,
    ap_wglQuerySwapGroupNV,
    ap_wglQueryMaxSwapGroupsNV,
    ap_wglQueryFrameCountNV,
    ap_wglResetFrameCountNV,

    // WGL_NV_gpu_affinity
    ap_wglEnumGpusNV,
    ap_wglEnumGpuDevicesNV,
    ap_wglCreateAffinityDCNV,
    ap_wglEnumGpusFromAffinityDCNV,
    ap_wglDeleteDCNV,

    // WGL_AMD_gpu_association
    ap_wglGetGPUIDsAMD,
    ap_wglGetGPUInfoAMD,
    ap_wglGetContextGPUIDAMD,
    ap_wglCreateAssociatedContextAMD,
    ap_wglCreateAssociatedContextAttribsAMD,
    ap_wglDeleteAssociatedContextAMD,
    ap_wglMakeAssociatedContextCurrentAMD,
    ap_wglGetCurrentAssociatedContextAMD,
    ap_wglBlitContextFramebufferAMD,

#elif ((AMDT_BUILD_TARGET == AMDT_LINUX_OS) && (AMDT_LINUX_VARIANT == AMDT_GENERIC_LINUX_VARIANT))

    //////////////////////////////////////////////////////////////////////////
    // GLX Extensions monitored functions:
    //////////////////////////////////////////////////////////////////////////

    // GLX_SGIX_fbconfig
    ap_glXGetFBConfigAttribSGIX,
    ap_glXChooseFBConfigSGIX,
    ap_glXCreateGLXPixmapWithConfigSGIX,
    ap_glXCreateContextWithConfigSGIX,
    ap_glXGetVisualFromFBConfigSGIX,
    ap_glXGetFBConfigFromVisualSGIX,

    // GLX_SGI_video_sync
    ap_glXGetVideoSyncSGI,
    ap_glXWaitVideoSyncSGI,

    // GLX_ARB_get_proc_address
    // See above

    // GLX_ARB_multisample
    // See GL_ARB_multisample

    // GLX_ARB_fbconfig_float
    // See GL_ARB_color_buffer_float

    // GLX_ARB_framebuffer_sRGB
    // See GL_ARB_framebuffer_sRGB

    // GLX_SGIX_pbuffer
    ap_glXCreateGLXPbufferSGIX,
    ap_glXDestroyGLXPbufferSGIX,
    ap_glXQueryGLXPbufferSGIX,
    ap_glXSelectEventSGIX,
    ap_glXGetSelectedEventSGIX,

#elif ((AMDT_BUILD_TARGET == AMDT_LINUX_OS) && (AMDT_LINUX_VARIANT == AMDT_MAC_OS_X_LINUX_VARIANT))
    //////////////////////////////////////////////////////////////////////////
    // CGL Extension monitored functions:
    //////////////////////////////////////////////////////////////////////////

#endif

    // Graphic Remedy Extensions:

    // GL_GREMEDY_string_marker functions:
    ap_glStringMarkerGREMEDY,

    // GL_GREMEDY_frame_terminator function:
    ap_glFrameTerminatorGREMEDY,

    // Last extension function:
    apLastOpenGLExtensionFunction = ap_glFrameTerminatorGREMEDY,

    apLastOpenGLFunction = apLastOpenGLExtensionFunction,

#if (AMDT_BUILD_TARGET == AMDT_WINDOWS_OS)

    // OpenGL ES, EGL and Extensions monitored functions:
    // -------------------------------------------------

    apFirstOpenGLESFunction,

    // EGL 1.1 functions:
    ap_eglGetError = apFirstOpenGLESFunction,
    ap_eglGetDisplay,
    ap_eglInitialize,
    ap_eglTerminate,
    ap_eglQueryString,
    ap_eglGetProcAddress,
    ap_eglGetConfigs,
    ap_eglChooseConfig,
    ap_eglGetConfigAttrib,
    ap_eglCreateWindowSurface,
    ap_eglCreatePixmapSurface,
    ap_eglCreatePbufferSurface,
    ap_eglDestroySurface,
    ap_eglQuerySurface,
    ap_eglSurfaceAttrib,
    ap_eglBindTexImage,
    ap_eglReleaseTexImage,
    ap_eglSwapInterval,
    ap_eglCreateContext,
    ap_eglDestroyContext,
    ap_eglMakeCurrent,
    ap_eglGetCurrentContext,
    ap_eglGetCurrentSurface,
    ap_eglGetCurrentDisplay,
    ap_eglQueryContext,
    ap_eglWaitGL,
    ap_eglWaitNative,
    ap_eglSwapBuffers,
    ap_eglCopyBuffers,

    //////////////////////////////////////////////////////////////////////////
    // EGL Extensions
    //////////////////////////////////////////////////////////////////////////

    // NVIDIA EGL extensions:
    ap_eglMakeWindowNV,
    ap_eglDestroyWindowNV,
#endif // (AMDT_BUILD_TARGET == AMDT_WINDOWS_OS)

#if ((AMDT_BUILD_TARGET == AMDT_WINDOWS_OS) || ((AMDT_BUILD_TARGET == AMDT_LINUX_OS) && (AMDT_LINUX_VARIANT == AMDT_MAC_OS_X_LINUX_VARIANT)))

    // OpenGL ES Core functions:
    ap_glAlphaFuncx,
    ap_glClearColorx,
    // ap_glClearDepthf, // Appears in OpenGL 4.1
    ap_glClearDepthx,
    ap_glClipPlanef,
    ap_glClipPlanex,
    ap_glColor4x,
    // ap_glDepthRangef, // Appears in OpenGL 4.1
    ap_glDepthRangex,
    ap_glFogx,
    ap_glFogxv,
    ap_glFrustumf,
    ap_glFrustumx,
    ap_glGetClipPlanef,
    ap_glGetClipPlanex,
    ap_glGetFixedv,
    ap_glGetLightxv,
    ap_glGetMaterialxv,
    ap_glGetTexEnvxv,
    ap_glGetTexParameterxv,
    ap_glLightModelx,
    ap_glLightModelxv,
    ap_glLightx,
    ap_glLightxv,
    ap_glLineWidthx,
    ap_glLoadMatrixx,
    ap_glMaterialx,
    ap_glMaterialxv,
    ap_glMultMatrixx,
    ap_glMultiTexCoord4x,
    ap_glNormal3x,
    ap_glOrthof,
    ap_glOrthox,
    ap_glPointParameterx,
    ap_glPointParameterxv,
    ap_glPointSizex,
    ap_glPolygonOffsetx,
    ap_glRotatex,
    ap_glSampleCoveragex,
    ap_glScalex,
    ap_glTexEnvx,
    ap_glTexEnvxv,
    ap_glTexParameterx,
    ap_glTexParameterxv,
    ap_glTranslatex,

    // OES_draw_texture:
    ap_glDrawTexsOES,
    ap_glDrawTexiOES,
    ap_glDrawTexxOES,
    ap_glDrawTexsvOES,
    ap_glDrawTexivOES,
    ap_glDrawTexxvOES,
    ap_glDrawTexfOES,
    ap_glDrawTexfvOES,

#if (AMDT_BUILD_TARGET == AMDT_WINDOWS_OS)
    apLastOpenGLESFunction = ap_glDrawTexfvOES,
#endif
#else // ((AMDT_BUILD_TARGET == AMDT_WINDOWS_OS) || ((AMDT_BUILD_TARGET == AMDT_LINUX_OS) && (AMDT_LINUX_VARIANT == AMDT_MAC_OS_X_LINUX_VARIANT)))
    // If we don't support OpenGL ES, we want the first-last range to be impossible:
    apFirstOpenGLESFunction,
    apLastOpenGLESFunction = apLastOpenGLExtensionFunction,
#endif // ((AMDT_BUILD_TARGET == AMDT_WINDOWS_OS) || ((AMDT_BUILD_TARGET == AMDT_LINUX_OS) && (AMDT_LINUX_VARIANT == AMDT_MAC_OS_X_LINUX_VARIANT)))

#if ((AMDT_BUILD_TARGET == AMDT_LINUX_OS) && (AMDT_LINUX_VARIANT == AMDT_MAC_OS_X_LINUX_VARIANT))

    // GL_OES_blend_subtract:
    ap_glBlendEquationOES,

    // GL_OES_framebuffer_object:
    ap_glIsRenderbufferOES,
    ap_glBindRenderbufferOES,
    ap_glDeleteRenderbuffersOES,
    ap_glGenRenderbuffersOES,
    ap_glRenderbufferStorageOES,
    ap_glGetRenderbufferParameterivOES,
    ap_glIsFramebufferOES,
    ap_glBindFramebufferOES,
    ap_glDeleteFramebuffersOES,
    ap_glGenFramebuffersOES,
    ap_glCheckFramebufferStatusOES,
    ap_glFramebufferRenderbufferOES,
    ap_glFramebufferTexture2DOES,
    ap_glGetFramebufferAttachmentParameterivOES,
    ap_glGenerateMipmapOES,

    // GL_OES_mapbuffer:
    ap_glGetBufferPointervOES,
    ap_glMapBufferOES,
    ap_glUnmapBufferOES,

    // OES_matrix_palette:
    ap_glCurrentPaletteMatrixOES,
    ap_glLoadPaletteFromModelViewMatrixOES,
    ap_glMatrixIndexPointerOES,
    ap_glWeightPointerOES,

    // OES_point_size_array:
    ap_glPointSizePointerOES,

    // OpenGL ES 2.0:
    ap_glGetShaderPrecisionFormat,
    ap_glShaderBinary,
    ap_glReleaseShaderCompiler,

    // EAGL Obj-C functions:
    ap_EAGLContext_initWithAPI,
    ap_EAGLContext_initWithAPI_sharegroup,
    ap_EAGLContext_dealloc,
    ap_EAGLContext_setCurrentContext,
    ap_EAGLContext_currentContext,
    ap_EAGLContext_API,
    ap_EAGLContext_sharegroup,
    ap_EAGLContext_renderbufferStorage_fromDrawable,
    ap_EAGLContext_presentRenderbuffer,

    // EAGL C functions:
    ap_EAGLGetVersion,

    apLastOpenGLESFunction = ap_EAGLGetVersion,
#endif

    // OpenCL monitored functions:
    // ---------------------------

    // First OpenCL function index:
    apFirstOpenCLFunction,

    ap_clGetPlatformIDs = apFirstOpenCLFunction,
    ap_clGetPlatformInfo,
    ap_clGetDeviceIDs,
    ap_clGetDeviceInfo,
    ap_clCreateSubDevices,
    ap_clRetainDevice,
    ap_clReleaseDevice,
    ap_clCreateContext,
    ap_clCreateContextFromType,
    ap_clRetainContext,
    ap_clReleaseContext,
    ap_clGetContextInfo,
    ap_clCreateCommandQueue,
    ap_clRetainCommandQueue,
    ap_clReleaseCommandQueue,
    ap_clGetCommandQueueInfo,
    ap_clSetCommandQueueProperty,
    ap_clCreateBuffer,
    ap_clCreateSubBuffer,
    ap_clCreateImage,
    ap_clCreateImage2D,
    ap_clCreateImage3D,
    ap_clRetainMemObject,
    ap_clReleaseMemObject,
    ap_clGetSupportedImageFormats,
    ap_clGetMemObjectInfo,
    ap_clGetImageInfo,
    ap_clSetMemObjectDestructorCallback,
    ap_clCreateSampler,
    ap_clRetainSampler,
    ap_clReleaseSampler,
    ap_clGetSamplerInfo,
    ap_clCreateProgramWithSource,
    ap_clCreateProgramWithBinary,
    ap_clCreateProgramWithBuiltInKernels,
    ap_clRetainProgram,
    ap_clReleaseProgram,
    ap_clBuildProgram,
    ap_clCompileProgram,
    ap_clLinkProgram,
    ap_clUnloadPlatformCompiler,
    ap_clUnloadCompiler,
    ap_clGetProgramInfo,
    ap_clGetProgramBuildInfo,
    ap_clCreateKernel,
    ap_clCreateKernelsInProgram,
    ap_clRetainKernel,
    ap_clReleaseKernel,
    ap_clSetKernelArg,
    ap_clGetKernelInfo,
    ap_clGetKernelArgInfo,
    ap_clGetKernelWorkGroupInfo,
    ap_clWaitForEvents,
    ap_clGetEventInfo,
    ap_clCreateUserEvent,
    ap_clRetainEvent,
    ap_clReleaseEvent,
    ap_clSetUserEventStatus,
    ap_clSetEventCallback,
    ap_clGetEventProfilingInfo,
    ap_clFlush,
    ap_clFinish,
    ap_clEnqueueReadBuffer,
    ap_clEnqueueReadBufferRect,
    ap_clEnqueueWriteBuffer,
    ap_clEnqueueWriteBufferRect,
    ap_clEnqueueFillBuffer,
    ap_clEnqueueCopyBuffer,
    ap_clEnqueueCopyBufferRect,
    ap_clEnqueueReadImage,
    ap_clEnqueueWriteImage,
    ap_clEnqueueFillImage,
    ap_clEnqueueCopyImage,
    ap_clEnqueueCopyImageToBuffer,
    ap_clEnqueueCopyBufferToImage,
    ap_clEnqueueMapBuffer,
    ap_clEnqueueMapImage,
    ap_clEnqueueUnmapMemObject,
    ap_clEnqueueMigrateMemObjects,
    ap_clEnqueueNDRangeKernel,
    ap_clEnqueueTask,
    ap_clEnqueueNativeKernel,
    ap_clEnqueueMarkerWithWaitList,
    ap_clEnqueueBarrierWithWaitList,
    ap_clSetPrintfCallback,
    ap_clGetExtensionFunctionAddressForPlatform,
    ap_clEnqueueMarker,
    ap_clEnqueueWaitForEvents,
    ap_clEnqueueBarrier,
    ap_clGetExtensionFunctionAddress,
    ap_clCreateFromGLBuffer,
    ap_clCreateFromGLTexture,
    ap_clCreateFromGLTexture2D,
    ap_clCreateFromGLTexture3D,
    ap_clCreateFromGLRenderbuffer,
    ap_clGetGLObjectInfo,
    ap_clGetGLTextureInfo,
    ap_clEnqueueAcquireGLObjects,
    ap_clEnqueueReleaseGLObjects,
    ap_clGetGLContextInfoKHR,

    // Last OpenCL base function index:
    apLastOpenCLBaseFunction = ap_clGetGLContextInfoKHR,

    // OpenCL 2.0.
    // Note that the base function pointer is above this point, since we do not require OpenCL 2.0 support as base, currently:
    ap_clCreateCommandQueueWithProperties,
    ap_clCreatePipe,
    ap_clGetPipeInfo,
    ap_clSVMAlloc,
    ap_clSVMFree,
    ap_clCreateSamplerWithProperties,
    ap_clSetKernelArgSVMPointer,
    ap_clSetKernelExecInfo,
    ap_clEnqueueSVMFree,
    ap_clEnqueueSVMMemcpy,
    ap_clEnqueueSVMMemFill,
    ap_clEnqueueSVMMap,
    ap_clEnqueueSVMUnmap,

    // Graphic Remedy Extensions:

    // cl_amd_computation_frame functions:
    ap_clBeginComputationFrameAMD,
    ap_clEndComputationFrameAMD,

    // cl_amd_object_naming functions:
    ap_clNameContextAMD,
    ap_clNameCommandQueueAMD,
    ap_clNameMemObjectAMD,
    ap_clNameSamplerAMD,
    ap_clNameProgramAMD,
    ap_clNameKernelAMD,
    ap_clNameEventAMD,

    // cl_khr_gl_event:
    ap_clCreateEventFromGLsyncKHR,

    // cl_khr_dx9_media_sharing:
    ap_clGetDeviceIDsFromDX9MediaAdapterKHR,
    ap_clCreateFromDX9MediaSurfaceKHR,
    ap_clEnqueueAcquireDX9MediaSurfacesKHR,
    ap_clEnqueueReleaseDX9MediaSurfacesKHR,

    // cl_khr_d3d10_sharing:
    ap_clGetDeviceIDsFromD3D10KHR,
    ap_clCreateFromD3D10BufferKHR,
    ap_clCreateFromD3D10Texture2DKHR,
    ap_clCreateFromD3D10Texture3DKHR,
    ap_clEnqueueAcquireD3D10ObjectsKHR,
    ap_clEnqueueReleaseD3D10ObjectsKHR,

    // cl_khr_d3d11_sharing:
    ap_clGetDeviceIDsFromD3D11KHR,
    ap_clCreateFromD3D11BufferKHR,
    ap_clCreateFromD3D11Texture2DKHR,
    ap_clCreateFromD3D11Texture3DKHR,
    ap_clEnqueueAcquireD3D11ObjectsKHR,
    ap_clEnqueueReleaseD3D11ObjectsKHR,

    // Last OpenCL extension function index:
    apLastOpenCLExtensionFunction = ap_clEnqueueReleaseD3D11ObjectsKHR,
    apLastOpenCLFunction = apLastOpenCLExtensionFunction,

    // Will get the amount of monitored functions:
    apMonitoredFunctionsAmount
};


#endif  // __APMONITOREDFUNCTIONID
