# -*- Python -*-

Import('*')
from CXL_init import *

libName = "CXLCpuCallstackSampling"

env = CXL_env.Clone()

env.Append( CPPPATH = [ 
	".",
	"..",
	"inc",
	env['CXL_commonproj_dir'],
	env['CXL_commonproj_dir'] + '/../../CodeXL/Components/CpuProfiling',
])

# NOTE: Do not change the order of the two lines here
initLibDwarf (env)
initLibElf (env)

env.Append (LIBS = [
	"CXLBaseTools",
	"CXLOSWrappers",
	"CXLExecutableFormat",
	"CXLDisassembler",
])

sources = \
[
	"src/CallGraph.cpp",
	"src/CallSite.cpp",
	"src/CallStack.cpp",
	"src/CallStackBuilder.cpp",
	"src/CssReader.cpp",
	"src/CssWriter.cpp",
	"src/FunctionGraph.cpp",
]

# Creating object files	
objFiles = env.SharedObject(sources)

# Creating shared libraries
soFiles = env.SharedLibrary(
	target = libName, 
	source = objFiles)

# Installing libraries
libInstall = env.Install( 
	dir = env['CXL_lib_dir'], 
	source = (soFiles))

Return('libInstall')
