# -*- Python -*-

from CXL_init import *

Import('*')

libName = "CXLAPIClasses"

env = CXL_env.Clone()
env.Append( CPPPATH = [ 
	".",
	env['CXL_commonproj_dir'],
	env['CXL_commonproj_dir'] + "/AMDTOSWrappers/Include",
])

UseAPPSDK(env);

sources = \
[
	"src/ap2DPoint.cpp",
	"src/ap2DRectangle.cpp",
	"src/apAPIFunctionId.cpp",
	"src/apAIDFunctions.cpp",
	"src/apAllocatedObject.cpp",
	"src/apAPIConnectionType.cpp",
	"src/apApiFunctionsInitializationData.cpp",
	"src/apAPIVersion.cpp",
	"src/apApplicationModesEventsType.cpp",
	"src/apBasicParameters.cpp",
	"src/apBreakPoint.cpp",
	"src/apCLBuffer.cpp",
	"src/apCLCommandQueue.cpp",
	"src/apCLContext.cpp",
	"src/apCLContextProperties.cpp",
	"src/apCLDevice.cpp",
	"src/apCLEnqueuedCommands.cpp",
	"src/apCLEvent.cpp",
	"src/apCLImage.cpp",
	"src/apCLKernel.cpp",
	"src/apCLMemObject.cpp",
	"src/apCLObjectID.cpp",
	"src/apCLPipe.cpp",
	"src/apCLProgram.cpp",
	"src/apCLSampler.cpp",
	"src/apCLSubBuffer.cpp",
	"src/apContextID.cpp",
	"src/apCounterID.cpp",
	"src/apCounterInfo.cpp",
	"src/apCounterScope.cpp",
	"src/apDebugProjectSettings.cpp",
	"src/apDefaultTextureNames.cpp",
	"src/apDetectedErrorParameters.cpp",
	"src/apDisplayBuffer.cpp",
	"src/apEnumeratorUsageStatistics.cpp",
	"src/apErrorCode.cpp",
	"src/apExpression.cpp",
	"src/apFileType.cpp",
#	"src/apFPSDisplayItem.cpp",
	"src/apFunctionCall.cpp",
	"src/apFunctionCallStatistics.cpp",
	"src/apFunctionDeprecation.cpp",
	"src/apGenericBreakpoint.cpp",
	"src/apGLComputeShader.cpp",
	"src/apGLDebugOutput.cpp",
	"src/apGLDisplayList.cpp",
	"src/apGLenumParameter.cpp",
	"src/apGLFBO.cpp",
	"src/apGLFragmentShader.cpp",
	"src/apGLGeometryShader.cpp",
	"src/apGLItemsCollection.cpp",
	"src/apGLPipeline.cpp",
	"src/apGLProgram.cpp",
	"src/apGLRenderBuffer.cpp",
	"src/apGLSampler.cpp",
	"src/apGLShaderObject.cpp",
	"src/apGLSync.cpp",
	"src/apGLTessellationControlShader.cpp",
	"src/apGLTessellationEvaluationShader.cpp",
	"src/apGLTransformFeedbackObject.cpp",
	"src/apGLTexture.cpp",
	"src/apGLTextureMipLevel.cpp",
	"src/apGLTextureMiplevelData.cpp",
	"src/apGLTextureParameter.cpp",
	"src/apGLTextureParams.cpp",
	"src/apGLUnsupportedShader.cpp",
	"src/apGLVBO.cpp",
	"src/apGLVertexShader.cpp",
	"src/apGLPixelInternalFormatParameter.cpp",
	"src/apGLRenderContextInfo.cpp",
	"src/apGLRenderContextGraphicsInfo.cpp",
	"src/apGPUInfo.cpp",
#	"src/apHeadsUpDisplayItem.cpp",
	"src/apiClassesInitFunc.cpp",
	"src/apInternalFormat.cpp",
#	"src/apLoadedModule.cpp",
	"src/apKernelFunctionNameBreakpoint.cpp",
	"src/apKernelSourceCodeBreakpoint.cpp",
	"src/apMonitoredFunctionBreakPoint.cpp",
	"src/apMonitoredFunctionsManager.cpp",
	"src/apOpenCLErrorParameters.cpp",
	"src/apOpenCLParameters.cpp",
	"src/apOpenCLQueueCommandsCategories.cpp",
	"src/apOpenGLBuiltInUniformManager.cpp",
	"src/apOpenGLESExtensionId.cpp",
	"src/apOpenGLExtensionsId.cpp",
	"src/apOpenGLParameters.cpp",
	"src/apOpenGLStateVariablesManager.cpp",
	"src/apOSRelatedParameters.cpp",
	"src/apParameters.cpp",
	"src/apPBuffer.cpp",
	"src/apPointerParameterCreator.cpp",
	"src/apProjectSettings.cpp",
	"src/apRasterMode.cpp",
	"src/apRenderPrimitivesStatistics.cpp",
	"src/apSingeltonsDelete.cpp",
	"src/apSourceCodeBreakpoint.cpp",
	"src/apStateVariablesSnapShot.cpp",
	"src/apStaticBuffer.cpp",
	"src/apStatistics.cpp",
	"src/apTextureType.cpp",
	"src/apHostSourceBreakPoint.cpp",

# Events:
	"Events/src/apAddWatchEvent.cpp",
	"Events/src/apAfterKernelDebuggingEvent.cpp",
	"Events/src/apApiConnectionEndedEvent.cpp",
	"Events/src/apApiConnectionEstablishedEvent.cpp",
	"Events/src/apBeforeDebuggedProcessRunResumedEvent.cpp",
	"Events/src/apBeforeKernelDebuggingEvent.cpp",
	"Events/src/apBreakpointHitEvent.cpp",
	"Events/src/apBreakpointsUpdatedEvent.cpp",
	"Events/src/apCallStackFrameSelectedEvent.cpp",
	"Events/src/apComputeContextCreatedEvent.cpp",
	"Events/src/apComputeContextDeletedEvent.cpp",
	"Events/src/apContextDataSnapshotWasUpdatedEvent.cpp",
	"Events/src/apHexChangedEvent.cpp",
	"Events/src/apDebuggedProcessCreatedEvent.cpp",
	"Events/src/apDebuggedProcessCreationFailureEvent.cpp",
	"Events/src/apDebuggedProcessDetectedErrorEvent.cpp",
	"Events/src/apDebuggedProcessIsDuringTerminationEvent.cpp",
	"Events/src/apDebuggedProcessOutputStringEvent.cpp",
	"Events/src/apDebuggedProcessRunResumedEvent.cpp",
	"Events/src/apDebuggedProcessRunStartedEvent.cpp",
	"Events/src/apDebuggedProcessRunStartedExternallyEvent.cpp",
	"Events/src/apDebuggedProcessRunSuspendedEvent.cpp",
	"Events/src/apDebuggedProcessTerminatedEvent.cpp",
	"Events/src/apDeferredCommandEvent.cpp",
	"Events/src/apFlushTextureImageEvent.cpp",
	"Events/src/apKernelDebuggingFailedEvent.cpp",
	"Events/src/apKernelDebuggingInterruptedEvent.cpp",
	"Events/src/apKernelWorkItemChangedEvent.cpp",
	"Events/src/apMDIViewActivatedEvent.cpp",
	"Events/src/apMDIViewCreateEvent.cpp",
	"Events/src/apMemoryAllocationFailureEvent.cpp",
	"Events/src/apModuleLoadedEvent.cpp",
	"Events/src/apModuleUnloadedEvent.cpp",
	"Events/src/apEvent.cpp",
	"Events/src/apEventsHandler.cpp",
	"Events/src/apExecutionModeChangedEvent.cpp",
	"Events/src/apExceptionEvent.cpp",
	"Events/src/apGDBErrorEvent.cpp",
	"Events/src/apGDBListenerThreadWasSuspendedEvent.cpp",
	"Events/src/apGDBOutputStringEvent.cpp",
	"Events/src/apGLDebugOutputMessageEvent.cpp",
	"Events/src/apIEventsFiller.cpp",
	"Events/src/apIEventsObserver.cpp",
	"Events/src/apInfrastructureEndsBeingBusyEvent.cpp",
	"Events/src/apInfrastructureFailureEvent.cpp",
	"Events/src/apInfrastructureStartsBeingBusyEvent.cpp",
	"Events/src/apKernelSourceBreakpointsUpdatedEvent.cpp",
	"Events/src/apMemoryLeakEvent.cpp",
	"Events/src/apMonitoredObjectsTreeEvent.cpp",
	"Events/src/apSearchingForMemoryLeaksEvent.cpp",
	"Events/src/apOpenCLErrorEvent.cpp",
	"Events/src/apOpenCLProgramBuildEvent.cpp",
	"Events/src/apOpenCLProgramBuildFailedWithDebugFlagsEvent.cpp",
	"Events/src/apOpenCLProgramCreatedEvent.cpp",
	"Events/src/apOpenCLProgramDeletedEvent.cpp",
	"Events/src/apOpenCLQueueCreatedEvent.cpp",
	"Events/src/apOpenCLQueueDeletedEvent.cpp",
	"Events/src/apOutputDebugStringEvent.cpp",
	"Events/src/apProfileProcessTerminatedEvent.cpp",
	"Events/src/apProfileProgressEvent.cpp",
	"Events/src/apRenderContextCreatedEvent.cpp",
	"Events/src/apRenderContextDeletedEvent.cpp",
	"Events/src/apSpyProgressEvent.cpp",
	"Events/src/apTechnologyMonitorFailureEvent.cpp",
	"Events/src/apThreadCreatedEvent.cpp",
	"Events/src/apThreadTerminatedEvent.cpp",
	"Events/src/apUserWarningEvent.cpp",
#linuVariantSource
	"src/apGLXParameters.cpp",
]

env.Prepend( LIBS = 
[
	"CXLBaseTools",
	"CXLOSWrappers",
	"CXLOSAPIWrappers",
])

# Creating object files	
objFiles = env.SharedObject(sources)

if (env['CXL_build_type'] == 'static'):
	soFiles = env.StaticLibrary(
	target = libName,
	source = objFiles)
else:
	# Creating shared libraries
	soFiles = env.SharedLibrary(
	target = libName,
	source = objFiles)


# Installing libraries
libInstall = env.Install( 
	dir = env['CXL_lib_dir'], 
	source = (soFiles))

Return('libInstall')
