#!/bin/bash

# PwrProf requires bash. Do not remove the above shebang line!

# ----------------------------------------------------------------------------------------------------------------------------------
# File name: CodeXLPowerProfiler 
# This script sets the PowerProfiler's related environment variables and and driver
#
# (c) 2014 Advanced Micro Devices Inc. All Rights Reserved.
# ----------------------------------------------------------------------------------------------------------------------------------


# Get this script full path:

if echo "$0" | grep '^/' ; then
	thisScriptFullPath="$0"
else
	thisScriptFullPath=`pwd`/$0
fi

# Enable the use of symbolic links to the script
if [ -h ${thisScriptFullPath} ]
then
    LINKTARGET=`readlink -f "$thisScriptFullPath"`
    thisScriptFullPath=${LINKTARGET}
fi

# PwrProf's binaries directory is this scripts directory:
PwrProfBinariesDir=`dirname "$thisScriptFullPath"`

# Calculate PwrProf's binary executable path:
PwrProfBinaryExePath="${PwrProfBinariesDir}/CodeXLPowerProfiler-bin"

# Obtain libstdc++ needed version
CRUNTIMEPATH=$(ldconfig -p | grep libstdc++.so.6 | grep 64)
if [ -z "$CRUNTIMEPATH" ] ; then
   CRUNTIMEPATH=$(/sbin/ldconfig -p | grep libstdc++.so.6 | grep 64)
fi
CRUNTIMEFILE=${CRUNTIMEPATH##*>}
# Test if current system C++ runtime is older from CodeXL version needed
CXL_CLIB=""
NEWCRUNTIME=$(strings $CRUNTIMEFILE | grep GLIBCXX_3.4.16)
if [ -z "$NEWCRUNTIME" ];then
    # System C++ runtime is older from CodeXL
    CXL_CLIB="${PwrProfBinariesDir}/RuntimeLibs"
fi

# Add PwrProf's binaries directory to LD_LIBRARY_PATH:
if [ -z "$LD_LIBRARY_PATH" ]; then
	export LD_LIBRARY_PATH="${PwrProfBinariesDir}:${CXL_CLIB}"
else
	export LD_LIBRARY_PATH="${PwrProfBinariesDir}:${CXL_CLIB}:$LD_LIBRARY_PATH"
fi

# Run PwrProf:
eval "$PwrProfBinaryExePath $@"
