#
# Main scons build file for GLServer
#

Import('GPS_env')
env = GPS_env.Clone()
env['CPPPATH'] = env['GPS_PATH']
env.Prepend (CPPPATH =
[
    '../Common/Linux',
    '../../../Common/Lib/Ext/tinyxml/2.6.2',
])

env.Prepend(CCFLAGS =
[
    '-Wall',
    '-Wextra',
])

# build the Common Server static library

sources = \
[
    # TinyXML
    "../../../Common/Lib/Ext/tinyxml/2.6.2/tinystr.cpp",
    "../../../Common/Lib/Ext/tinyxml/2.6.2/tinyxmlparser.cpp",
    "../../../Common/Lib/Ext/tinyxml/2.6.2/tinyxml.cpp",
    "../../../Common/Lib/Ext/tinyxml/2.6.2/tinyxmlerror.cpp",

    # Files needed for GPA
    "../../../Common/Src/GPUPerfAPIUtils/GPUPerfAPILoader.cpp",
    "../../../Common/Src/GPUPerfAPIUtils/GPUPerfAPIUtil.cpp",
#    "../../../Common/Src/ADLUtil/ADLUtil.cpp",
#    "../../../Common/Src/AMDTMutex/AMDTMutex.cpp",

    "BufferDelta.cpp",
    "Capture.cpp",
    "CaptureLayer.cpp",
    "CaptureStream.cpp",
    "CommandProcessor.cpp",
    "CommandTimingManager.cpp",
    "CommandVisitor.cpp",
    "Communication_Impl.cpp",
    "Compressor.cpp",
    "DeltaAccumulationBuffer.cpp",
    "ErrorImage.cpp",
    "HookTimer.cpp",
    "FDPipeline.cpp",
    "FDPipelineShaderStage.cpp",
    "FDPipelineStage.cpp",
    "FrameDebugger.cpp",
    "FrameInfo.cpp",
    "FrameProfiler.cpp",
    "FrameStatsLogger.cpp",
    "geometry.cpp",
    "GraphicsServerState.cpp",
    "HTTPRequest.cpp",
    "HUDTextureVisualization.cpp",
    "IMonitor.cpp",
    "IServerPlugin_Impl.cpp",
    "LayerManager.cpp",
    "Logger.cpp",
    "MemoryBuffer.cpp",
    "misc.cpp",
    "ModernAPIFrameDebuggerLayer.cpp",
    "ModernAPIFrameProfilerLayer.cpp",
    "ModernAPILayerManager.cpp",
    "NamedEvent.cpp",
    "NamedMutex.cpp",
    "NamedSemaphore.cpp",
    "NetSocket.cpp",
    "ObjectDatabaseProcessor.cpp",
    "parser.cpp",
    "SaveImage.cpp",
    "SessionManager.cpp",
    "SharedGlobal.cpp",
    "SharedMemory.cpp",
    "SharedMemoryManager.cpp",
    "StreamLog.cpp",
    "TimeControlLayer.cpp",
    "timer.cpp",
    "TraceAnalyzer.cpp",
    "TraceMetadata.cpp",
    "Tracing/APIEntry.cpp",
    "Tracing/MultithreadedTraceAnalyzerLayer.cpp",
    "Tracing/ThreadTraceData.cpp",
    "WrappedObjectDatabase.cpp",
    "xml.cpp",

    # Linux files
    "Linux/proc.cpp",
    "Linux/Interceptor.cpp",
    "Linux/OSWrappers.cpp",
    "Linux/SafeCRT.cpp",
    "Linux/timerLinux.cpp"
]

Common = env.StaticLibrary('Common', sources)
Return('Common')
