# -*- Python -*-

Import('*')
from CXL_init import *

libName = "CXLTaskInfo"

env = CXL_env.Clone()

env.Append( CPPPATH = [ 
    ".",
    env['CXL_commonproj_dir'],
    env['CXL_common_dir'] + '/../CodeXL/Components/CpuProfiling',
    env['CXL_common_dir'] + '/../CodeXL/Components/CpuProfiling/ProfilingAgents',
])

env.Append(CPPFLAGS = '-fno-strict-aliasing')

env.Append (LIBS = [
	"CXLBaseTools",
	"CXLOSWrappers",
	"CXLProfilingAgentsData",
])

sources = \
[
    "src/JitTaskInfo.cpp",
]

# Creating object files
objFiles = env.SharedObject(sources)

# Creating shared libraries
soFiles = env.SharedLibrary(
	target = libName, 
	source = objFiles)

# Installing libraries
libInstall = env.Install( 
	dir = env['CXL_lib_dir'], 
	source = (soFiles))

Return('libInstall')
