# -*- Python -*-

Import('*')
from CXL_init import *

libName = "CXLProfilingAgentsData"

env = CXL_env.Clone()

env.Append( CPPPATH = [ 
	"inc",
	"..",
	env['CXL_commonproj_dir'],
	env['CXL_common_dir'] + '/Lib/Ext/Java/jdk1.7.0_17/include',
	env['CXL_common_dir'] + '/Lib/Ext/Java/jdk1.7.0_17/include/linux',
	env['CXL_commonproj_dir'] + '/../../CodeXL/Components/CpuProfiling',
])

initLibElf (env)

env.Append (LIBS = [
	"CXLBaseTools",
	"CXLOSWrappers",
])

sources = \
[
	"src/JclReader.cpp",
	"src/JclWriter.cpp",
	"src/OclJncReader.cpp",
	"src/Linux/ElfJncWriter.cpp",
	"src/Linux/JavaJncReader_Lin.cpp",
]

# Creating object files	
objFiles = env.SharedObject(sources)

# Creating shared libraries
soFiles = env.SharedLibrary(
	target = libName, 
	source = objFiles)

# Installing libraries
libInstall = env.Install( 
	dir = env['CXL_lib_dir'], 
	source = (soFiles))

Return('libInstall')
