# -*- Python -*-

import os

from CXL_init import *

Import('*')

appName = "CXLClassicMatMul-bin"

env = CXL_env.Clone()

#env.Append(CXL_commonproj_dir = env['CXL_common_dir'] + "/../CommonProjects")
compiler_base_flags = " -Wall -g -fmessage-length=0 -Wno-unknown-pragmas -pthread -D_DEBUG "
env.Replace(CPPFLAGS = compiler_base_flags)

env.Append( CPPPATH = [ 
    "./",
])

env.Append( LIBPATH = [
    env['CXL_Examples_dir']  + "/release",
])

# Source files:
sources = \
[
# src:
	"AMDTClassicMatMul.cpp",
]

commonLinkedLibraries = \
[
]

linkedLibraries = commonLinkedLibraries
env.Prepend (LIBS = linkedLibraries)


# Set the ELF hash generation mode:
# - When building on new systems, we would like to generate both sysv and gnu ELF hashes.
#   This enables running the executable also on old systems, that support only the sysv ELF hash.
# - When building on old systems, we need to set the GR_GENERATE_ONLY_DEFAULT_ELF_HASH environment
#   variable (preferably in the .bashrc file). Otherwise the link will fail when trying to
#   generate an ELF hash type that the old linker does not recognize.
# [Yaki 7/7/2009]
linkerFlags = [] 
shouldGenerateOnlyDefaultELFHash = os.environ.get('GR_GENERATE_ONLY_DEFAULT_ELF_HASH')
if shouldGenerateOnlyDefaultELFHash is None:
    linkerFlags += [ "-Wl,--hash-style=both,-lz,-lrt" ]

# Creating executable
exe = env.Program(
	target = appName, 
    source = sources,
	LINKFLAGS = linkerFlags)

# Installing libraries
libInstall = env.Install( 
    dir = env['CXL_lib_dir'], 
    source = (exe))

Return('libInstall')
