# -*- Python -*-

Import('*')
from CXL_init import *

libName = "CXLCpuPerfEventUtils"

env = CXL_env.Clone()

env.Append( CPPPATH = [ 
	".",
	"inc",
	"..",
	env['CXL_commonproj_dir'],
])

UseQtNoGraphics(env)

env.Append (LIBS = [
	"CXLBaseTools",
])

sources = \
[
	"src/DcConfig.cpp",
	"src/EventEncoding.cpp",
	"src/EventEngine.cpp",
	"src/EventsFile.cpp",
	"src/ViewConfig.cpp",
]

# Creating object files	
objFiles = env.SharedObject(sources)

# Creating shared libraries
soFiles = env.SharedLibrary(
	target = libName, 
	source = objFiles)

# Installing libraries
libInstall = env.Install( 
	dir = env['CXL_lib_dir'], 
	source = (soFiles))

Return('libInstall')
