#!/bin/sh

# This script build all Linux projects.
# Usage: buildAllLinuxProjects [scons arguments]

export commandLineArgs=$*

NUM_ERRORS=0

# Display a start message:
echo 
echo 
echo "Building all Linux projects"
echo "==========================="
echo "Build arguments passed to scons: $commandLineArgs"

# Change my work directory to Workspaces:
cd $AMD_CODEXL/Components/GpuDebugging/

# Build all Linux projects:

echo
echo
echo "-------- Building AMDTProcessDebugger -------- "
cd AMDTProcessDebugger
eval "scons $commandLineArgs" 
RC=$?
NUM_ERRORS=`expr ${NUM_ERRORS} + ${RC}`
cd ..

echo
echo
echo "-------- Building AMDTApiFunctions -------- "
cd AMDTApiFunctions
eval "scons $commandLineArgs"
RC=$?
NUM_ERRORS=`expr ${NUM_ERRORS} + ${RC}`
cd ..

echo
echo
echo "-------- Building AMDTServerUtilities -------- "
cd AMDTServerUtilities
eval "scons $commandLineArgs"
RC=$?
NUM_ERRORS=`expr ${NUM_ERRORS} + ${RC}`
cd ..

pwd
echo
echo
echo "-------- Building GRemedy OpenCL Server -------- "
cd AMDTOpenCLServer
eval "scons $commandLineArgs"
RC=$?
NUM_ERRORS=`expr ${NUM_ERRORS} + ${RC}`
cd ..

echo
echo
echo "-------- Building GRemedy OpenGL Server -------- "
cd AMDTOpenGLServer
eval "scons $commandLineArgs"
RC=$?
NUM_ERRORS=`expr ${NUM_ERRORS} + ${RC}`
cd ..

echo
echo
echo "-------- Building AMDTGpuDebuggingComponents -------- "
cd  AMDTGpuDebuggingComponents
eval "scons $commandLineArgs"
RC=$?
NUM_ERRORS=`expr ${NUM_ERRORS} + ${RC}`
cd ..

echo
echo
echo "-------- Building AMDTGpuDebugging -------- "
cd  AMDTGpuDebugging
eval "scons $commandLineArgs"
RC=$?
NUM_ERRORS=`expr ${NUM_ERRORS} + ${RC}`
cd ..

if [ ${NUM_ERRORS} -ne 0 ]
then
    echo "*** ERROR ***"
    echo "*** the build failed - see the logs for details ***"
    exit 1
else
    echo
    echo
    exit 0
fi
